### ISSUE TITLE
Code 101

### ISSUE THREAD

**Issue by ZiGmaX809** [xCss/Valine#104]
之前都是正常使用，今天开始出现
Code 101: Class or object doesn't exists.
也无法进行回复，回复后一直loading。
地址：http://www.zigma.cc
请问大佬解决方法。

**Comment by xCss** [comment]
额，我这正常啊。。。
![qq 20180723235102](https://user-images.githubusercontent.com/10877162/43087799-47e013b4-8ed3-11e8-8b95-0af42e15befa.png)
