### ISSUE TITLE
请问能否拿到评论数量？

### ISSUE THREAD

**Issue by samotoo** [xCss/Valine#105]
你好大师，

已经用上了Valine做评论系统，非常感谢。

请问有什么办法可以拿到一篇文章的评论数？我想在页面的某个地方显示评论数。

非常感谢！

**Comment by xCss** [comment]
参考 https://github.com/xCss/Valine/releases/tag/v1.1.8-beta2

**Comment by samotoo** [comment]
非常感谢，顺利解决！
