### ISSUE TITLE
Code -1:  Request has been terminated

### ISSUE THREAD

**Issue by ZeroneCat** [xCss/Valine#107]
按照网站的步骤进行操作，回复框下显示：
`Code -1: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.`

本地和在线都是这样。见：https://zeronecat.github.io/TeXt2/welcome.html 

LeanCloud上注册了新app、暂未设安全域名，依然报错。

**Comment by xCss** [comment]
![qq 20180813141403](https://user-images.githubusercontent.com/10877162/44015406-5b2666ea-9f03-11e8-86a8-1c8758da0561.png)

``` js
new Valine({
    el: '#vcomments',
    appId: 'site.comments.valine.app_id',
    appKey: 'site.comments.valine.app_key',
    notify:false,
    verify:false,
    avatar:'mm',
    placeholder:'Just Go Go'
    });
```

你的`appid`和`appKey`确定正确吗？

**Comment by ZeroneCat** [comment]
乌龙了，忘记加{{}}，太不仔细，不好意思
