### ISSUE TITLE
从主页点进文章无法加载出评论，刷新后才可加载出Valine

### ISSUE THREAD

**Issue by lmtsunnie** [xCss/Valine#109]
例如：
先进入 https://limengting.site 再点击某一篇文章，发现网页加载完毕后仍然无法加载出评论，但是刷新后可以加载出评论
直接通过网址 https://limengting.site/2018/08/25/leetcode169/ 也可以加载出评论
以上情况出现在macOS chrome/firefox/safari以及ios chrome/firefox/safari中

**Comment by link9596** [comment]
使用pjax会出现这种情况 pjax不会重新加载尾部的js 应该是这样
