### ISSUE TITLE
移动端不显示评论

### ISSUE THREAD

**Issue by WiseHou** [xCss/Valine#11]
浏览器内核blink（m40），截图是作者你的[博客](https://ioliu.cn/2017/add-valine-comments-to-your-blog/)。
[如图](http://ww4.sinaimg.cn/large/0060lm7Tly1fknaaeevrij30f00qoabi.jpg)

**Comment by xCss** [comment]
@WiseHou 已修复，请更新后重试。
感谢反馈~
