### ISSUE TITLE
关于评论数显示？

### ISSUE THREAD

**Issue by jerryc127** [xCss/Valine#112]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

我在html写下 
![image](https://user-images.githubusercontent.com/16351105/44959299-7dd83080-af1e-11e8-92e9-3b29a7226dba.png)
为什么会显示不正确
例如 https://jerryc.me/posts/d6615de0/#%E4%BD%BF%E7%94%A8ArrayAdapter%E5%89%B5%E5%BB%BAListView
里面已经有评论了 但是评论数还是显示为0

**Comment by xCss** [comment]
我这边看到的是
```
Code 403: Access denied by api domain white list, Please check your security domain. 
```

**Comment by jerryc127** [comment]
@xCss z这个我也不清楚 我大陆访问是跳到coding.me  其他的跳到github 不知道为什么访问coding.me 时会出现Code 403: Access denied by api domain white list, Please check your security domain.

**Comment by xCss** [comment]
`403`错误是因为你的`安全域名`没设置`https`

**Comment by jerryc127** [comment]
@xCss  设置了啊
![image](https://user-images.githubusercontent.com/16351105/44974723-17d9c080-af93-11e8-98b1-e75052d19227.png)

我github page 没报错Code 403: Access denied by api domain white list, Please check your security domain.  只有coding.me 会显示

**Comment by xCss** [comment]
。。。

哦，是因为没有设置http

**Comment by jerryc127** [comment]
想问下我的网页缺了哪个元素 我想要显示正确的评论数，你二楼写的是 阅读量的连接

**Comment by jerryc127** [comment]
已解决 改为 data-xid=url_for(page.path) 让其获得连接地址

谢谢解答
