### ISSUE TITLE
博主能不能收到留言的邮件通知？

### ISSUE THREAD

**Issue by hyrepo** [xCss/Valine#116]
有人留言后博主有没有办法收到邮件通知？看了一下LeanCloud的设置没找到相应的地方

**Comment by xCss** [comment]
抱歉，由于leancloud的限制，博主不能收到留言通知！~

**Comment by APPLLEJN** [comment]
请问，现在还是不可以么？

**Comment by tanjuntao** [comment]
+1 按照 wiki 页面的教程配置了，收不到邮件通知。

**Comment by xCss** [comment]
@tanjuntao https://github.com/zhaojun1998/Valine-Admin
