### ISSUE TITLE
关于css解释的一点小问题

### ISSUE THREAD

**Issue by MonoLogueChi** [xCss/Valine#117]
群友发现的一个问题
在评论中使用<style></style>标签可以修改页面样式

```
<style>body{width:40%}</style>
```

![image](https://user-images.githubusercontent.com/26868745/46025438-7d951480-c11b-11e8-9b16-11861cac26d7.png)

![image](https://user-images.githubusercontent.com/26868745/46025674-13c93a80-c11c-11e8-8b3b-653a691fba58.png)

**Comment by xCss** [comment]
收到，感谢反馈，将在下个版本修复~
