### ISSUE TITLE
不同用户头像是怎么显示的？

### ISSUE THREAD

**Issue by mapan2020** [xCss/Valine#12]
我想了解下头像是怎么实现的，有的人在给文章评论时候，他的头像是特殊的，和默认的不一致，这个是怎么实现的呢？是根据邮箱匹配头像的吗？

**Comment by xCss** [comment]
@mapan2020 不同用户头像需要自己创建`Gravatar`账户，并上传头像即可，评论显示的是自己上传的头像。如果没有上传就是默认头像。
已计划在`v1.1.7正式版`中加入头像配置，可配置项请参考：https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
