### ISSUE TITLE
提问：可不可以加收到留言短信提醒

### ISSUE THREAD

**Issue by Mabbs** [xCss/Valine#122]
我看LeanCloud支持短信，可不可以在收到评论后短信提醒。
如果支持短信提醒，我就把Gitalk换掉:-P

**Comment by xCss** [comment]
![qq 20181019092616](https://user-images.githubusercontent.com/10877162/47192656-0c92f680-d381-11e8-9123-44d52c7684ff.png)

短信不免费，而且，你认为用户会留电话在你的博客上吗？
