### ISSUE TITLE
未知错误导致无法评论

### ISSUE THREAD

**Issue by ya0guang** [xCss/Valine#124]
If you want to report a bug, please provide the following information:

- The steps to reproduce.

今天搭建valine时，评论组建下方显示，评论提交后没有回显，LeanCloud后台也看不到任何数据与请求

> code：

，应该是错误代码没有显示，如图：
![image](https://user-images.githubusercontent.com/12580159/47431058-a74e6380-d7cd-11e8-9bab-e985a43ee700.png)

#### 网址demo
https://ya0guang.github.io/rfid-on-rpi/

除了visitor设置true之外全部使用默认设置，安全中心已经添加

#### F12 network
410响应码

![image](https://user-images.githubusercontent.com/12580159/47431339-322f5e00-d7ce-11e8-9cbb-4d002abcfb2d.png)

##### 回传json
![image](https://user-images.githubusercontent.com/12580159/47431590-baadfe80-d7ce-11e8-88f0-c421a439b077.png)

{"ttl":3600,"push_router_server":"router-g0-push.leancloud.cn","api_server":"api.leancloud.cn","location":"https:\/\/api.leancloud.cn\/1.1\/classes\/Comment?where=%7B%22%24or%22%3A%5B%7B%22rid%22%3A%7B%22%24exists%22%3Afalse%7D%7D%2C%7B%22rid%22%3A%22%22%7D%5D%2C%22url%22%3A%22%2Frfid-on-rpi%2F%22%7D&order=-createdAt%2C-insertedAt&limit=0&count=1&redirectByAPI=cn"}

四个410的请求ttl都是3600，猜测和这个有关。

- Which versions of Valine, and which browser / OS are affected by this issue?

hexo3.8.0，NexT主题6.4.2，Valine v1.3.3, firefox 62.0 chrome ie 于win10上结果相同

**Comment by Rocinantie** [comment]
同样的问题，去你博客测试了下，提交评论之后下方的 code 会闪一下。

**Comment by cnsuer** [comment]
同样的问题

**Comment by xCss** [comment]
抱歉，暂时没发现什么问题，已给Leancloud官方发了issues [#557](https://github.com/leancloud/javascript-sdk/issues/557)。

> Ps. 请确保你的`appId`和`appKey`准确。

**Comment by leeyeh** [comment]
你好，你的 appId 的前 5 位是 `appid`，我猜是复制的时候没有删掉原来的占位符。

**Comment by xCss** [comment]
@ya0guang @Rocinantie @cnsuer

**Comment by cnsuer** [comment]
问题解决了,真是个神奇的问题，我的appId是: UA0rSPvaoDhmmyQQWnk0zdPw-gzGzoHsz 但我填的appId是: 'UA0rSPvaoDhmmyQQWnk0zdPw',也就是没有填写 ‘-gzGzoHsz ‘，但是，但是，但是，竟然可以评论成功！！！！！。。。这么低级的错误，抱歉抱歉，麻烦大家了。。。。。 
 [昨天的commit](https://github.com/cnsuer/cnsuer.github.io/blob/90e67f6485ac6c61fdee4aa8cc147d49acddd8f3/index.html)
 [今天的commit](https://github.com/cnsuer/cnsuer.github.io/blob/master/index.html)
有问题的可以看下是不是这个问题，因为我的错误提示和你的一样,评论框后边也显示这个
![地址](https://user-images.githubusercontent.com/12580159/47431058-a74e6380-d7cd-11e8-9bab-e985a43ee700.png)

**Comment by xCss** [comment]
@cnsuer 你的是因为使用了`Next`主题自带的`阅读量统计`，关了试试。
