### ISSUE TITLE
并不想要填写网址怎么设置

### ISSUE THREAD

**Issue by vxhly** [xCss/Valine#13]
版本信息： hexo-theme-next | Merged v1.1.7-rc3
在实际使用中，有些用户并没有想填写网址的意愿，怎么设置

**Comment by insekkei** [comment]
不能定制简直太残暴了，竟然还说什么可以fork自己改，怎么不说“你可以自己去写一个评论系统，想怎样就怎样”，_(:3 」∠)_

**Comment by vxhly** [comment]
大兄弟冷静发自我的iPhone------------------ 原始邮件 ------------------发件人: insekkei  <notifications@github.com>发送时间: 2017年10月28日 21:54收件人: xCss/Valine <Valine@noreply.github.com>抄送: 星火燎原 <pengchengou@gmail.com>, Author <author@noreply.github.com>主题: 回复：[xCss/Valine] 并不想要填写网址怎么设置 (#13)不能定制简直太残暴了，竟然还说什么可以fork自己改，怎么不说“你可以自己去写一个评论系统，想怎样就怎样”，(:3 」∠)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xCss/Valine","title":"xCss/Valine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xCss/Valine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@insekkei in #13: 不能定制简直太残暴了，竟然还说什么可以fork自己改，怎么不说“你可以自己去写一个评论系统，想怎样就怎样”，_(:3 」∠)_ "}],"action":{"name":"View Issue","url":"https://github.com/xCss/Valine/issues/13#issuecomment-340192545"}}}

**Comment by xCss** [comment]
@vxhly 已更新，如有需要，请更新到最新版本。

**Comment by vxhly** [comment]
嗯，过几天得空了，再更新


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xCss/Valine","title":"xCss/Valine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xCss/Valine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xCss in #13: @vxhly 已更新，如有需要，请更新到最新版本。"}],"action":{"name":"View Issue","url":"https://github.com/xCss/Valine/issues/13#issuecomment-340254760"}}}
