### ISSUE TITLE
在vuepress中使用 跳转页面评论数据不更新

### ISSUE THREAD

**Issue by songStar0904** [xCss/Valine#130]
在跳转不同页面的时候，valine发的每次请求参数都一样导致评论数据不更新。
有人用
```vue
watch: {
     '$route' (to, from) {
        if(to.path !==  from.path){
          this.$router.go(0)
        }else{
           // nothing
       }
     }
   }, 
```
问题解决，但是每次跳转页面网页刷新导致体验很不友好。请问还有其他解决办法吗

**Comment by xiaolimaotx** [comment]
怎么弄，我的是每次网页一刷新评论就没有了

**Comment by xiaolimaotx** [comment]
> 在跳转不同页面的时候，valine发的每次请求参数都一样导致评论数据不更新。
> 有人用
> 
> ```
> watch: {
>      '$route' (to, from) {
>         if(to.path !==  from.path){
>           this.$router.go(0)
>         }else{
>            // nothing
>        }
>      }
>    }, 
> ```
> 
> 问题解决，但是每次跳转页面网页刷新导致体验很不友好。请问还有其他解决办法吗

怎么弄啊

**Comment by songStar0904** [comment]
> > 在跳转不同页面的时候，valine发的每次请求参数都一样导致评论数据不更新。
> > 有人用
> > ```
> > watch: {
> >      '$route' (to, from) {
> >         if(to.path !==  from.path){
> >           this.$router.go(0)
> >         }else{
> >            // nothing
> >        }
> >      }
> >    }, 
> > ```
> > 问题解决，但是每次跳转页面网页刷新导致体验很不友好。请问还有其他解决办法吗
> 
> 怎么弄啊

就是我上面那样做的。。。在开发模式下会刷新网页（有点不爽）。但是在线上模式感觉不到刷新。。。

**Comment by ChangMM** [comment]
```
valine = new Valine({
      appId: '****',
      appKey: *****',
      el: '#comment',
      placeholder: '评论在此',
      avatar: 'monsterid',
      path: window.location.pathname,
      recordIP: true,
      visitor: true
    })
```
router 变化的时候重新渲染下上面的对象就好了，同时记得 path 要传一个自己设定的值，不然也是不行的。

**Comment by wb121017405** [comment]
https://github.com/dongyuanxin/vuepress-plugin-comment/issues/4#issuecomment-555381607

**Comment by AJ-X** [comment]
> 怎么弄，我的是每次网页一刷新评论就没有了

请问解决了吗，我也是出现这样的情况
