### ISSUE TITLE
在本机的chrome浏览器上可以正常评论，但在别的任何地方就只能看到评论而不能评论

### ISSUE THREAD

**Issue by oukohou** [xCss/Valine#132]
### 1. Valine config:
```text
<script src="https://cdnjs.loli.net/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
    <script src="//unpkg.com/valine/dist/Valine.min.js"></script>

<p><br /><br/><br/><br/><br/><br><hr /><br/>不写个评论嘛：</p>
<div id="valine_comment" class="fb_comments_container"></div>
<script>
    var notify = '{{site.valine.notify}}' === true;
    var verify = '{{site.valine.verify}}.>' === true;
    var visitor = '{{site.valine.visitor}}.>' === true;

    new Valine({
        av: AV,
        el: '#valine_comment',
        notify: notify,
        verify: verify,
        // smiles_url: '/smiles',
        visitor: visitor,
        app_id: '{{site.valine.app_id}}',
        app_key: '{{site.valine.app_key}}',
        placeholder: '{{site.valine.placeholder}}',
        avatar: '{{site.valine.avatar}}'
    });
</script>
```

### 2. 博客网址：

- 主页：
[https://www.oukohou.wang/](https://www.oukohou.wang/)

- 有vlaine插件的一篇博文：
[爱因斯坦求和约定](https://www.oukohou.wang/2018/10/25/Einstein-summation-convention/)

### 3. leanCloud域名白名单设置：
```bash
https://www.oukohou.wang/
https://oukohou.github.io/
https://www.oukohou.wang
https://oukohou.github.io
```

### 4. 错误：
- 本机chrome显示：
![image](https://user-images.githubusercontent.com/16237619/49134817-d81b3e80-f31f-11e8-9b93-6a4cd870285e.png)

- 本机firefox显示：
![image](https://user-images.githubusercontent.com/16237619/49134854-fed97500-f31f-11e8-85dc-9dd55d47f54a.png)

- 手机浏览器显示：
![image](https://user-images.githubusercontent.com/16237619/49134941-44963d80-f320-11e8-9243-1a9c0c31dc3e.png)

- 本机上的虚拟机chrome显示：
![image](https://user-images.githubusercontent.com/16237619/49134991-64c5fc80-f320-11e8-9018-18e163b20c77.png)

- 关于错误信息：
```bash
Code 403: 访问被api域名白名单拒绝，请检查你的安全域名设置.
```

当然这个提示信息足够明确了，但是依据我的理解，域名白名单里我应该已经正确设置了吧？
或许哪里有错误？前端无能，请大佬释疑。

谢谢。致礼！

**Comment by oukohou** [comment]
update 2018-11-28 15:27:51：
其他客户端上并不能看到评论，只能看到错误提示。
但是可以强制点击回复，然后能够显示评论，但刷新之后就依然只显示上面的错误信息：
```bash
Code 403: 访问被api域名白名单拒绝，请检查你的安全域名设置.
```
this is awkward...

**Comment by xCss** [comment]
[![安全域名了解下](https://ws1.sinaimg.cn/large/006qRazegy1fkxqmddfh1j30qd0go40h.jpg)](https://ws1.sinaimg.cn/large/006qRazegy1fkxqmddfh1j30qd0go40h.jpg)

https://valine.js.org/quickstart.html#%E5%AE%89%E5%85%A8%E5%9F%9F%E5%90%8D

**Comment by oukohou** [comment]
@xCss  额不好意思，这个据我的理解，我应该是设置对了~~具体如下：
```text
https://www.oukohou.wang/
https://oukohou.github.io/
https://www.oukohou.wang
https://oukohou.github.io
http://www.oukohou.wang/
http://oukohou.github.io/
http://www.oukohou.wang
http://oukohou.github.io
```
我的博客网址是[https://www.oukohou.wang/](https://www.oukohou.wang/),应该足够覆盖了吧？

**Comment by xCss** [comment]
你试着把最后面的`斜杠`去掉，然后去重试试。

**Comment by oukohou** [comment]
@xCss emm……看到贴的一共8行域名，第3/4/7/8行都是把最后的**斜杠**去掉了的～～
