### ISSUE TITLE
评论在Google Chrome浏览器无法显示评论的内容

### ISSUE THREAD

**Issue by mstao** [xCss/Valine#135]
The versions of Valine： v1.3.4
browser / OS： Google Chrome   71.0.3578.80（正式版本）（64 位）/ Win10

Edge 浏览器显示正常，但在Google Chrome无法显示评论的内容，链接： https://mingshan.fun/2018/10/07/%E6%88%91%E8%AF%BB/

**Comment by xCss** [comment]
chrome正常显示~

[![_20181205214551](https://user-images.githubusercontent.com/10877162/49517440-29ef3600-f8d7-11e8-8812-96c68d993478.png)](https://user-images.githubusercontent.com/10877162/49517440-29ef3600-f8d7-11e8-8812-96c68d993478.png)

**Comment by mstao** [comment]
我用 chrome 的f12 看了下，数据都有， 但是显示不出来

![snipaste_2018-12-06_09-12-50](https://user-images.githubusercontent.com/23411433/49554428-268b9700-f937-11e8-97c0-f51b28b36060.png)

麻烦帮忙看看是咋回事，谢谢~

**Comment by xCss** [comment]
升级浏览器试下？

**Comment by mstao** [comment]
我仔细看了下css样式， 发现评论右侧的内容 class为 `vh`,  `vh`的css为：

```
.vh {
    visibility: hidden !important;
}
```

如下图所示：

![snipaste_2018-12-06_09-58-34](https://user-images.githubusercontent.com/23411433/49556114-6c4b5e00-f93d-11e8-87f1-b9b4fbea73be.png)

是不是这个原因导致的？

**Comment by xCss** [comment]
这个样式属性设置(`visibility: hidden !important;`)在`Valine`中是不存在的

请确认你的浏览器插件是否有屏蔽`.vh`

**Comment by mstao** [comment]
我试着把我chrome的插件卸载了， 发现这个class 是 `https://github.com/FrankFan/gitlab-tree` 这个插件加的，把这个插件卸载后现在已经可以显示了。。

问题解决了，多谢~
