### ISSUE TITLE
如何在jekyll博客的index.html页面显示所有博客的阅读量统计结果？

### ISSUE THREAD

**Issue by oukohou** [xCss/Valine#136]
问题：

**首先声明一下我前端无能～～**
---
然后是参照你的[博客主页](https://ioliu.cn/)，也想把index页面每篇博客的阅读量都统计显示在index页面，然后努力试着理解[我的博客的index.html源码](https://github.com/oukohou/oukohou.github.io/blob/master/index.html)并改写，最终实现的情况如图：
![image](https://user-images.githubusercontent.com/16237619/49570685-468c7c00-f972-11e8-91ef-0d8fb6581891.png)

---
只显示了**阅读量**三个字，不像每一篇博文里还会显示数字结果：
![image](https://user-images.githubusercontent.com/16237619/49570731-6ae85880-f972-11e8-8471-a87af039f27b.png)

是不是index.html里还需要加些别的东西，不只是单单引入下面这几行：
```html
<!-- 显示每篇博客阅读量, id 将作为查询条件 -->
 <span id={{post.url}} class="leancloud-visitors" data-flag-title={{post.title}}>
    <span class="post-meta-divider">|</span>
    <span class="post-meta-item-text">阅读量 </span>
    <span class="leancloud-visitors-count"></span>
</span>
```

以及，应该改成什么样子？
致礼！
---
- 参考：
　　我的博客：[oukohou](https://www.oukohou.wang/)
　　我的博客的repo：[https://github.com/oukohou/oukohou.github.io](https://github.com/oukohou/oukohou.github.io)
- The steps to reproduce.
我的博客的index.html页面源码（很短，加上无效行数才58行）：
[https://github.com/oukohou/oukohou.github.io/blob/master/index.html](https://github.com/oukohou/oukohou.github.io/blob/master/index.html)

- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
not sure what and how?
- Which versions of Valine, and which browser / OS are affected by this issue?
![image](https://user-images.githubusercontent.com/16237619/49570517-cebe5180-f971-11e8-9a1a-cfabe65b0a69.png)

**Comment by ccslience** [comment]
@xCss 谢谢，已解决。  
致礼。

**Comment by oukohou** [comment]
@xCss 谢谢，已解决。
致礼！

**Comment by oukohou** [comment]
solved，now close it.

**Comment by oukohou** [comment]
我的博客主页：[oukohou](https://www.oukohou.wang/)，然后发现首页的阅读统计量全部为0了，而点进去每个页面是可以正确统计阅读量的，请问是什么原因？谢谢～～

**Comment by xCss** [comment]
@oukohou 首页只需要一个`new Valine`，而你每条数据都new了一个。。。

![image](https://user-images.githubusercontent.com/10877162/63747161-0a6ec200-c8d9-11e9-87b3-5a380771a867.png)

**Comment by oukohou** [comment]
@xCss 已经修改为只有一个`new Valine`了但是依然全部为0。。
![image](https://user-images.githubusercontent.com/16237619/63757719-2b411280-c8ed-11e9-9583-aeda0327b6fd.png)

**Comment by xCss** [comment]
@oukohou OK，感谢反馈，已复现BUG，将在下个版本修复。

**Comment by xCss** [comment]
@oukohou 已修复，参考 [v1.3.10](https://github.com/xCss/Valine/releases/tag/v1.3.10)
