### ISSUE TITLE
请问如何在带有 pjax 的页面下使用

### ISSUE THREAD

**Issue by memset0** [xCss/Valine#138]
我使用和一个带有 pjax 的博客主题，并使用了 Valine 作为评论系统。我发现在从一个页面切换到另一个页面时， Valine 不会显示。具体表现类似于 #109 （但那个 issue ）没人回复，我使用了 #66 中的方式后，切换页面之后提示 `Code : Not initialized` ，求教如何解决。

目前我的代码是：

```html
{% if theme.valine.appid and theme.valine.appkey %}
<!-- valine Comments -->
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js" data-no-instant></script>
<script src='//unpkg.com/valine/dist/Valine.min.js' data-no-instant></script>
<script type="text/javascript">
    var valine_option = {
        el: '#vcomments',
        notify: {{ theme.valine.notify }},
        verify: {{ theme.valine.verify }},
        app_id: "{{ theme.valine.appid }}",
        app_key: "{{ theme.valine.appkey }}",
        placeholder: "{{ theme.valine.placeholder }}",
        avatar: '{{ theme.valine.avatar }}'
    };
    var valine = new Valine(valine_option);
    $(document).on({
        'pjax:end': function () {
            valine.init(valine_option);
        }
    });
</script>
{% endif %}
```

问题页面可在 [memset0.cn](//memset0.cn) 的任意两个带评论的页面切换。

求教如何解决 @xCss ，谢谢。

**Comment by xCss** [comment]
抱歉，目前来说，Valine对Pjax并不兼容。。。

还在寻找解决办法。

**Comment by memset0** [comment]
谢谢回复。

现在我发现如果第一个页面没有 Valine ，那么在第二个页面可以正常加载 Valine .

是否有什么方法删掉已经 init 过的 Valine 然后再重新 init 一个呢？

**Comment by xCss** [comment]
@memset0 Valine本身是可以重新init的，但是leancloud的av对象不支持，不管怎么搞都是操作同一个av对象。故。。。

**Comment by xCss** [comment]
@memset0 
新的解决方案：
1. 在`<head>`中加载`AV文件`和`Valine文件`
2. 正确填写`Valine配置`

``` html
<!doctype html>
<html>
<head>
<!-- 你的代码（请确保已加载jQuery） -->

<!-- 在head中加载AV文件和Valine文件 -->
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src="//unpkg.com/valine/dist/Valine.min.js"></script>
</head>
<body>
<div  id="pjax-box">
    <!-- 你的文章内容 -->

    <!-- Comments -->
    <div class="comment"></div>
      <script>
          new Valine({
              el: '.comment' ,
              notify:false, 
              verify:false, 
              app_id: '{{theme.leancloud.app_id}}',
              app_key: '{{theme.leancloud.app_key}}',
              placeholder: 'Just Go Go',
              path:window.location.pathname // **请确保必须写该属性
          });
      </script>
</div>
<script>
    // **请确认你的jQuery库已加载
    $(document).pjax('a', '#pjax-box', {fragment:'#pjax-box', timeout:8000}).on('pjax:complete', function() {
        // pjax 加载完成要做的操作
    }).on('pjax:start', function() { 
      // pjax 加载开始需要做的操作 比如 NProgress.start();
    }).on('pjax:end',   function() {
      // pjax 加载结束需要做的操作 比如 NProgress.done();
      // 其他操作;
    });
</script>
</body>
</html>
```

**Comment by memset0** [comment]
@xCss 

谢谢！~

**Comment by jeasonlau** [comment]
> 新的解决方案：
> 
> 1. 在`<head>`中加载`AV文件`和`Valine文件`
> 2. 正确填写`Valine配置`
> 
> ```
> <!doctype html>
> <html>
> <head>
> 
> 
> 
> <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
> <script src="//unpkg.com/valine/dist/Valine.min.js"></script>
> </head>
> <body>
> <div  id="pjax-box">
>     
> 
>     
>     <div class="comment"></div>
>       <script>
>           new Valine({
>               el: '.comment' ,
>               notify: false, 
>               verify: false, 
>               appId: 'your appId',
>               appKey: 'your appKey',
>               placeholder: 'Just Go Go',
>               path: window.location.pathname // **请确保必须写该属性
>           });
>       </script>
> </div>
> <script>
>     // **请确认你的jQuery库已加载
>     $(document).pjax('a', '#pjax-box', {fragment:'#pjax-box', timeout:8000}).on('pjax:complete', function() {
>         // pjax 加载完成要做的操作
>     }).on('pjax:start', function() { 
>       // pjax 加载开始需要做的操作 比如 NProgress.start();
>     }).on('pjax:end',   function() {
>       // pjax 加载结束需要做的操作 比如 NProgress.done();
>       // 其他操作;
>     });
> </script>
> </body>
> </html>
> ```
@xCss 您好，我使用您的方法成功使`valine`支持了`pjax`，同时我在[这篇文档](https://valine.js.org/visitor.html)了解到可以通过附加`visitor: true`来支持文章阅读量统计，但我发现这样配置之后虽然`valine`依旧正常，但文章阅读量不会随着`pjax`而刷新，请问有什么办法可以修复吗？

**Comment by inkss** [comment]
pjax 情况下，此两处存在重复的事件监听 `paste` `keydown` ，这边可不可以改成先 off 再 on
![image](https://user-images.githubusercontent.com/31947043/87499755-945c8080-c68d-11ea-8ee2-a593f3cbe6c5.png)

![image](https://user-images.githubusercontent.com/31947043/87499769-9cb4bb80-c68d-11ea-98c8-ea3b38a4c642.png)

**Comment by cjqts** [comment]
![image](https://github.com/user-attachments/assets/5db0bd77-0b18-4aa2-aac4-e146def9ede3)
加上 data-pjax='' 就好了

**Comment by memset0** [comment]
> ![image](https://private-user-images.githubusercontent.com/175526247/348837120-5db0bd77-0b18-4aa2-aac4-e146def9ede3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDEwMTAsIm5iZiI6MTcyMTIwMDcxMCwicGF0aCI6Ii8xNzU1MjYyNDcvMzQ4ODM3MTIwLTVkYjBiZDc3LTBiMTgtNGFhMi1hYWM0LWUxNDZkZWY5ZWRlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QwNzE4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmRkZTI2MzI2ODFhNzA2MzBmNTljODc1MGNjMGIwMWJiYTFiMzJhNDg4YmVmNDNiNGY2YWExZjJlZjYwODVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X90doXSz724AOMWLJ44ztdFg6d3QwXuQAgrsJLQxdKY) 加上 data-pjax='' 就好了

这个 issue 已经是六年前的了。。。
