### ISSUE TITLE
部署Valine后，评论框下方出现Code 12错误

### ISSUE THREAD

**Issue by stgapr** [xCss/Valine#139]
https://lilis.coding.me/post/jargonfile/ 例如这篇文章下的评论框。
部署Valine后，评论框下方出现Code 12: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL。
![err12](https://user-images.githubusercontent.com/12985185/49698561-705ad280-fc00-11e8-9dce-738f84d80330.jpg)

本人博客主题为https://github.com/AlynxZhou/hexo-theme-aria , 自行通过修改<blogpath>\theme\aria\layout\comment.njk （已打包上传
[comment.zip](https://github.com/xCss/Valine/files/2660599/comment.zip) ）来添加valine支持，在leancloud中新建app，API key/secret已经填写到_config.yml中，并且已经把js文件和博客地址添加入leancloud的安全网址里。

该错误 在Edge浏览器中显示为Code 12: SyntaxError，在IE 11浏览器中显示为Code -1: 参数无效。

该故障是否和浏览器同源策略、js文件的存放位置有关？ 博客项目地址 https://git.coding.net/lilis/lilis.coding.me.git （可以fork，重现bug。）

请问有可能是什么原因？谢谢！

**Comment by xCss** [comment]
你网页中的源码：
``` js

<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>

  <script src="//unpkg.com/valine@latest/dist/Valine.min.js"></script>
  <div id="comment" class="vcomment"></div>
  <script>
  var notify = '<%= theme.comment.valine.notify %>' == true ? true : false;
  var verify = '<%= theme.comment.valine.verify %>' == true ? true : false;
  var GUEST_INFO = ['nick','mail','link'];
  var guest_info = '<%= theme.comment.valine.guest_info %>'.split(',').filter(function(item){
  return GUEST_INFO.indexOf(item) > -1
  });
  guest_info = guest_info.length == 0 ? GUEST_INFO :guest_info;
  window.valine = new Valine({
      el: '.vcomment',
      notify: notify,
      verify: verify,
      appId: "<%= theme.comment.valine.appid %>",
      appKey: "<%= theme.comment.valine.appkey %>",
      avatar:'<%= theme.comment.valine.avatar %>',
      guest_info: guest_info,
      pageSize: '<%= theme.comment.valine.pageSize %>'
  });
  </script>


```

#### 找到`问题`所在了吗？

**Comment by stgapr** [comment]
不好意思，看了半天还是没想出来，请明示……

**Comment by xCss** [comment]
@stgapr 好吧，你打开你的自己网页( https://lilis.coding.me/post/jargonfile/ )，然后右键查看你网页源码，找到初始化`Valine`的位置，然后就能看到我上面列出来的代码了。

然后你再 打开我的博客( https://ioliu.cn/2017/add-valine-comments-to-your-blog/ )，右键源码，查看一下有什么不一样。

**Comment by stgapr** [comment]
感谢指点，发现是NJK模板语法的问题，把comment.njk里所有写成 <%= theme.comment.valine.xx %> 的地方改成{{ theme.comment.valine.xx  }}后问题解决。谢谢！
