### ISSUE TITLE
针对邮件提醒的一些意见与建议

### ISSUE THREAD

**Issue by vxhly** [xCss/Valine#14]
版本信息： hexo-theme-next | Merged v1.1.7-rc3

因为邮箱提醒还在内测中，并没有将此功能加入我的博客系统，但自己用了一下之后，有几点体验问题想跟作者提一下醒。
在邮件提醒中就是 leancloud 那边的邮件模板设置中能够提供几个变量来获取相应的内容。
1. 获取文章的 title。
2. 点击马上查看的 URL ，是指向 url#rid
（PS：在我看来，评论人接受到邮件是希望能够直观地看到哪篇文章的哪条评论被回复了）

**Comment by xCss** [comment]
抱歉，目前Leancloud官方只提供`用户昵称`和`邮箱`传递，其他不提供。

所以，暂时不能满足你的请求~

**Comment by vxhly** [comment]
这有点尴尬，邮件提醒这功能还是蛮好的，想着加入我的博客呢，可惜不能满足我的需求发自我的iPhone------------------ 原始邮件 ------------------发件人: Nine  <notifications@github.com>发送时间: 2017年10月28日 21:59收件人: xCss/Valine <Valine@noreply.github.com>抄送: 星火燎原 <pengchengou@gmail.com>, Author <author@noreply.github.com>主题: 回复：[xCss/Valine] 针对邮件提醒的一些意见与建议 (#14)抱歉，目前Leancloud官方只提供用户昵称和邮箱传递，其他不提供。
所以，暂时不能满足你的请求~

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xCss/Valine","title":"xCss/Valine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xCss/Valine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xCss in #14: 抱歉，目前Leancloud官方只提供`用户昵称`和`邮箱`传递，其他不提供。\r\n\r\n所以，暂时不能满足你的请求~"}],"action":{"name":"View Issue","url":"https://github.com/xCss/Valine/issues/14#issuecomment-340192832"}}}

**Comment by profoundsoul** [comment]
我自己fork之后加上了title和commentCallback功能，邮件的话用的是Valine-Admin，可以定制化化一些回复邮件通知和定时任务。
