### ISSUE TITLE
为啥 dist 的 min 会比 src 更新，src 缺少 i18n 等的实现

### ISSUE THREAD

**Issue by virusdefender** [xCss/Valine#140]
我原意是想通过 i18n 来自定义几个文字，就不需要修改源码了。

看了下源码，没有找到相关的东西啊。

然后发现 dist min 中有，啥 dist 的 min 会比 src 更新？

**Comment by byte0xff** [comment]
+1，看 commit 发现作者最近（在 569c5ea95daa12624200b143c3ae4620305c5711 之后）一直只提交 dist 文件夹，src 没动过 orz

**Comment by yeungtg** [comment]
+1

**Comment by lizheming** [comment]
+1
