### ISSUE TITLE
英文界面支持

### ISSUE THREAD

**Issue by SaferSky** [xCss/Valine#141]
我在文档中看到有多语言支持，但是当我选择en的时候界面的语言依然是中文的。
请问我是哪里设置不对吗？

**Comment by xCss** [comment]
怎么设置的，请发配置，或者预览地址

**Comment by xCss** [comment]
抱歉，我在你的博客仓库没看见带有Valine配置信息的`_config.yml`文件。

**Comment by SaferSky** [comment]
这个是[配置文件](https://github.com/SaferSky/safersky.github.io/blob/493025d089a9a612c092d63dee34fb097105c50a/source/_data/melody.yml#L226)

**Comment by xCss** [comment]
你的主题文件没有上传。上传下，我看看
