### ISSUE TITLE
Used in Jekyll

### ISSUE THREAD

**Issue by kitian616** [xCss/Valine#142]
For now in [Used in Hexo](https://valine.js.org/en/hexo.html) shows a number of hexo theme built-in valine comment system.

I think it is time to have a list for Jekyll Theme.

[TeXt](https://github.com/kitian616/jekyll-TeXt-theme), a Jekyll Theme, [has supported the valine comment system](https://tianqi.name/jekyll-TeXt-theme/docs/en/configuration#valine).

**Comment by xCss** [comment]
Jekyll Theme List Page is Ready, Please commit your PR.
