### ISSUE TITLE
请问如何设置昵称和邮箱为必填项？

### ISSUE THREAD

**Issue by sanshuifeibing** [xCss/Valine#143]
有些游客不填邮箱的咨询不知道回复还是不回复好，希望能有个必填限制，不知如何设置，请指教。

**Comment by xCss** [comment]
由于Valine本身属于匿名评论系统，所以抱歉，并不能设置必填。

**Comment by sanshuifeibing** [comment]
> 由于Valine本身属于匿名评论系统，所以抱歉，并不能设置必填。

那是否可以设置提醒呢？（我看有的人的Valine有提醒的，但是测试了一下我的没有，该如何设置呢？）

**Comment by xCss** [comment]
参考 @zhaojun1998 https://github.com/zhaojun1998/Valine-Admin

**Comment by sanshuifeibing** [comment]
> 参考 @zhaojun1998 https://github.com/zhaojun1998/Valine-Admin

不是邮件回复提醒，是如果没有填邮箱有个对话框提醒，这个怎么设置呢？ 如图：

![20181224164017](https://user-images.githubusercontent.com/43435652/50394794-ba17f100-079a-11e9-8ad9-828c4779238f.png)

**Comment by sanshuifeibing** [comment]
> @sanshuifeibing 这是老版本的吧，新版本中已经不判断格式了。

好的吧，虽然Valin不能满足很多人的要求，但确实是很棒的东西，作者继续加油，持续关注。

**Comment by imaegoo** [comment]
总是有人不输邮箱就评论，可能就是没注意到，博客底下一堆匿名用户…

**Comment by jason-663** [comment]
> 总是有人不输邮箱就评论，可能就是没注意，博客底下操作匿名用户……

主要是怕会产生很多垃圾评论，既影响整篇文章的观看体验，至少得垃圾评论得删掉，这样又费精力，把一下项设为必填，多多少少能过滤掉一些垃圾评论

**Comment by liuzepeng996** [comment]
地方
