### ISSUE TITLE
链接开头的的评论被拼接成一个无效的超链接

### ISSUE THREAD

**Issue by redstoneleo** [xCss/Valine#145]
https://github.com/DesertsP/Valine-Admin/issues/21
这个问题是不是本项目的原因 ？

**Comment by xCss** [comment]
@redstoneleo MarkDown链接了解下。 链接结尾请加`空格`，而不是直接写内容。

**Comment by redstoneleo** [comment]
本评论系统实际上最终要面向的绝大多数人依然是普通小白，而他们中很多都是不知道MarkDown的这个特性的，以至于不可避免地会产生问题中所描述的情形，为了避免这个问题，我建议：在评论提交的时候，如果链接后面没有空格，那么就利用程式自动加一个空格。
希望大大考虑这个建议，谢谢！
