### ISSUE TITLE
查看了 hexo 的 valine.swing 后提的建议

### ISSUE THREAD

**Issue by vxhly** [xCss/Valine#15]
```swing
{% if page.comments and theme.valine.enable and theme.valine.appid and theme.valine.appkey %}

  <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
  <script src="//cdn.jsdelivr.net/gh/xcss/valine@v1.1.7-rc3/dist/Valine.min.js"></script>
  <script type="text/javascript">
    new Valine({
        av: AV,
        el: '#comments' ,
        verify: {{ theme.valine.verify }},
        notify: {{ theme.valine.notify }},
        app_id: '{{ theme.valine.appid }}',
        app_key: '{{ theme.valine.appkey }}',
        placeholder: '{{ theme.valine.placeholder }}'
    });
  </script>
{% endif %}

```

这边的配置项少了几个，比如 `avatar`, `path`

**Comment by xCss** [comment]
@vxhly 你是说的`next`主题吧？
因为头像配置选项`avatar`字段是[v1.1.7正式版](https://github.com/xCss/Valine/releases/tag/v1.1.7)才加进去的。
当时[v1.1.7-rc3](https://github.com/xCss/Valine/releases/tag/v1.1.7-rc3)版本发布的时候并没有头像配置选项，所以在提交pr的时候，就没加入这个配置项。

而在hexo中，`path`选项默认为`window.location.pathname`为最优选项，所以也就没有加可选项了。

**Comment by vxhly** [comment]
好的，知道了发自我的iPhone------------------ 原始邮件 ------------------发件人: Nine  <notifications@github.com>发送时间: 2017年10月28日 22:09收件人: xCss/Valine <Valine@noreply.github.com>抄送: 星火燎原 <pengchengou@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[xCss/Valine] 查看了 hexo 的 valine.swing 后提的建议 (#15)@vxhly 你是说的next主题吧？
因为头像配置选项avatar字段是v1.1.7正式版才加进去的。
当时v1.1.7-rc3版本发布的时候并没有头像配置选项，所以在提交pr的时候，就没加入这个配置项。
而在hexo中，path选项默认为window.location.pathname为最优选项，所以也就没有加可选项了。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xCss/Valine","title":"xCss/Valine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xCss/Valine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xCss in #15: @vxhly 你是说的`next`主题吧？\r\n因为头像配置选项`avatar`字段是[v1.1.7正式版](https://github.com/xCss/Valine/releases/tag/v1.1.7)才加进去的。\r\n当时[v1.1.7-rc3](https://github.com/xCss/Valine/releases/tag/v1.1.7-rc3)版本发布的时候并没有头像配置选项，所以在提交pr的时候，就没加入这个配置项。\r\n\r\n而在hexo中，`path`选项默认为`window.location.pathname`为最优选项，所以也就没有加可选项了。"}],"action":{"name":"View Issue","url":"https://github.com/xCss/Valine/issues/15#issuecomment-340194110"}}}
