### ISSUE TITLE
能否加入自定义emoji功能

### ISSUE THREAD

**Issue by ghost** [xCss/Valine#150]
如题

**Comment by a1401358759** [comment]
+1

**Comment by Boyuan26832** [comment]
[有位老哥](https://deserts.io/diy-a-comment-system/#5ce76bf543e78c0067e414fc)通过某种方法成功了，但是我在 hexo 上通过修改 valine.ejs 配置始终不成功，

**Comment by a1401358759** [comment]
@Boyuan26832  我是直接用的他的valine  配置了一下 可以用了 但是我想用楼中楼的模式 https://yangsihan.com

**Comment by Boyuan26832** [comment]
> https://deserts.io/diy-a-comment-system/#5ce76bf543e78c0067e414fc

可能是 Hexo 的配置有些不同吧，还没找到解决方法

**Comment by atongmucp** [comment]
源码下载 emojis下面的 light.json 修改完了，npm run build 就 ok

**Comment by Skrtono** [comment]
+1

**Comment by xCss** [comment]
新版[v1.4.5](https://valine.js.org)已发布，支持了自定义表情，感谢建议~
