### ISSUE TITLE
使用过程中的几点疑问

### ISSUE THREAD

**Issue by practicemp** [xCss/Valine#151]
* 第一点：是否能自定义评论者信息的必填项？
比如我想评论者必须填写 昵称 和 邮箱 这两项。

* 第二点：能否自定义头像的形状？
目前来看头像都被设置为圆形，能否自定义为原来的方形，或圆角方形？

* 第三点：文档中的默认头像 mm 和 mp 貌似是同样的图像

**Comment by practicemp** [comment]
* 第四点：预览按钮为什么没有中文化？

**Comment by xCss** [comment]
1. `Valine`作为`匿名评论系统`，`强制必填项`和其本身存在的意义冲突
2. 可以自行添加style，来达到`自定义头像形状`的目的
3. 文档中目前只存在`mp`选项，如果你还看到`mm`选项，那么可能是我的疏忽
4. 关于`中文化`问题，请期待后期版本更新
5. `data-flag-title`本身就是第一次初始化的时候会用到，存到数据库中只是作为一个冗余字段存在，没必要关注，可能需要关注的字段就只有`time`和`url`

**Comment by practicemp** [comment]
1. 在介绍页面看到的 `无后端评论系统` 代表的就是 `匿名评论系统` 的意思么？
2. 好的。
3. 在 `快速开始` 页面的 `配置` 小节，示例代码中写有 `avatar:'mm', `
4. 好的
5. 我的意思是：在这两种情况下，`data-flag-title` 都初始化为 `string` 类型可能会更好一些。
