### ISSUE TITLE
TypeError: Cannot read property 'init' of undefined Valine:1.1.4

### ISSUE THREAD

**Issue by runingBody** [xCss/Valine#154]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by JadeVane** [comment]
same here，同样的问题

**Comment by xCss** [comment]
请更新版本。
