### ISSUE TITLE
安全问题（被刷了 1000 多条评论）

### ISSUE THREAD

**Issue by reuixiy** [xCss/Valine#156]
![selection_002](https://user-images.githubusercontent.com/28993043/52894998-88e1fd00-31ee-11e9-8454-db90b561ab33.png)

如图，这老哥昨天用这 IP 刷了我 1271 条评论（

**Comment by memset0** [comment]
@reuixiy 能否请问下这个日志是在哪里查看的

**Comment by reuixiy** [comment]
![selection_002](https://user-images.githubusercontent.com/28993043/52907787-81c8f680-32a3-11e9-9f48-046a68f17e6b.png)
![selection_003](https://user-images.githubusercontent.com/28993043/52907791-99a07a80-32a3-11e9-9182-16eb37f58046.png)
@memset0 如图（握手.webp

**Comment by memset0** [comment]
@reuixiy QAQ 我这里不知道为什么没有 ...
![](https://i.loli.net/2019/02/17/5c6937f1d7545.png)

**Comment by sxyugao** [comment]
我最近也被这么刷过评论，感觉好像就是有个人专门针对valine的评论的。。

**Comment by DesertsP** [comment]
刷Valine评论是一件极容易的事情，获取整站评论中的邮箱也很容易。

- 如何避免？
- 你可以试试到我的博客刷一下垃圾评论，或者尝试盗取取评论人的邮箱和隐私信息

**Comment by sxyugao** [comment]
> 刷Valine评论是一件极容易的事情，获取整站评论中的邮箱也很容易。
> 
> * 如何避免？
> * 你可以试试到我的博客刷一下垃圾评论，或者尝试盗取取评论人的邮箱和隐私信息

如果有人直接有你应用的App_key，App_id呢

**Comment by DesertsP** [comment]
> > 刷Valine评论是一件极容易的事情，获取整站评论中的邮箱也很容易。
> > 
> > * 如何避免？
> > * 你可以试试到我的博客刷一下垃圾评论，或者尝试盗取取评论人的邮箱和隐私信息
> 
> 如果有人直接有你应用的App_key，App_id呢

无妨

**Comment by TRHX** [comment]
> ![selection_002](https://user-images.githubusercontent.com/28993043/52894998-88e1fd00-31ee-11e9-8454-db90b561ab33.png)
> 
> 如图，这老哥昨天用这IP刷了我1271条评论（

哥们儿，一千多条不算什么，我被刷了两万九千多条，要疯了啊啊啊啊啊啊
![](https://i.loli.net/2019/03/29/5c9dcebd2c789.png)

**Comment by iLay1678** [comment]
刚刚也被刷了一万多评论
