### ISSUE TITLE
不能取消回复

### ISSUE THREAD

**Issue by Tarocch1** [xCss/Valine#157]
似乎是没有这个功能。。。

**Comment by xCss** [comment]
抱歉，由于是无后端评论系统，没有`账户系统`，所有评论数据都是博主在管理，你可以联系博主删掉你的评论

**Comment by Tarocch1** [comment]
我的意思是在发表回复之前，点击了回复按钮，但是又不想回复了，这个时候不能取消

**Comment by xCss** [comment]
刷新下就好了
