### ISSUE TITLE
pjax 兼容问题

### ISSUE THREAD

**Issue by 96486d9b** [xCss/Valine#158]
您好，暂时遇到了pjax兼容的问题。
查看了几个类似的issue，有这样的疑问。
因为不清楚valine是具体怎样实现的，对于 #138 中提到的av不能重新初始化问题不太理解。
我觉得av初始化之后，可以设置一个添加评论的函数，一个参数是url，一个参数是对应的评论。然后进入不同的页面也拉取对应当前url的评论这样~

**Comment by DesertsP** [comment]
这里给出了PJAX兼容问题的解决，可以参考修改：https://deserts.io/diy-a-comment-system/

**Comment by 96486d9b** [comment]
我尝试了一下这个方法，没能成功，还是会出现在一个帖子回复了，另一个帖子也会显示该回复这个问题

**Comment by DesertsP** [comment]
因为获取到的路径不对。你可以试试我的Valine.min.js或者参考我开源的代码去修改你的JS文件

**Comment by 96486d9b** [comment]
您好，尝试了您的valine之后的确可以，期待后续能合并到valine当中。

**Comment by xCss** [comment]
@96486d9b 
新的解决方案：
1. 在`<head>`中加载`AV文件`和`Valine文件`
2. 正确填写`Valine配置`

``` html
<!doctype html>
<html>
<head>
<!-- 你的代码（请确保已加载jQuery） -->

<!-- 在head中加载AV文件和Valine文件 -->
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src="//unpkg.com/valine/dist/Valine.min.js"></script>
</head>
<body>
<div  id="pjax-box">
    <!-- 你的文章内容 -->

    <!-- Comments -->
    <div class="comment"></div>
      <script>
          new Valine({
              el: '.comment' ,
              notify: false, 
              verify: false, 
              appId: 'your appId',
              appKey: 'your appKey',
              placeholder: 'Just Go Go',
              path: window.location.pathname // **请确保必须写该属性
          });
      </script>
</div>
<script>
    // **请确认你的jQuery库已加载
    $(document).pjax('a', '#pjax-box', {fragment:'#pjax-box', timeout:8000}).on('pjax:complete', function() {
        // pjax 加载完成要做的操作
    }).on('pjax:start', function() { 
      // pjax 加载开始需要做的操作 比如 NProgress.start();
    }).on('pjax:end',   function() {
      // pjax 加载结束需要做的操作 比如 NProgress.done();
      // 其他操作;
    });
</script>
</body>
</html>
```

**Comment by 96486d9b** [comment]
> @96486d9b
> 新的解决方案：
> 
> 1. 在`<head>`中加载`AV文件`和`Valine文件`
> 2. 正确填写`Valine配置`
> 
> ```
> <!doctype html>
> <html>
> <head>
> 
> 
> 
> <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
> <script src="//unpkg.com/valine/dist/Valine.min.js"></script>
> </head>
> <body>
> <div  id="pjax-box">
>     
> 
>     
>     <div class="comment"></div>
>       <script>
>           new Valine({
>               el: '.comment' ,
>               notify: false, 
>               verify: false, 
>               appId: 'your appId',
>               appKey: 'your appKey',
>               placeholder: 'Just Go Go',
>               path: window.location.pathname // **请确保必须写该属性
>           });
>       </script>
> </div>
> <script>
>     // **请确认你的jQuery库已加载
>     $(document).pjax('a', '#pjax-box', {fragment:'#pjax-box', timeout:8000}).on('pjax:complete', function() {
>         // pjax 加载完成要做的操作
>     }).on('pjax:start', function() { 
>       // pjax 加载开始需要做的操作 比如 NProgress.start();
>     }).on('pjax:end',   function() {
>       // pjax 加载结束需要做的操作 比如 NProgress.done();
>       // 其他操作;
>     });
> </script>
> </body>
> </html>
> ```

按照这个配置，试了一下，切换页面之后没法显示出来欸，两种配置方式都试过了，直接new和init~

**Comment by xCss** [comment]
用这个文件试下，线上版本貌似还有点问题，我在修改，然后留下预览地址~~ 

小伙伴 @sxyugao 已经测试通过了~
 
[Valine.min.zip](https://github.com/xCss/Valine/files/3027978/Valine.min.zip)

**Comment by sxyugao** [comment]
喵喵喵？

**Comment by 96486d9b** [comment]
> 用这个文件试下，线上版本貌似还有点问题，我在修改，然后留下预览地址~~
> 
> 小伙伴 @sxyugao 已经测试通过了~
> 
> [Valine.min.zip](https://github.com/xCss/Valine/files/3027978/Valine.min.zip)

用这个提供的文件是可以的欸，谢谢~

**Comment by xCss** [comment]
> > 用这个文件试下，线上版本貌似还有点问题，我在修改，然后留下预览地址~~
> > 小伙伴 @sxyugao 已经测试通过了~
> > [Valine.min.zip](https://github.com/xCss/Valine/files/3027978/Valine.min.zip)
> 
> 用这个提供的文件是可以的欸，谢谢~

新版本`v1.3.6`已经更新，请耐心等待`CDN`生效，更新日志请查看 [Valine/releases](https://github.com/xCss/Valine/releases)
