### ISSUE TITLE
hexo使用valine刷新后评论会消失

### ISSUE THREAD

**Issue by yutouwd** [xCss/Valine#159]
hexo中next主题在配置好valine后可以正常加载，但是刷新后评论就会消失。在网上找到一个解决方法https://www.fayne.cn/2019/01/08/new-comment-valine/#comments 将```themes\next\layout\_third-party\comments\valine.swig```中的```appId```和```appKey```修改为```app_id```和```app_key```，刷新后评论仍然会消失。在leancloud中可以看到有API请求数。
hexo版本：3.8.0
next版本：5.1.4
valine版本：1.3.4
我的博客地址：https://yutouwd.github.io

**Comment by xCss** [comment]
Valine与next主题自带的`阅读量统计`冲突

**Comment by yutouwd** [comment]
谢谢～已经将next升级到7.0了，使用valine的评论和阅读量统计😉

**Comment by chhLab** [comment]
我也遇到了同样的问题，按照网上的教程发现装的next是老版本的，准备升级7.0版本看看
