### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by sxyugao** [xCss/Valine#160]
能否将ip信息作为可选配置项？

**Comment by xCss** [comment]
抱歉，在不引入第三方库的情况下，纯前端是无法获取用户ip的

**Comment by sxyugao** [comment]
https://ip.sb/api/ 这个行吗

**Comment by sxyugao** [comment]
主要是想配合valine-admin使用，但是又不会自动记录ip。。导致反垃圾评论没有效果。。

**Comment by xCss** [comment]
@sxyugao 请参考 https://github.com/DesertsP/Valine-Admin#%E5%9E%83%E5%9C%BE%E8%AF%84%E8%AE%BA%E6%A3%80%E6%B5%8B

**Comment by sxyugao** [comment]
请看https://github.com/DesertsP/Valine-Admin/issues/24

**Comment by xCss** [comment]
我尝试下，如果可行，将在下个版本中更新~

**Comment by sxyugao** [comment]
谢谢蛤
