### ISSUE TITLE
the size of the secondary blockquote

### ISSUE THREAD

**Issue by sli1989** [xCss/Valine#167]
is it the problem of the md render in valine?

![image](http://ws1.sinaimg.cn/large/645f3b4dgy1g0oe7oim5gj20oz06qdgq.jpg)

![image](http://wx1.sinaimg.cn/large/645f3b4dgy1g0oe7u1olwj20pf0buglq.jpg)

**Comment by xCss** [comment]
很抱歉现在才回复，在外面出差才回来。
你上面那张图是邮件回复吧？不太明白你所说的`Valine`的渲染问题。是没达到预期效果还是？

--- 
> ps. `Valine`  会将多余的`空行`干掉

**Comment by sli1989** [comment]
上图是单独返回评论的展示。这个图的预览也可以看出来，不知道是我博客render问题还是valine渲染问题。

![image](https://user-images.githubusercontent.com/8521181/55233233-e85a1080-5262-11e9-9c5e-6be7a90f51b3.png)

就是回复中加入引用，字体比非引用字体大。

**Comment by xCss** [comment]
明白。

我这边测试发现引用字体是正常值，没有变大的情况。 请检查你的网页的样式设置
