### ISSUE TITLE
Hexo 搭配 Valine 开启评论，弹出验证邮箱与url能取消吗

### ISSUE THREAD

**Issue by iplaypi** [xCss/Valine#168]
使用的 Valine 版本是 v1.3.4，Hexo 版本是 v3.8.0。

1、问题如图，总是弹出提示，怎么配置才能取消呢？
![image](https://user-images.githubusercontent.com/13584796/54767586-681b2600-4c38-11e9-9463-eefd7fcaa292.png)

2、称呼、邮箱、url 这3个属性能自由配置吗，我配置了 meta 但是没有生效，不知道为什么。
![image](https://user-images.githubusercontent.com/13584796/54767702-b4666600-4c38-11e9-872d-3663585ecacb.png)

感谢。

**Comment by xCss** [comment]
@iplaypi 
新版貌似早就取消了网址和邮件格式判断
`meta`属性是`1.2.x`的属性，我看你页面上还是`1.1.7-rc3`版本，请升级版本吧
