### ISSUE TITLE
第一条评论发送失败，重新提交没有反应

### ISSUE THREAD

**Issue by Ice-Hazymoon** [xCss/Valine#169]
## 环境：

(Chromium 72.0.3626.121) Windows10

## 问题

`Code 1: 应用初始化失败，请两分钟后重试。 [400 POST https://drfrdzb8.api.lncld.net/1.1/classes/Comment]`

重新按提交按钮的时候不会触发提交事件，必须刷新页面才行

如果数据库里没有数据的话，请求的时候会返回 `Class or object doesn't exists.` 错误，这个应该在文档里注明

## 其他

建议将 css 文件独立出来引用，要不然每次修改样式都很麻烦

**Comment by Ice-Hazymoon** [comment]
还有，回复的时候为什么会收到重置密码的邮件

![image](https://user-images.githubusercontent.com/25239977/54882745-356f6880-4e98-11e9-924b-0dca6c95d7d1.png)

![image](https://user-images.githubusercontent.com/25239977/54882751-461fde80-4e98-11e9-963a-14d42a35116a.png)

**Comment by xCss** [comment]
请留下`预览地址`~~~ 3Q

**Comment by Ice-Hazymoon** [comment]
抱歉，目前还没有预览地址

第一条评论提交失败提示：`Code 1: 应用初始化失败，请两分钟后重试。 [400 POST https://drfrdzb8.api.lncld.net/1.1/classes/Comment]` ，两分钟后再点击提交按钮没有任何反应

如果没有重现的话可能是我环境的问题，之后使用中没有遇到其他的问题
