### ISSUE TITLE
为啥用下载源码build和dist目录中的源码不一致

### ISSUE THREAD

**Issue by profoundsoul** [xCss/Valine#171]
下载源码之后，以1.3.4为例。
执行命令：npm run build 打包，结果打包出来的dist中
![image](https://user-images.githubusercontent.com/10645395/55325831-bb9f3680-54b8-11e9-90d8-eef87ee388a1.png)
Valine.min.js 只有48kb，而dist目录中有72KB，表情功能也是缺失的。

**Comment by xCss** [comment]
sorry，我的疏忽，忘了把最新的加进来~

**Comment by profoundsoul** [comment]
OK，历史的tag版本是无法处理了么？那我只能采用master版本了

**Comment by xCss** [comment]
是的，历史tag版本无法处理了，只能是最新的~ 😺
