### ISSUE TITLE
没有评论，报错TypeError: Cannot read property 'hide' of undefined

### ISSUE THREAD

**Issue by Core00077** [xCss/Valine#172]
在next主题下配置了valine，是最新版本v1.3.6

bug描述：无法显示评论
bug复现：100%
bug来源：[我的博客](https://coreja.com/%E7%9E%8E%E6%8A%98%E8%85%BE%E7%9A%84%E6%97%A5%E5%B8%B8/2019/03/lsyncd%E6%96%87%E4%BB%B6%E5%A2%9E%E9%87%8F%E5%90%8C%E6%AD%A5%E5%88%A9%E5%99%A8/)

欢迎大佬直接去我博客下debug哈哈。

额外信息：只开启了next主题下的valine，leanCloud_visitor**没有开启**，同时leanCloud的**控制台能看到counter**的信息，但**没有comments**。即阅读+1是ok的，bug应该是`valine.min.js`无法加载评论。

bug信息：
```
TypeError: Cannot read property 'hide' of undefined
    at r.ErrorHandler (Valine.min.js:12)
    at r.init (Valine.min.js:12)
    at new r (Valine.min.js:12)
    at new i (Valine.min.js:12)
    at (index):1891
```

**Comment by Core00077** [comment]
补充信息，试过1.3.5 1.3.4 1.2.5，均出现同样问题。怀疑是配置问题，但是目前没有什么头绪，求求各位大佬帮助。

**Comment by xCss** [comment]
收到，初步判断是你加了 `lang: zh-Hans`报错，请更改为`lang: zh-cn` 重试。

> Ps. 这应该是个Bug，感谢反馈。下个版本修复。

**Comment by Core00077** [comment]
！
感谢大佬！
回复好快！
解决了，的确是这个问题！ new Valine里是zh-cn，把next主题下的zh-Hans修改后就好了。

（话说当时是看next主题文档里写的，当时还纳闷zh-cn和zh-hans有啥区别来着）
再次感谢大佬！

**Comment by Fanlu91** [comment]
遇到了同样的issue 
1.3.6版本
我的配置是
```
language: zh-CN
```
将 “CN” 改为小写后解决，看来这里需要注意区分大小写

**Comment by CloneableX** [comment]
确实，需要注意大小写，zh-CN 大写情况下也会出现同样的问题

**Comment by chen-jx-private** [comment]
十分感谢，困惑了好几天的问题

**Comment by shen20010109** [comment]
![image](https://user-images.githubusercontent.com/26327724/77813672-5854de00-70e5-11ea-86ec-4def9db07bff.png)
这bug怎么改

**Comment by xCss** [comment]
> ![image](https://user-images.githubusercontent.com/26327724/77813672-5854de00-70e5-11ea-86ec-4def9db07bff.png)
> 这bug怎么改

更新下版本！~

**Comment by shen20010109** [comment]
> > ![image](https://user-images.githubusercontent.com/26327724/77813672-5854de00-70e5-11ea-86ec-4def9db07bff.png)
> > 这bug怎么改
> 
> 更新下版本！~

next的版本吗

**Comment by xCss** [comment]
> > > ![image](https://user-images.githubusercontent.com/26327724/77813672-5854de00-70e5-11ea-86ec-4def9db07bff.png)
> > > 这bug怎么改
> > 
> > 
> > 更新下版本！~
> 
> next的版本吗

Valine的版本~~

**Comment by shen20010109** [comment]
> > > > ![image](https://user-images.githubusercontent.com/26327724/77813672-5854de00-70e5-11ea-86ec-4def9db07bff.png)
> > > > 这bug怎么改
> > > 
> > > 
> > > 更新下版本！~
> > 
> > 
> > next的版本吗
> 
> Valine的版本~~

Valine怎么更新版本~~~

**Comment by shen20010109** [comment]
> > > > ![image](https://user-images.githubusercontent.com/26327724/77813672-5854de00-70e5-11ea-86ec-4def9db07bff.png)
> > > > 这bug怎么改
> > > 
> > > 
> > > 更新下版本！~
> > 
> > 
> > next的版本吗
> 
> Valine的版本~~

有没有相关文档 没有百度到

**Comment by Core00077** [comment]
你是咋装的valine就咋更新嗷

**Comment by shen20010109** [comment]
> @shen20010109 你是咋装的valine就咋更新嗷

![image](https://user-images.githubusercontent.com/26327724/77813885-378d8800-70e7-11ea-86af-75267f7c46dd.png)
更新过了还是不行

**Comment by xCss** [comment]
https://github.com/iissnan/hexo-theme-next/blob/620b1e829eb8b6fd72426f3009866b79d8ee2e7b/layout/_third-party/comments/valine.swig#L1-L3

大概就是更新这里的代码吧~

你看看这个文件有啥不一样~

**Comment by shen20010109** [comment]
> https://github.com/iissnan/hexo-theme-next/blob/620b1e829eb8b6fd72426f3009866b79d8ee2e7b/layout/_third-party/comments/valine.swig#L1-L3
> 
> 大概就是更新这里的代码吧~
> 
> 你看看这个文件有啥不一样~

解决了 谢谢了

**Comment by HeyRed233** [comment]
您好，请问一下这个是怎么回事
Code Class or object doesn't exists. [404 GET https://avoscloud.com/1.1/classes/Comment]: Class or object doesn't exists. [404 GET https://avoscloud.com/1.1/classes/Comment]

**Comment by shuiyunxc** [comment]
Code 98: Valine 初始化失败，请检查 av-min.js 版本，，这个情况是怎么解决

**Comment by xCss** [comment]
参考 #285

**Comment by turing0** [comment]
![image](https://user-images.githubusercontent.com/56038300/203781501-628eef53-d395-4fbd-80b1-a8919798fd78.png)
请问这是什么原因啊，next主题，valine版本v1.5.1

**Comment by xCss** [comment]
> ![image](https://user-images.githubusercontent.com/56038300/203781501-628eef53-d395-4fbd-80b1-a8919798fd78.png) 请问这是什么原因啊，next主题，valine版本v1.5.1

如果你是国际版的APPID并在国内访问，请参考 https://forum.leancloud.cn/t/2022-8/25408
如果是报`Code 403: Access denied by API domain white list, Please check your security domain.`，则需要检查你的`域名白名单`设置

**Comment by turing0** [comment]
> > ![image](https://user-images.githubusercontent.com/56038300/203781501-628eef53-d395-4fbd-80b1-a8919798fd78.png) 请问这是什么原因啊，next主题，valine版本v1.5.1
> 
> 如果你是国际版的APPID并在国内访问，请参考 https://forum.leancloud.cn/t/2022-8/25408 如果是报`Code 403: Access denied by API domain white list, Please check your security domain.`，则需要检查你的`域名白名单`设置

谢谢 已解决！
