### ISSUE TITLE
无法载入  Failed to load resource: net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by cxhttt233** [xCss/Valine#177]
![image](https://user-images.githubusercontent.com/28983554/56453214-b0318380-6371-11e9-9c70-0a07246c36e0.png)
![image](https://user-images.githubusercontent.com/28983554/56453245-34840680-6372-11e9-84c8-7a39b32e2344.png)

HEXO+yilia
之前还正常加载，突然不显示了

**Comment by cxhttt233** [comment]
![image](https://user-images.githubusercontent.com/28983554/56453351-eb34b680-6373-11e9-9f40-7fd00c6f98e5.png)

**Comment by xCss** [comment]
抱歉，这是由于`cdn.jsdelivr.net`的https证书过期造成资源无法加载，你可以将cdn地址更改为`//unpkg.com/valine/dist/Valine.min.js`


![微信截图_20190420141810](https://user-images.githubusercontent.com/10877162/56453584-2684b480-6377-11e9-8f06-de8bb1d416a8.png)

**Comment by cxhttt233** [comment]
好的，谢谢
