### ISSUE TITLE
关于一个网站只能用一个valien，限制了一个页面中只能查找最后一个el 的问题

### ISSUE THREAD

**Issue by jahnli** [xCss/Valine#178]
现在valine逻辑：限制了一个页面中只能查找最后一个el  
个人以为el应该为用户自己保证其唯一性

![image](https://user-images.githubusercontent.com/20943608/56493803-e6623500-6522-11e9-9154-c2761e26a25b.png)

Swiper：
![image](https://user-images.githubusercontent.com/20943608/56493895-25908600-6523-11e9-9448-097d0c88d6a5.png)

Echarts：
![image](https://user-images.githubusercontent.com/20943608/56493914-3d680a00-6523-11e9-93b3-9ee1879f0a4e.png)

都没有限制El的设置

**Comment by xCss** [comment]
这个是Leancloud全局对象的限制，和Valine本身无关 

我也很伤心。。。
