### ISSUE TITLE
链接显示不够醒目；点击展开时底下的 <a> 标签也会响应

### ISSUE THREAD

**Issue by Sheey11** [xCss/Valine#180]
1. 链接显示不够醒目(框出来的部分是一个链接)  
![](https://user-images.githubusercontent.com/13375959/57012243-0b982700-6c38-11e9-8b31-1784aac503b4.png)
2. 点击 `Click on expand` 时底层链接也会响应  
![image](https://user-images.githubusercontent.com/13375959/57012288-413d1000-6c38-11e9-90ce-c90adc1fda78.png)
如果点击了 `Click on expand`，底部的 `<a>` 标签也会响应点击事件而打开链接。

**Comment by xCss** [comment]
新版[v1.4.x](https://valine.js.org)已修复了这个问题，感谢反馈~
