### ISSUE TITLE
markdown 代办事项语法渲染错误

### ISSUE THREAD

**Issue by RikkaBlue** [xCss/Valine#182]
```
- [x] test
```
valine对这个语法支持有bug···
```
- [ ] test
```
- [x] test
---
```
- [x] test2
```
- [x] test2
---
佛了
---
![Snipaste_2019-05-09_19-58-15.png](https://i.loli.net/2019/05/09/5cd41675b0ea5.png)

**Comment by xCss** [comment]
已修复，感谢反馈
