### ISSUE TITLE
Comment system doesn't work.

### ISSUE THREAD

**Issue by zeakey** [xCss/Valine#183]
Hi there.
Thanks for providing such a nice tool.

I searched some tutorials and strictly followed the steps to setup valine commend system on
my onw website.

However, it doesn't work.

The preview address is <http://kaizhao.net/cn/>.
And I've already added `http://kaizhao.net` to the white list of my leancloud app.

My website is hosted on a Ubuntu18 virtual machine (I think it doesn't matter).

Can anybody give me a hint ?

**Comment by xCss** [comment]
Hi, thank you for your affirmation of Valine.

I checked the source of your web page and found no problems.

If you don't have new data in your leancloud app, try deleting the current app, then creating a new app and experimenting with the newly acquired appid and appkey.

Good luck!

**Comment by zeakey** [comment]
Hi @xCss , Thanks for your quick response.

So I've switched to a new leancloud app as you suggested.

Now the situation is better: when I post a new comment, it gives me error code `Code 403: Access denied by api domain white list, Please check your security domain.`

I do comfirm that I've added `kaizhao.net` to the white list of my leancloud app.
My white list is as below:
```
http://kaizhao.net
http://kaizhao.net:80
http://kaizhao.net:8080
```

**Comment by xCss** [comment]
You are welcome.
I did not find a new appid on `http://kaizhao.net`. Please confirm if the following prompt appears during local testing?
> Code 403: Access denied by api domain white list, Please check your security domain.

If you use hexo, add http://localhost:4000 to the whitelist before the local test (if you don't have a custom port)

**Comment by zeakey** [comment]
@xCss Yes it works now!

Thanks again for providing such cool tool.
