### ISSUE TITLE
关闭单个页面的评论

### ISSUE THREAD

**Issue by CoderFeiSu** [xCss/Valine#186]
请问如何关闭单个页面的评论

**Comment by xCss** [comment]
https://hexo.io/zh-cn/docs/front-matter



参数 | 描述 | 默认值
-- | -- | --
layout | 布局 |  
title | 标题 |  
date | 建立日期 | 文件建立日期
updated | 更新日期 | 文件更新日期
**comments** | **开启文章的评论功能** | **true**
tags | 标签（不适用于分页） |  
categories | 分类（不适用于分页） |  
permalink | 覆盖文章网址

**Comment by CoderFeiSu** [comment]
好的,多谢。
