### ISSUE TITLE
不能正常引入js文件，是不是托管的文件被删除了？？？

### ISSUE THREAD

**Issue by liuyonghu** [xCss/Valine#187]
![image](https://user-images.githubusercontent.com/14899215/59833321-661c4c80-9378-11e9-87b2-9a5fba8216e3.png)

**Comment by xCss** [comment]
请检查你的网络连接，我这边是正常的。
![image](https://user-images.githubusercontent.com/10877162/59833460-ac71ab80-9378-11e9-91b2-240050bcac62.png)

**Comment by liuyonghu** [comment]
好的

**Comment by liuyonghu** [comment]
确认是LeanCloud的DNS问题。。

**Comment by xCss** [comment]
#188
