### ISSUE TITLE
leancloud无法解析导致Valine无法正常使用

### ISSUE THREAD

**Issue by myloft** [xCss/Valine#188]
[域名无法访问的临时解决方案](https://blog.avoscloud.com/6805/)
cdn1.lncld.net替换为avoscloud.com

**Comment by Mabbs** [comment]
似乎不行，404了

**Comment by xCss** [comment]
我看了下，需要Valine在初始化AV对象的时候设置`serverUrl`，最迟明天更新。

**Comment by HpBoss** [comment]
> 我看了下，需要缬氨酸在初始化AV对象的时候设置`serverUrl`，最迟明天更新。

更新好了，可以通知一下嘛

**Comment by jiyiren** [comment]
有更新好吗？

**Comment by jiyiren** [comment]
leancloud 也太惨了，竟然要被墙

**Comment by xCss** [comment]
@jiyiren @HpBoss 还没，现在遇到的问题是我本地测试出现`cdn1.lncld.net替换为avoscloud.com`替换后无法访问sdk文件

**Comment by lxqxsyu** [comment]
好惨，有修改了临时服务器地址的js文件吗

**Comment by HpBoss** [comment]
我还在等呢






------------------ 原始邮件 ------------------
发件人: "水寒"<notifications@github.com>; 
发送时间: 2019年6月21日(星期五) 中午12:51
收件人: "xCss/Valine"<Valine@noreply.github.com>; 
抄送: "兽兽丷"<193220847@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [xCss/Valine] leancloud无法解析导致Valine无法正常使用 (#188)




好惨，有修改了临时服务器地址的js文件吗

**Comment by jiyiren** [comment]
leancloud sdk 有没有更新的

**Comment by jiyiren** [comment]
![image](https://user-images.githubusercontent.com/7271380/59898542-ddf38100-9423-11e9-87ed-bd3be340be3d.png)

**Comment by HpBoss** [comment]
我看到了，你在用valine吗








------------------ 原始邮件 ------------------
发件人: "jiyiren"<notifications@github.com>; 
发送时间: 2019年6月21日(星期五) 中午12:55
收件人: "xCss/Valine"<Valine@noreply.github.com>; 
抄送: "兽兽丷"<193220847@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [xCss/Valine] leancloud无法解析导致Valine无法正常使用 (#188)

**Comment by lxqxsyu** [comment]
需要修改一下Valine.mie.js的下方代码：
```js
        AV.init({
            serverURLs: 'https://avoscloud.com',
            appId: id,
            appKey: key
        });
```
并更改av.mie.js为：
<script src="//cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js"></script>

**Comment by lxqxsyu** [comment]
> @jiyiren @HpBoss 还没，现在遇到的问题是我本地测试出现`cdn1.lncld.net替换为avoscloud.com`替换后无法访问sdk文件

我刚试了一下好像也不行，着急！

**Comment by p1r06u3** [comment]
![image](https://user-images.githubusercontent.com/17398960/59901244-3418f200-942d-11e9-9387-0229baa388e7.png)
cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js 这个js里的地址还是app-router.leancloud.cn后端服务，需要leancloud去替换。谁能联系上，让他们给我们一个地址。
还有这个lxlh8tot.api.lncld.net。
![image](https://user-images.githubusercontent.com/17398960/59901378-9eca2d80-942d-11e9-9ebd-ba4ab93e2153.png)

**Comment by mstao** [comment]
![TIM图片20190621140809](https://user-images.githubusercontent.com/23411433/59901399-b0abd080-942d-11e9-8a13-9fbf006038df.jpg)

今天收到短信了，被墙了吗，还是怎么回事

**Comment by lxqxsyu** [comment]
> ![image](https://user-images.githubusercontent.com/17398960/59901244-3418f200-942d-11e9-9387-0229baa388e7.png)
> cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js 这个js里的地址还是app-router.leancloud.cn后端服务，需要leancloud去替换。谁能联系上，让他们给我们一个地址。
> 还有这个lxlh8tot.api.lncld.net。
> ![image](https://user-images.githubusercontent.com/17398960/59901378-9eca2d80-942d-11e9-9ebd-ba4ab93e2153.png)

https://avoscloud.com/ 这个官网地址的右下角可以联系上

**Comment by lxqxsyu** [comment]
> ![image](https://user-images.githubusercontent.com/17398960/59901244-3418f200-942d-11e9-9387-0229baa388e7.png)
> cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js 这个js里的地址还是app-router.leancloud.cn后端服务，需要leancloud去替换。谁能联系上，让他们给我们一个地址。
> 还有这个lxlh8tot.api.lncld.net。
> ![image](https://user-images.githubusercontent.com/17398960/59901378-9eca2d80-942d-11e9-9ebd-ba4ab93e2153.png)

![image](https://user-images.githubusercontent.com/7038254/59901894-4300a400-942f-11e9-9163-bc9b1c49f3c0.png)

**Comment by p1r06u3** [comment]
临时方案可以用我博客里面的地址：
http://pirogue.org/js/av-min.js

![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)

**Comment by lxqxsyu** [comment]
> 临时方案可以用我博客里面的地址：
> http://pirogue.org/js/av-min.js
> 
> ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)

果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js

**Comment by invkrh** [comment]
还是不行，leancloud返回410
```
Request URL: https://avoscloud.com/1.1/classes/Comment?where=%7B%22%24or%22%3A%5B%7B%22rid%22%3A%7B%22%24exists%22%3Afalse%7D%7D%2C%7B%22rid%22%3A%22%22%7D%5D%2C%22url%22%3A%22%2F2019%2F05%2F14%2Fexpectation-maximization-explained%2F%22%7D&order=-createdAt%2C-insertedAt&limit=0&count=1
Request Method: GET
Status Code: 410 
```

**Comment by HpBoss** [comment]
兄弟们我们本地没问题了，但是我放在服务器上还是有这个问题，评论区加载不出来

**Comment by HigHwindEx** [comment]
@HpBoss 缓存没刷新吧……你倒是看看控制台是什么错误啊

**Comment by weakish** [comment]
@lxqxsyu 换 jsdelivr CDN，同时初始化语句中设置 serverURLs 后还是不行吗？

**Comment by HpBoss** [comment]
没问题了👌，全都能正常使用了------------------ 原始邮件 ------------------
发件人: "Jang Rush"<notifications@github.com>
发送时间: 2019年6月21日(星期五) 晚上11:41
收件人: "xCss/Valine"<Valine@noreply.github.com>;
抄送: "Danne"<193220847@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xCss/Valine] leancloud无法解析导致Valine无法正常使用 (#188)



@lxqxsyu 换 jsdelivr CDN，同时初始化语句中设置 serverURLs 后还是不行吗？
 
&mdash;

**Comment by HpBoss** [comment]
你说对了，就是这个原因，哈哈------------------ 原始邮件 ------------------
发件人: "HigHwind"<notifications@github.com>
发送时间: 2019年6月21日(星期五) 晚上10:53
收件人: "xCss/Valine"<Valine@noreply.github.com>;
抄送: "Danne"<193220847@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xCss/Valine] leancloud无法解析导致Valine无法正常使用 (#188)



@HpBoss 缓存没刷新吧……你倒是看看控制台是什么错误啊
 
&mdash;

**Comment by HpBoss** [comment]
我想了想应该只有这个原因了------------------ 原始邮件 ------------------
发件人: "HigHwind"<notifications@github.com>
发送时间: 2019年6月21日(星期五) 晚上10:53
收件人: "xCss/Valine"<Valine@noreply.github.com>;
抄送: "Danne"<193220847@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xCss/Valine] leancloud无法解析导致Valine无法正常使用 (#188)



@HpBoss 缓存没刷新吧……你倒是看看控制台是什么错误啊
 
&mdash;

**Comment by weakish** [comment]
看起来 v1.3.7 已经修复了这个问题。

**Comment by lxqxsyu** [comment]
> 兄弟们我们本地没问题了，但是我放在服务器上还是有这个问题，评论区加载不出来

可能是你的站强制https，你需要添加https的库 ：  https://dp2px.com/demo/av-min.js

**Comment by missdeer** [comment]
> > 临时方案可以用我博客里面的地址：
> > http://pirogue.org/js/av-min.js
> > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> 
> 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js

感谢，已用上

**Comment by AomanHao** [comment]
> > 临时方案可以用我博客里面的地址：
> > http://pirogue.org/js/av-min.js
> > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> 
> 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js

这是修改的主题中哪一个文件

**Comment by msdx** [comment]
> > 临时方案可以用我博客里面的地址：
> > http://pirogue.org/js/av-min.js
> > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> 
> 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js

小强？用下你的地址，谢了。

**Comment by myloft** [comment]
> 
> 
> > > 临时方案可以用我博客里面的地址：
> > > http://pirogue.org/js/av-min.js
> > > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> > 
> > 
> > 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js
> 
> @lxqxsyu 小强？用下你的地址，谢了。

现在可以直接把av-min.js的引用删除了。valine.js会自动调用了。

**Comment by AomanHao** [comment]
> > > 临时方案可以用我博客里面的地址：
> > > http://pirogue.org/js/av-min.js
> > > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> > 
> > 
> > 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js
> 
> 这是修改的主题中哪一个文件

我是next6+版本，直接修改_config.yml

![](https://img-blog.nos-eastchina1.126.net/blog/leancloud_link.jpg)

**Comment by BillYang2016** [comment]
奇怪的是，我用的next7，没有修改任何valine相关文件，评论系统可以正常使用。

**Comment by msdx** [comment]
> 奇怪的是，我用的next7，没有修改任何valine相关文件，评论系统可以正常使用。

有些地区可以，有些地区不可以。我用它加入了一个自定义的阅读统计，这几天api请求数锐减为不到之前的十分之一

**Comment by lxqxsyu** [comment]
> > > 临时方案可以用我博客里面的地址：
> > > http://pirogue.org/js/av-min.js
> > > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> > 
> > 
> > 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js
> 
> @lxqxsyu 小强？用下你的地址，谢了。

你的valine评论有问题，看图
![valine评论错误](https://user-images.githubusercontent.com/7038254/59977888-74cd6280-9609-11e9-9595-15609a1c99e3.png)

**Comment by msdx** [comment]
> > > > 临时方案可以用我博客里面的地址：
> > > > http://pirogue.org/js/av-min.js
> > > > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> > > 
> > > 
> > > 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js
> > 
> > 
> > @lxqxsyu 小强？用下你的地址，谢了。
> 
> 你的valine评论有问题，看图
> ![valine评论错误](https://user-images.githubusercontent.com/7038254/59977888-74cd6280-9609-11e9-9595-15609a1c99e3.png)

刚更新的。我升级一下看看。

**Comment by Boyuan26832** [comment]
@invkrh 我也是返回410 `Code : undefined [410 GET https://avoscloud.com/1.1/classes/Comment]`  

如果进入这个网页，就是如下提示：
`{"code":401,"error":"Unauthorized."}`

**Comment by BillYang2016** [comment]
> > > > 临时方案可以用我博客里面的地址：
> > > > http://pirogue.org/js/av-min.js
> > > > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> > > 
> > > 
> > > 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js
> > 
> > 
> > 这是修改的主题中哪一个文件
> 
> 我是next6+版本，直接修改_config.yml
> 
> ![](https://camo.githubusercontent.com/f8d77787300bb4b1c959ca57d8759c3c165a5ec2/68747470733a2f2f696d672d626c6f672e6e6f732d656173746368696e61312e3132362e6e65742f626c6f672f6c65616e636c6f75645f6c696e6b2e6a7067)

NexT 7+版本会自动更新Valine版本，因此不需任何修改。

**Comment by sli1989** [comment]
@p1r06u3  @lxqxsyu  请问数据库的访问问题解决了么。阅读榜无法生成。

```
<script src="//cdn.jsdelivr.net/npm/leancloud-storage/dist/av-min.js"></script>

<script>AV.initialize("**", "**");</script>
```

**Comment by xCss** [comment]
@sli1989 阅读量统计在v1.3.7失效是个已知bug，将会尽快修复

**Comment by sli1989** [comment]
@xCss 谢谢，我更新后，阅读量统计是好的诶？
我指的这个意思：自定义的阅读榜单和点击数，无法从数据库访问获取列表。楼上提到`cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js 这个js里的地址还是app-router.leancloud.cn后端服务`，所以不知道是不是`av-min.js`的问题。

**Comment by xCss** [comment]
@sli1989 如果调用是Valine之外的`AV.init`方法，需要手动设置`serverURLs`:
``` js
   AV.init({
            serverURLs: 'https://avoscloud.com',
            appId: id,
            appKey: key
        });
```

**Comment by msdx** [comment]
> @xCss 谢谢，我更新后，阅读量统计是好的诶？
> 我指的这个意思：自定义的阅读榜单和点击数，无法从数据库访问获取列表。楼上提到`cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js 这个js里的地址还是app-router.leancloud.cn后端服务`，所以不知道是不是`av-min.js`的问题。

我也自己实现了阅读统计，改完目前看来似乎没问题。

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
> > 临时方案可以用我博客里面的地址：
> > http://pirogue.org/js/av-min.js
> > ![image](https://user-images.githubusercontent.com/17398960/59905581-32552b80-9439-11e9-9cfc-690cc1aef229.png)
> 
> 果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js

感谢！我贡献一个自己的全球 cdn 加速地址吧：https://cdn.17shou.vip/www-17shou-vip/valine/av-min.js
qwq

**Comment by HpBoss** [comment]
兄弟，你是我们17的人呀！你不会用这个也在做期末作业吧------------------ 原始邮件 ------------------
发件人: "17shou_VIP"<notifications@github.com>
发送时间: 2019年6月24日(星期一) 晚上10:45
收件人: "xCss/Valine"<Valine@noreply.github.com>;
抄送: "Danne"<193220847@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xCss/Valine] leancloud无法解析导致Valine无法正常使用 (#188)


  
临时方案可以用我博客里面的地址：
 http://pirogue.org/js/av-min.js
 
  
果然好了，感谢，我贡献一个临时的https的地址： https://dp2px.com/demo/av-min.js
  
感谢！我贡献一个自己的全球 cdn 加速地址吧：https://cdn.17shou.vip/www-17shou-vip/valine/av-min.js
 qwq
 
&mdash;

**Comment by sli1989** [comment]
> > @xCss 谢谢，我更新后，阅读量统计是好的诶？
> > 我指的这个意思：自定义的阅读榜单和点击数，无法从数据库访问获取列表。楼上提到`cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js 这个js里的地址还是app-router.leancloud.cn后端服务`，所以不知道是不是`av-min.js`的问题。
> 
> 我也自己实现了阅读统计，改完目前看来似乎没问题。

使用 `cdn.jsdelivr.net/npm/leancloud-storage@3.13.2/dist/av-min.js` 无法读取，暂时使用楼上给出的`av-min.js`可以使用。
