### ISSUE TITLE
切换到 LeanCloud 美国区

### ISSUE THREAD

**Issue by weakish** [xCss/Valine#189]
以避免 #188 重演

另外现在 LeanCloud 国内节点创建应用的门槛比较高：

1. 需要认证手机号
2. 名下最少需要一个商用版应用（每天最低消费 30 元）

**Comment by lxqxsyu** [comment]
> 以避免 #188 重演
> 
> 另外现在 LeanCloud 国内节点创建应用的门槛比较高：
> 
> 1. 需要认证手机号
> 2. 名下最少需要一个商用版应用（每天最低消费 30 元）

太贵了，搞不起，而且没必要

**Comment by weakish** [comment]
美国节点不氪金也可以创建应用

**Comment by Boyuan26832** [comment]
> 美国节点不氪金也可以创建应用

今天我博客切换到了美国节点，但是配置完以后就是`Code : undefined [410 GET https://avoscloud.com/1.1/classes/Comment]`  
不清楚问题出在了哪里？
此网页的提示就是`{"code":401,"error":"Unauthorized."}`
