### ISSUE TITLE
请暴露用于首页显示评论数的接口

### ISSUE THREAD

**Issue by codefine** [xCss/Valine#19]
已经完美融入我的主题了，但是我想在首页每个文章摘要中显示，没找到相应接口。
是我没找到，还是？
求建议。

**Comment by xCss** [comment]
@codefine 不要着急，首页评论数统计接口已加入下个版本的开发计划。
尽请期待吧。ヽ(￣▽￣)ﾉ

**Comment by codefine** [comment]
好的，那只能预祝下个版本早日落地咯，加油加油。
