### ISSUE TITLE
v1.3.7 无法支持 LeanCloud 华东地区节点应用

### ISSUE THREAD

**Issue by lei2rock** [xCss/Valine#190]
Valine v1.3.7 更新后，无法支持 LeanCloud 华东地区节点应用获取评论，见我的[博客](https://blog.dlzhang.com/about/)或下图。
![Bug](https://user-images.githubusercontent.com/19180725/59967814-519ba800-9562-11e9-8aba-1ef08ef4e185.jpg)

**Comment by invkrh** [comment]
我也遇到了同样的问题，我即使切换到国际版也不行

**Comment by lei2rock** [comment]
> 我也遇到了同样的问题，我即使切换到国际版也不行

@invkrh 应该是因为新版本的紧急 bug 修复只考虑了华北节点，华东（tab）和美国（us）节点因为域名不一样所以没有兼顾到。感觉还是等 LeanCloud 解决域名解析问题比较好。

**Comment by Boyuan26832** [comment]
> > 我也遇到了同样的问题，我即使切换到国际版也不行
> 
> @invkrh 应该是因为新版本的紧急 bug 修复只考虑了华北节点，华东（tab）和美国（us）节点因为域名不一样所以没有兼顾到。感觉还是等 LeanCloud 解决域名解析问题比较好。

同一个问题，切换到国际版就是如下提示，
`Code : undefined [410 GET https://avoscloud.com/1.1/classes/Comment]`  
  
如果真的是域名问题，只有等leancloud解决，但是为什么这个url点击进入返回`{"code":401,"error":"Unauthorized."}`?

**Comment by lei2rock** [comment]
> > > 我也遇到了同样的问题，我即使切换到国际版也不行
> > 
> > 
> > @invkrh 应该是因为新版本的紧急 bug 修复只考虑了华北节点，华东（tab）和美国（us）节点因为域名不一样所以没有兼顾到。感觉还是等 LeanCloud 解决域名解析问题比较好。
> 
> 同一个问题，切换到国际版就是如下提示，
> `Code : undefined [410 GET https://avoscloud.com/1.1/classes/Comment]`
> 
> 如果真的是域名问题，只有等leancloud解决，但是为什么这个url点击进入返回`{"code":401,"error":"Unauthorized."}`?

因为你直接点击进入的时候没有应用的ID和key（相当于空的验证），当然提示授权失败。华东节点和国际版错误应该是因为最新的 Valine 修改相关链接时候只考虑了华北节点的情况，没有考虑到华东节点和美国节点域名不一样，所以变成用华东节点和美国节点的应用ID和key去华北节点尝试登陆，自然不行。

**Comment by invkrh** [comment]
粗略地看了下近期的commits没有发现相关的内容。
@xCss 有空的话，希望能看下这个issue。
谢谢

**Comment by xCss** [comment]
@lei2rock @invkrh @RikkaBlue 新版`v1.3.8`已发布，会根据`appid`自动匹配`serverURLs`

**Comment by leafjame** [comment]
请问现在解决了嘛？你们用的是hexo next类的博客主题还是？我今天把valine从国内版的Leancloud切换到国际版成功了。期间出现
```
{
  "code": 401,
  "error": "Unauthorized."
}
```
这个错误，官方解释：认定为 App ID 或者 App Key 输入有误
然后我clean多次，不知道怎么就好了。。。
next版本5.1.4，valine版本1.3.10
