### ISSUE TITLE
建议头像添加一个 QQ 头像 api

### ISSUE THREAD

**Issue by Snowflake-Pink** [xCss/Valine#192]
如题，感觉 Gravatar 的头像不太方便，普通用户一般都不会用，而且同步时间长。
QQ 头像 api：https://q1.qlogo.cn/g?b=qq&nk=【QQ号】&s=640

**Comment by staymo** [comment]
个人感觉微信比QQ优先级更高。有人不用QQ，但没人不用微信

**Comment by laomocode** [comment]
不过感觉还是用QQ头像吧，感觉更易用

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
有一点，就是微信头像是需要授权的，但是 QQ 已经是开放 API 的，所以说如果要用微信可能还要扫码，挺麻烦的，技术上也要另写很多代码。
话说作者没有更吗 qwq

**Comment by xCss** [comment]
@WhiteSnowPinkPinkWhatItLike 正在进行中，预计下下个版本应该会有吧(又挖坑。。。逃。。。)

**Comment by AyagawaSeirin** [comment]
解析出QQ邮箱中的QQ号，再通过接口就能获取头像了，很方便的。强烈推荐加上这个功能！

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
有一个项目：https://github.com/justauth/JustAuth
可以支持更多方式的授权登陆

**Comment by Clansty** [comment]
> 个人感觉微信比QQ优先级更高。有人不用QQ，但没人不用微信

谁说的？我就不用微信
微信是针对老年人的
（我们这边的）人基本上都用 QQ

**Comment by MHuiG** [comment]
这里贴一下大佬的链接 : https://blog.csdn.net/cungudafa/article/details/104638730

**Comment by kongfl888** [comment]
匿名头像如果能本地提供更好，感觉。毕竟没几个游客是不匿名的，大家都懒留也懒注册。
至少可以减少“外”网流量。

**Comment by xCss** [comment]
新版[v1.4.5](https://valine.js.org)已发布，已支持QQ头像，感谢反馈~
