### ISSUE TITLE
v1.3.9 无法支持 LeanCloud 华东地区节点应用

### ISSUE THREAD

**Issue by BurgerTown** [xCss/Valine#194]
![图片](https://user-images.githubusercontent.com/19660419/61554282-2471e500-aa8f-11e9-9844-9b4b93cd3eb8.png)

跟这个[issue](https://github.com/xCss/Valine/issues/190)一样
对于华东节点的应用 还是会出现410错误
我查看了判断判断方式 觉得过于粗糙
查看了 leancloud 的文档 华东节点的域名应该是 tab.avoscloud.com
而不是 avoscloud.com

对比的 查看了 leancloud-visitor 的判断方式
会先通过 https://app-router.leancloud.cn/2/route?appId=
获取对应APP所对应的服务器的域名

**Comment by lmm214** [comment]
同问题，切回1.3.6坚挺

**Comment by xCss** [comment]
这个Bug会在v1.3.10版本中解决。如果想要尝鲜，请从楼主的cdn获取 https://blog-1253475808.file.myqcloud.com/Valine.min.js

**Comment by lmm214** [comment]
> 这个Bug会在v1.3.10版本中解决。如果想要尝鲜，请从楼主的cdn获取 https://blog-1253475808.file.myqcloud.com/Valine.min.js

耐心等待官方更新，很好用再次感谢！

**Comment by jiankunking** [comment]
> 这个Bug会在v1.3.10版本中解决。如果想要尝鲜，请从楼主的cdn获取 https://blog-1253475808.file.myqcloud.com/Valine.min.js

你好 1.3.10 release什么时间发布？

**Comment by xCss** [comment]
@BurgerTown @lmm214 @jiankunking [v1.3.10](https://github.com/xCss/Valine/releases/tag/v1.3.10) 已发布
