### ISSUE TITLE
Valine回复重复

### ISSUE THREAD

**Issue by laomocode** [xCss/Valine#197]
你好，我是一位小白。
我在我的Jekyll博客上使用了Valine，可是发现评论居然重复了。查看了源代码，似乎显示了两个一样的评论。
那么，我该怎么办？我用的是Gitee Pages，求教。
项目网址：https://gitee.com/laomocode/laomocode

**Comment by xCss** [comment]
你好，看了下源码，发现没什么问题，能否留下预览地址？

**Comment by xCss** [comment]
找到问题了，你的`laomocode/_layouts/default.html`页面中引入了`{% include comments.html %}`

而`laomocode/_layouts/post.html`页面中又引入了一次。

**Comment by laomocode** [comment]
谢谢 @xCss ，问题解决了
