### ISSUE TITLE
在leancloud哪里有class comment？(如图)

### ISSUE THREAD

**Issue by xiebruce** [xCss/Valine#198]
![image](https://user-images.githubusercontent.com/13575500/62184192-83890100-b38f-11e9-8426-07d65ed47a0f.png)

这没有什么comment呀，是让我们自己创建一个？
![image](https://user-images.githubusercontent.com/13575500/62184255-cc40ba00-b38f-11e9-9d43-25c36263744a.png)

**Comment by xCss** [comment]
如果已经有评论数据，那么会自动创建 Class `Comment`

**Comment by xiebruce** [comment]
@xCss 哦哦，原来是自动创建的
