### ISSUE TITLE
感谢Valine提供的评论服务

### ISSUE THREAD

**Issue by laomocode** [xCss/Valine#201]
大家好，我是[作文小站](https://laomocode.gitee.io)的站长。我特别感谢这个评论服务，易用性做的特别好。
之前，这个小站使用的是[Gitalk](https://github.com/gitalk/gitalk)的评论服务。但是我发现，这玩意是基于Github的Issus功能。导致了评论需要登录Github账号。又因为Github的登录界面是全英文的，导致了无人使用评论的情况。
后来，为了加快速度，我把作文小站移到了[码云](https://gitee.com)的Pages服务，顺便也把评论系统改为Valine。很快，我发现Valine评论系统特别易用（对于用户来说），很多人也开始评论了。这次，我特别感谢Valine为我们作文小站提供评论服务。
还有， @xCss ，什么时候1.3.10推出呢😂？

**Comment by xCss** [comment]
已发布~感谢支持

[v1.3.10](https://github.com/xCss/Valine/releases/tag/v1.3.10)
