### ISSUE TITLE
LeanCloud要求10月1日绑定个人域名，会有影响吗？

### ISSUE THREAD

**Issue by songjinghe** [xCss/Valine#203]
我在LeanCloud上收到的通知如下：

> 10 月 1 日起 LeanCloud 中国版将停止为不绑定自有域名的应用服务，还请未绑定用户尽快绑定自己的域名，以免业务受到影响。更多内容请[点击详情](https://leancloudblog.com/mandatory-domain-config/)。

**Comment by leeyiding** [comment]
可以把国内版的数据导出，到leancloud国际版注册一个账号，再把数据导入国际版应用，不过我的1.3.7版本valine报错Code : undefined [410 GET https://avoscloud.com/1.1/classes/Comment]

**Comment by xCss** [comment]
@songjinghe 如果配置了域名，可以设置`serverURLs`值为你设置的域名，如果是国际节点则不影响。
参考 [v.13.10](https://github.com/xCss/Valine/releases/tag/v1.3.10)

**Comment by songjinghe** [comment]
@xCss 多谢
