### ISSUE TITLE
wiki里的邮箱提醒照片链接挂了

### ISSUE THREAD

**Issue by therehello** [xCss/Valine#204]

**Comment by xCss** [comment]
已修复~ https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
