### ISSUE TITLE
关于在NexT配置Valine报错

### ISSUE THREAD

**Issue by miniminiwhite** [xCss/Valine#205]
你好~我在配置自己的github.io的时候，用了NexT的主题，然后想在评论区配置Valine.
不过按照NexT官网的指引配置完之后，发现评论区会报```Code : undefined [410 GET https://avoscloud.com/1.1/classes/Comment]```的错误...
后面重新注册了一个leancloud国际版的账户，换上新的appid和appkey之后错误就变成了```Code 401: 未经授权的操作，请检查你的AppId和AppKey.```但是我核对过几次，并不是AppId和AppKey的问题...
想问下这个是不是同一样东西？然后现在这个有没有什么比较好的解决方案？

**Comment by miniminiwhite** [comment]
哦对了另外想问下，在Valine的官网下面看到有些评论是有自己的头像的。所以说评论的人是用什么办法登录的咧？还是说博主这边可以做什么相关设置之类的...

**Comment by xCss** [comment]
@miniminiwhite 你好，出现`410`问题应该是节点判断出错，请更新到[v1.3.10](https://github.com/xCss/Valine/releases/tag/v1.3.10)版本(或者等`CDN`自动更新)

另外，头像可参考 https://valine.js.org/avatar.html
