### ISSUE TITLE
Feature Request: 增加 serverURLs 字段

### ISSUE THREAD

**Issue by YunYouJun** [xCss/Valine#206]
LeanCloud 发布公告，使用服务将必须绑定自定义域名。 https://leancloudblog.com/mandatory-domain-config/

```js
AV.init({
  appId: "xxx",
  appKey: "xxx",
  serverURLs: "https://xxx.example.com",
});
```
现在 LeanCloud 初始化需要提供 `serverURLs` 字段了，希望 Valine 可以增加该字段的自定义配置。

**Comment by xCss** [comment]
已发布新版，参考 [v1.3.10](https://github.com/xCss/Valine/releases/tag/v1.3.10)
