### ISSUE TITLE
阅读数列表页面可以显示，文章详情却不行

### ISSUE THREAD

**Issue by note4** [xCss/Valine#208]
## 列表页面
![image](https://user-images.githubusercontent.com/6513389/64323980-199bf100-cff8-11e9-81b1-a25b21eb5892.png)

里面的55是调试输入的

## 详情页面
![image](https://user-images.githubusercontent.com/6513389/64324012-24ef1c80-cff8-11e9-9d3a-354b4f3a6935.png)

## js报错
![image](https://user-images.githubusercontent.com/6513389/64324087-45b77200-cff8-11e9-8c8d-5398e776bbfa.png)

```
{code: 111,…}
code: 111
error: "Invalid value type for field 'time',expect type is {:type "String"},but it is '{:type "Number"}'."
```

### 新窗口打开的报错提示
```
{"code":401,"error":"Unauthorized."}
```

两个页面的配置都是一样的，区别是详情页有评论框

**Comment by xCss** [comment]
请留下预览地址

**Comment by note4** [comment]
可能是 time 的类型 有问题，这个还能编辑吗
可能是要 数字 现在是 string

**Comment by note4** [comment]
> 请留下预览地址

zlun*gitlab*yijile.com

有劳星号替换.
临时地址，不想被抓，typecho转过来测试

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/64324795-98455e00-cff9-11e9-9896-a39f58cd5c31.png)

![image](https://user-images.githubusercontent.com/10877162/64324816-a1cec600-cff9-11e9-9513-79c1d5b5cbd8.png)


额，我这显示没问题

**Comment by note4** [comment]
> ![image](https://user-images.githubusercontent.com/10877162/64324795-98455e00-cff9-11e9-9896-a39f58cd5c31.png)
> 
> ![image](https://user-images.githubusercontent.com/10877162/64324816-a1cec600-cff9-11e9-9513-79c1d5b5cbd8.png)
> 
> 额，我这显示没问题
> 
> 而且。。。我也没看到加载Valine。。。

没加载valine？

太恐怖了，我还以为哪里出了问题，搁着几个月了。惨

**Comment by note4** [comment]
难道是 chrome 插件 导致的兼容性

**Comment by xCss** [comment]
抱歉，我在你的整个网页中，真没找到valine

**Comment by note4** [comment]
> 抱歉，我在你的整个网页中，真没找到valine

那为什么 你在详情可以看到 阅读数，好诡异

https://pinwu.pub/url/chrome/

我代码从配置这个站直接复制的，但这个站在我浏览器是正常的，然后这个站 leancloud 中的 time 的类型是数字
#### pinwu
![image](https://user-images.githubusercontent.com/6513389/64325633-18b88e80-cffb-11e9-8b1f-6663767cc437.png)
#### zlun
![image](https://user-images.githubusercontent.com/6513389/64325605-0e969000-cffb-11e9-82f8-214e87d88d72.png)

**Comment by note4** [comment]
![image](https://user-images.githubusercontent.com/6513389/64325745-456ca600-cffb-11e9-9387-f9ed4359241f.png)

**Comment by xCss** [comment]
额，你截图这个是`pinwu.pub`的，不是之前发那个~

**Comment by note4** [comment]
![image](https://user-images.githubusercontent.com/6513389/64325993-ba3fe000-cffb-11e9-8fa4-28b6fde4675c.png)

**Comment by xCss** [comment]
好吧，我以为要去掉`gitlab`。。。

**Comment by note4** [comment]
> 好吧，我以为要去掉`gitlab`。。。

😢

**Comment by note4** [comment]
应该是time的数据类型的问题，但是备份数据不能在12点后操作。
可是为什么列表可以正常显示，比较诡异

**Comment by xCss** [comment]
恩，确认是time数据类型问题，你数据库中存的是`String`，而实际上应该是`Number`

列表正常显示是因为没有写操作，只有读

**Comment by note4** [comment]
> 恩，确认是time数据类型问题，你数据库中存的是`String`，而实际上应该是`Number`
> 
> 列表正常显示是因为没有写操作，只有读

谢谢大佬，我也不知道怎么数据库是string，这是不是只能备份然后修改备份文件再通过恢复数据修改？

**Comment by note4** [comment]
修改 valine.js 应该也可以解决这个问题对吧😺

**Comment by xCss** [comment]
> 修改 valine.js 应该也可以解决这个问题对吧😺

不要想了。。。还是老老实实改数据库吧

**Comment by note4** [comment]
> > 修改 valine.js 应该也可以解决这个问题对吧😺
> 
> 不要想了。。。还是老老实实改数据库吧

那要等到明天。。。不行我要挑战下，虽然我不会js😂

**Comment by xCss** [comment]
> > > 修改 valine.js 应该也可以解决这个问题对吧😺
> > 
> > 不要想了。。。还是老老实实改数据库吧

> 那要等到明天。。。不行我要挑战下，虽然我不会js😂

那你加油~~

**Comment by note4** [comment]
> > > > 修改 valine.js 应该也可以解决这个问题对吧😺
> > > 
> > > 
> > > 不要想了。。。还是老老实实改数据库吧
> 
> > 那要等到明天。。。不行我要挑战下，虽然我不会js😂
> 
> 那你加油~~

....从入门到放弃。。。。
我还是乖乖等明天，为什么leancloud不能编辑结构

也是一直有一个疑问，如果以后 leancloud 挂了或者完全收费了，有b计划吗，valine很好用，但是之前在别人博客评论区说leancloud不稳定所以放弃，也是无言以对

**Comment by xCss** [comment]
所以啊，是类型的问题啊~

**Comment by xCss** [comment]
> 也是一直有一个疑问，如果以后 leancloud 挂了或者完全收费了，有b计划吗，valine很好用，但是之前在别人博客评论区说leancloud不稳定所以放弃，也是无言以对

在努力的开发其他云数据库版本~

**Comment by note4** [comment]
> > 也是一直有一个疑问，如果以后 leancloud 挂了或者完全收费了，有b计划吗，valine很好用，但是之前在别人博客评论区说leancloud不稳定所以放弃，也是无言以对
> 
> 在努力的开发其他云数据库版本~

你最棒，加油！有没有那种轻量像ssr傻瓜式部署的，架在gcp?

谢谢大佬搞定了，重新从typecho数据库折腾了一份出来
