### ISSUE TITLE
头像后边展示IP和操作系统有办法去掉么

### ISSUE THREAD

**Issue by maxisvest** [xCss/Valine#210]
如图
![image](https://user-images.githubusercontent.com/20422618/64482689-687c9d00-d229-11e9-9801-5b986ff36794.png)

**Comment by maxisvest** [comment]
是使用的next自带的配置，页面展示valine版本为1.3.10

**Comment by xCss** [comment]
可以自己写css覆盖
``` css
.vsys{display:none;}
```
