### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by L1cardo** [xCss/Valine#211]
能不能在获取到的系统信息前面有个小图标支持？
类似这种的：
![截屏2019-09-15下午10 54 45](https://user-images.githubusercontent.com/33802186/64923365-da497d80-d80b-11e9-9084-d691d14baecf.png)
![截屏2019-09-15下午10 54 51](https://user-images.githubusercontent.com/33802186/64923366-db7aaa80-d80b-11e9-81ec-951008d9fdca.png)
不需要这么花里胡哨，就是awesomefont图标就好了，当然能做成彩色的更好。
我想自己加，但是是个代码小白。

这个需求可能不太难实现，可能无关紧要，但是会增加美观，而且一眼就能看出来是什么系统

谢谢！

**Comment by L1cardo** [comment]
Hello？

**Comment by xCss** [comment]
@L1cardo 这个需求是很简单，但是需要用户自己去实现，毕竟Valine不可能把awesome-font打包进去。
