### ISSUE TITLE
新功能需求

### ISSUE THREAD

**Issue by L1cardo** [xCss/Valine#212]
建议：当回复某条评论时，评论框能直接显示在此评论下方，现在无论是哪条都是跳回到上方。

这也导致回复页面底下的评论时出现：点击回复，跳转到上方，点击提交，手动拉倒页面底部看是否提交成功。

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xCss** [comment]
@L1cardo 该功能将在新版v1.4.0推出，敬请期待
