### ISSUE TITLE
hexo-theme-even主题下频现error

### ISSUE THREAD

**Issue by hishark** [xCss/Valine#214]
[hexo-theme-even](https://github.com/ahonn/hexo-theme-even)
error如图：
![image](https://user-images.githubusercontent.com/29684201/66299512-43fa0a80-e926-11e9-8ebd-9487fbd2b801.png)

**Comment by xCss** [comment]
请更新到最新版

```js
<script src="https://cdn.jsdelivr.net/npm/valine"></script>
```

**Comment by hishark** [comment]
> 请更新到最新版
> 
> ```js
> <script src="https://cdn.jsdelivr.net/npm/valine"></script>
> ```

好的谢谢，我下课回去试试
