### ISSUE TITLE
评论能接入QQ 微信 微博 谷歌 等账号吗

### ISSUE THREAD

**Issue by wkq278276130** [xCss/Valine#22]
什么时候评论能接入QQ 微信 微博 谷歌 等账号吗

**Comment by xCss** [comment]
@wkq278276130 你好，接入`QQ、微信、微博、谷歌`等帐号的主要目的是什么？

**Comment by wkq278276130** [comment]
@xCss  不用输入邮箱账号，而是通过qq、微信、微博等账号就可以登录评论

**Comment by xCss** [comment]
@wkq278276130 抱歉，这貌似需要后端支持，并存储授权登陆信息。

**Comment by vimcaw** [comment]
@xCss 好像是可以在前端处理登录的：
[leancloud 用户系统 \- 工具资源 \- 掘金](https://juejin.im/entry/571af2cd2e958a0055f07214)
[在云代码中处理用户登录 \| LeanCloud Blog](https://blog.leancloud.cn/597/)
[leancloud \- SNS第三方登录保存昵称、头像 \- SegmentFault 思否](https://segmentfault.com/q/1010000000478451)
[第三方平台账号登录组件（SNS）开发指南 \- LeanCloud 文档](https://tab.leancloud.cn/docs/sns.html)
