### ISSUE TITLE
highlight参数无法影响更改之前发布的评论中代码的高亮状态

### ISSUE THREAD

**Issue by JingwangLi** [xCss/Valine#225]
我发现highlight参数无法影响更改之前发布的评论中代码的高亮状态，即在改变highlight参数之前发布的评论中的代码的高亮状态是不受影响的，如下所示：
<img width="577" alt="{91940431-CAEC-4FC7-9FEF-6C9B896ADE44}" src="https://user-images.githubusercontent.com/29228612/73911954-3bbed580-48ee-11ea-8cc8-ccf0e88d6753.png">

请问如何解决该问题？

**Comment by JingwangLi** [comment]
？

**Comment by xCss** [comment]
这个应该删掉之前无高亮的评论，已经生成html代码的无法重新渲染，抱歉
