### ISSUE TITLE
Firefox无法加载评论区，报错MIME 类型（“text/html”）不匹配

### ISSUE THREAD

**Issue by zerofancy** [xCss/Valine#228]
![图片](https://user-images.githubusercontent.com/40628516/74814494-5489ab00-5332-11ea-943e-2087023f4dd8.png)

![图片](https://user-images.githubusercontent.com/40628516/74814510-63705d80-5332-11ea-8a5b-f803a3db7b73.png)

## The steps to reproduce.
https站使用`<script src='//unpkg.com/valine/dist/Valine.min.js'></script>`引入（放在了head区），创建Valine的脚本放在了页面底部，使用firefox73.0浏览。（npm安装的也有报错，但能正常使用）

## A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
无法访问这两个网站。

## Which versions of Valine, and which browser / OS are affected by this issue?
- Valine 最新版，使用`<script src='//unpkg.com/valine/dist/Valine.min.js'></script>`
- OS Ubuntu 18.04LTS
- browser Firefox73.0

**Comment by xCss** [comment]
这个应该属于CDN分发服务的锅，不知道应该怎么解决~~
