### ISSUE TITLE
limit为0的请求

### ISSUE THREAD

**Issue by YES-Lee** [xCss/Valine#229]
在hexo下，SPA主题中，进入文章页面加载Valine插件，插件正常加载，评论没有加载出来。经过检查发现请求评论数据的接口中limit为0。刷新后正常，请求的limit为10。
![image](https://user-images.githubusercontent.com/19748456/74938231-9137ce00-5428-11ea-8ec0-1905f6b3e6cf.png)

![image](https://user-images.githubusercontent.com/19748456/74938185-7feec180-5428-11ea-86f8-99442ead802a.png)

**Comment by sdlyfjx** [comment]
这个库貌似没人维护了啊都。。。
