### ISSUE TITLE
初始化失败，请检查你的appid或者appkey.

### ISSUE THREAD

**Issue by Captain-SJ** [xCss/Valine#23]
Valine:1.1.7-rc3

部署后，打开主页，评论框下面出现这个问题，appid和appkey均检查了几遍无误。另外，在评论框输入内容，点击回复时，无反应，也无法评论。请教一下，谢谢。

**Comment by xCss** [comment]
@Captain-SJ 请提供下预览地址、浏览器环境等，以方便我定位错误。

谢谢~

**Comment by Captain-SJ** [comment]
@xCss 不好意思，根目录配置文件下的appid和valine.ejsx下的appId大小写不一样，查了半天找出来了。现在评论系统可以用了，十分感谢。:)

**Comment by xCss** [comment]
@Captain-SJ ok~
