### ISSUE TITLE
「网址」被识别成相对路径

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#232]
我在valine官网测试了一下： https://valine.js.org

![](https://user-images.githubusercontent.com/16400144/75090032-bc8dfa80-5599-11ea-8aa8-5e672a057dc9.png)

![QQ20200222-173917@2x.png](https://i.loli.net/2020/02/22/OR46u8gStEeT1NJ.png)

网址那里只写 `baidu.com`，点击回复。
然后在评论中点击名字就跳转到了 `https://valine.js.org/baidu.com`。

不知道这个问题开发者能否优化一下？

**Comment by 2Broear** [comment]
这个问题可以加个url验证（但是会影响用户体验），还有就是加载评论的时候自动去匹配错误的url并替换@xCss

**Comment by xCss** [comment]
> 这个问题可以加个url验证（但是会影响用户体验），还有就是加载评论的时候自动去匹配错误的url并替换@xCss

那用户就是想输入错的url呢
