### ISSUE TITLE
v1.1.7 到 v1.3.10 数据不互通怎么办？

### ISSUE THREAD

**Issue by YoungSx** [xCss/Valine#233]
我旧主题 Anatole（https://github.com/Ben02/hexo-theme-Anatole）使用的是 v1.1.7，
而换上 Ocean 主题（https://github.com/zhwangart/hexo-theme-ocean）后使用的是最新版 v1.3.10。
发现数据不互通，在我自己的比对两个主题之后，发现是 Valine 版本问题。
v1.1.7 对 pathname 的处理是先 url_encode 再使用，而 v1.3.10 则是直接使用。
这就导致了 leancloud 中存储的数据 url(path) 是不一致的，从而导致评论数据不互通。

有什么办法可以迁移数据吗，或者说只能手动去修改 leancloud 里面的数据？

**Comment by stevenjoezhang** [comment]
写个脚本把全部数据 url_encode 一遍？或者升级到 Hexo 4

**Comment by YoungSx** [comment]
@stevenjoezhang 我的数据不是很多，之前手动 url_encode 了，话说 Hexo 4 是什么操作

**Comment by stevenjoezhang** [comment]
Hexo 4 默认会 url_encode，如果主题支持的话，应该能直接把正确的 url 传给 valine
