### ISSUE TITLE
如何防止有人仿冒评论?

### ISSUE THREAD

**Issue by RivenNero** [xCss/Valine#237]
举个例子, 比如有人想评论我的一个文章, 那么他只要知道了我的邮箱就可以冒充我的评论了, 有没有什么方法来阻止这个现象呢?

**Comment by sli1989** [comment]
按照目前逻辑，应该没这个功能。手工后台删除，或者去 https://wordpress.com/me 个性化头像。

**Comment by RivenNero** [comment]
好吧
