### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: Storage is not defined

### ISSUE THREAD

**Issue by jeremy0519** [xCss/Valine#242]
latest version of valine and i install it by npm.
I have already insert the code:
`import Valine from 'valine';`
`window.AV = require('leancloud-storage');`

**Comment by jeremy0519** [comment]
@xCss

**Comment by lovepoem** [comment]
这个应该是因为用了react的新版本

**Comment by xCss** [comment]
@jeremy0519 @lovepoem 这个问题应该是Valine最新版中的Bug，我正在排查，将于近期更新。感谢反馈。

**Comment by jeremy0519** [comment]
那什么版本不会出现这个问题？

**Comment by xCss** [comment]
@jeremy0519 请尝试下1.3.9版本

**Comment by jeremy0519** [comment]
@xCss v1.3.9还是不行

**Comment by xCss** [comment]
@jeremy0519 请尝试下这个版本
``` js
// leancloud-storage 已经打包进了Valine.min.js
import Valine from '/path/Valine.min.js'
```
使用中有什么问题请随时反馈，感谢~

[Valine.min.zip](https://github.com/xCss/Valine/files/4374503/Valine.min.zip)

**Comment by jeremy0519** [comment]
@xCss 我没有用`window.AV=require('leancloud-storage');`，还是不行

**Comment by lovepoem** [comment]
docsite新版本是不是已经解决了这个问题？

**Comment by xCss** [comment]
@jeremy0519 请尝试下[v1.4.0](https://github.com/xCss/Valine/releases/tag/v1.4.0)版本
