### ISSUE TITLE
怎么在docsite 框架下添加Valine ？

### ISSUE THREAD

**Issue by lovepoem** [xCss/Valine#243]
https://github.com/wuhan2020/wuhan2020.github.io
是一个用
docsite ： https://github.com/txd-team/docsite

做的博客系统，现在想用Valine 发现加上有问题，不在合适的位置。
见 https://github.com/wuhan2020/wuhan2020.github.io/pull/470
求指导

**Comment by jeremy0519** [comment]
@xCss

**Comment by jeremy0519** [comment]
在react中使用时会报错，见 #242
