### ISSUE TITLE
使用Hexo NexT主题，访问首页浏览器会报错 429 状态码

### ISSUE THREAD

**Issue by lei2rock** [xCss/Valine#245]
使用 Hexo NexT 主题，访问首页（index.html）的时候浏览器会报错 429 状态（但是浏览其他页面均不会出现报错），截图如下：
![](https://user-images.githubusercontent.com/19180725/77508443-abd8e900-6ea5-11ea-8b3f-0ef3c5546c5d.jpg)

使用 macOS 系统，对于 Safari 和 Chrome 浏览器均有相同的情况，尝试关闭主题的 PJAX 功能也同样会出现该错误。不知道应该是 Valine 的问题，还是 Hexo NexT 主题的问题？

**相关链接**

- [博客地址](https://blog.dlzhang.com)
- [源代码地址](https://github.com/lei2rock/blog)

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/77511582-56540a80-6eac-11ea-8c5b-760c2db55ae0.png)

**Comment by lei2rock** [comment]
就是说一次请求了太多了评论数吗，了解了。不是我这边的设置错误就行，就等你的优化了，多谢！

**Comment by xCss** [comment]
> 就是说一次请求了太多了评论数吗，了解了。不是我这边的设置错误就行，就等你的优化了，多谢！

不是请求太多评论数，而是短时间内请求次数过多~
