### ISSUE TITLE
是否可以把url作为可配置打开

### ISSUE THREAD

**Issue by liu578101804** [xCss/Valine#246]
现在用户评论用户是可以填写自己的url，这对网址来说存在潜在风险，建议可以作为配置项，原因打开就打开，谢谢。

**Comment by xCss** [comment]
评论本来就是让用户畅所欲言，限制用户填写自己的URL，还不如直接关闭评论~~

**Comment by liu578101804** [comment]
我是建议可以设置为可配置，不是说关闭他

**Comment by liu578101804** [comment]
我只是建议，作者不喜欢，与你的初衷不同了，可以不采纳。
