### ISSUE TITLE
一个小问题：刷新页面后评论不能再次发送

### ISSUE THREAD

**Issue by I-Info** [xCss/Valine#247]
如题，网站的评论能够正常发送接收。但是，刷新页面之后，评论就不能再次发送了（按下“回复”按钮没有反应，没有出现算术验证的界面）。
但是，如果删除掉网页的本地存储后就可以正常评论了。同样，再次刷新后，又不能发送评论。
***
valine版本：1.3.10
目前测试的浏览器：*chrome 80.0.3987.149*（刷新后失效）*chrome 62.0.3202.84*（正常） *Safari 12.1.2*（正常）
但是我的chrome 80版本使用其他网站的valine 1.3.10 评论系统又是正常的。
希望得到解决的办法，谢谢

**Comment by xCss** [comment]
麻烦提供下网页地址~

**Comment by I-Info** [comment]
好的：
<https://www.i-info.xyz>

**Comment by I-Info** [comment]
可能是chrome的某个版本的问题，但又感觉说不通，因为我在其他网站刷新评论都正常。这就很奇怪。。

**Comment by xCss** [comment]
> 可能是chrome的某个版本的问题，但又感觉说不通，因为我在其他网站刷新评论都正常。这就很奇怪。。

是啊，这就很奇怪了，我测试是正常的。。。

控制台也没见报错~

**Comment by I-Info** [comment]
问题应该不大，虽然发送不了，但是控制台也没有报错。目前问题锁定在Chrome 80.0.3987.xxx （我的手机Chrome 80.0.3987.132 电脑Chrome 80.0.3987.149，都出现问题）这个版本。目前其他浏览器和chrome版本没有问题，我试试chrome beta版本看看。

**Comment by I-Info** [comment]
好吧，chrome的beta版和正式版不能用，dev版可以正常使用。。

**Comment by I-Info** [comment]
@xCss 目前新的发现：chrome dev版本，评论后关闭浏览器再打开网页，也无法再次评论了（是不是因为验证无法加载出来？）。这个问题就很迷。。目前测试的其他浏览器不存在这个问题。是不是与本地缓存有关？如果有机会的话，希望您能帮忙测试一下，谢谢。

**Comment by xCss** [comment]
试了下，我这边貌似没发现这个问题~~ !-_-!

**Comment by I-Info** [comment]
额，这就很尴尬了。可能是我的网站配置存在问题。但就目前看来，我找不到问题的原因。

**Comment by xCss** [comment]
最主要是不报错，而且我这边也复现不了，这就不能定位到问题的具体位置，很尴尬~

**Comment by I-Info** [comment]
好吧，您用的是chrome canary吧，我又下过来试了试，发现没有出问题。。😂没有办法的话就等着chrome更新吧。。

**Comment by xCss** [comment]
@I-Info 我用dev版本试过了也没问题。。。!-_-
> 版本 83.0.4093.3（正式版本）dev （64 位）
