### ISSUE TITLE
新版edge发布评论会显示为chrome

### ISSUE THREAD

**Issue by Makysdd** [xCss/Valine#250]
- The steps to reproduce.
用新版edge在Valine发布评论后，会显示为chrome
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.

- Which versions of Valine, and which browser / OS are affected by this issue?
当前版本；egde+温10

**Comment by xCss** [comment]
Ok，收到，该已知Bug将在下个版本修复~
感谢反馈~

**Comment by xCss** [comment]
fixes in [v1.4.0](https://github.com/xCss/Valine/releases/tag/v1.4.0)
