### ISSUE TITLE
V1.4.0的一些问题

### ISSUE THREAD

**Issue by Linhk1606** [xCss/Valine#254]
好像最近你更新到了Valine V1.4.0(官网都没更🤣)

我发现一个UI的问题, 就是点击笑脸图案弹出Emoji选项后, 正常应该是再点一下收回去, 而这个版本没有实现, 点一下就不能再点了

还有一个, 就是验证码好像又不能用了

**Comment by xCss** [comment]
官网的v1.4.0版本是属于内测版本，目前正在优化一些体验上的问题，后续将推出更新

Emoji只能点开不能收回是已知问题，本地已解决，感谢反馈。

验证码将在下个版本中取消，改由`statusBar`上显示类似于`操作频繁`的提示消息。

**Comment by Linhk1606** [comment]
所以错误代码 `Code 140: code-140` 跟这个有关吗 <img class='emoji' src='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/tieba/滑稽.png'>

**Comment by Linhk1606** [comment]
确实, 在你的个人博客看到一堆的undefined

**Comment by xCss** [comment]
没错，`code 140`是提示`今日 API 调用总次数已超过开发版限制.`

哎，好烦躁啊，挤出个人时间来搞这个，还要被人搞
![image](https://user-images.githubusercontent.com/10877162/78501289-a923a100-778d-11ea-9311-e0166f4b7100.png)

**Comment by Linhk1606** [comment]
你可以弄垃圾评论检测(第三方的) https://github.com/DesertsP/Valine-Admin

**Comment by Linhk1606** [comment]
至少重复的内容会被过滤掉

**Comment by xCss** [comment]
哎，最终也逃不过真香警告~~
![image](https://user-images.githubusercontent.com/10877162/78501398-3a931300-778e-11ea-8529-c6270d01d4e4.png)

**Comment by Linhk1606** [comment]
还有, 打个广告, 推荐一个改版, 可以禁掉匿名评论 https://github.com/xaoxuu/volantis

**Comment by xCss** [comment]
哇哦w(ﾟДﾟ)w，厉害哟![image](https://user-images.githubusercontent.com/10877162/78501701-6662c880-778f-11ea-8c17-f94291791e26.png)，貌似很多人用啊~

我看jsdelivr引用超过100w [![](https://data.jsdelivr.com/v1/package/gh/xaoxuu/volantis/badge)](https://www.jsdelivr.com/package/gh/xaoxuu/volantis)

**Comment by xaoxuu** [comment]
我这改成必填项也只是勉强有一点点作用，有时候还是会收到昵称是 111 邮箱是 aaa 类似这样的评论。。。

**Comment by xaoxuu** [comment]
@Linhk1606 那个地址旧版的，不再更新了，因为主题用了这个名字，所以评论就放在主题的cdn仓库里面了。

**Comment by Linhk1606** [comment]
还有一个, 就是如果页面有加载MathJax, 则Valine会加载不出来, 浏览器会报错

```
Uncaught TypeError: Cannot read property 'Typeset' of undefined
    at e.exports (valine.js:1)
    at valine.js:1
    at valine.js:1
    at HTMLScriptElement.i.onload.i.onreadystatechange (valine.js:1)
```

在这里
```js
"undefined" != typeof MathJax && MathJax.Hub.Typeset(document.querySelector(".v"))
```

**Comment by xCss** [comment]
@Linhk1606 嗯，这个应该是我用了MathJax 2.x的渲染方式，而你加载的是3.x，我看看怎么处理这个问题~

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/78519844-1881ab00-77f7-11ea-8f59-dcc2e80e18f1.png)
好骚啊，把这么多表情都整合进去了

**Comment by Linhk1606** [comment]
<img class='emoji' src='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/tieba/滑稽.png'>

**Comment by xCss** [comment]
> ![](https://camo.githubusercontent.com/c70f65e2784dba976f60a8ea5a571863299a4dde/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f78616f7875752f63646e2d6173736574732f656d6f6a692f74696562612fe6bb91e7a8bd2e706e67)好像在GitHub上也占一行

github么有独占一行哦~

**Comment by Linhk1606** [comment]
> 哇哦w(ﾟДﾟ)w，厉害哟![image](https://user-images.githubusercontent.com/10877162/78501701-6662c880-778f-11ea-8c17-f94291791e26.png)，貌似很多人用啊~
> 
> 我看jsdelivr引用超过100w [![](https://camo.githubusercontent.com/f77ee6d5fe679a03c01133ca886b760bb2e0182c/68747470733a2f2f646174612e6a7364656c6976722e636f6d2f76312f7061636b6167652f67682f78616f7875752f766f6c616e7469732f6261646765)](https://www.jsdelivr.com/package/gh/xaoxuu/volantis)

那是因为@xaoxuu有个[美丽的hexo主题(就是我用的)](https://github.com/xaoxuu/hexo-theme-volantis) , 有很多人用, 而 Valine 的这个改版是~~捆绑安装~~自带 的 <img class='emoji' src='https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/tieba/滑稽.png'>

**Comment by xCss** [comment]
> > 哇哦w(ﾟДﾟ)w，厉害哟![image](https://user-images.githubusercontent.com/10877162/78501701-6662c880-778f-11ea-8c17-f94291791e26.png)，貌似很多人用啊~
> > 我看jsdelivr引用超过100w [![](https://camo.githubusercontent.com/f77ee6d5fe679a03c01133ca886b760bb2e0182c/68747470733a2f2f646174612e6a7364656c6976722e636f6d2f76312f7061636b6167652f67682f78616f7875752f766f6c616e7469732f6261646765)](https://www.jsdelivr.com/package/gh/xaoxuu/volantis)
> 
> 那是因为@xaoxuu有个[美丽的hexo主题(我也用了)](https://github.com/xaoxuu/hexo-theme-volantis) , 有很多人用, 而 Valine 的这个改版是主题~捆绑安装~自带 的 ![](https://camo.githubusercontent.com/c70f65e2784dba976f60a8ea5a571863299a4dde/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f78616f7875752f63646e2d6173736574732f656d6f6a692f74696562612fe6bb91e7a8bd2e706e67)

牛皮，牛皮，膜拜大佬 ![image](https://user-images.githubusercontent.com/10877162/78520483-4b2ca300-77f9-11ea-8d10-e57f61e109fd.png)

**Comment by MHuiG** [comment]
MathJax 和 markdown 渲染冲突 (吐血)

**Comment by MHuiG** [comment]
@xCss 

我在这个项目中配置math参数用以区分MathJax@2和MathJax@3.

或许你可以尝试一下

[https://github.com/MiniValine/MiniValine](https://github.com/MiniValine/MiniValine)

![image](https://user-images.githubusercontent.com/38281581/78540277-81344c00-7826-11ea-88d2-55c658865fef.png)

<blockquote><img src="https://avatars2.githubusercontent.com/u/62384464?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/MiniValine/MiniValine">MiniValine/MiniValine</a></strong></div><div>A simple and minimalist comment system based on Leancloud. - MiniValine/MiniValine</div></blockquote>

**Comment by xCss** [comment]
> @xCss
> 
> 我在这个项目中配置math参数用以区分MathJax@2和MathJax@3.
> 
> 或许你可以尝试一下
> 
> https://github.com/MiniValine/MiniValine
> 
> ![image](https://user-images.githubusercontent.com/38281581/78540277-81344c00-7826-11ea-88d2-55c658865fef.png)
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/62384464?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MiniValine/MiniValine](https://github.com/MiniValine/MiniValine)**A simple and minimalist comment system based on Leancloud. - MiniValine/MiniValine

没必要指定，可以直接判断MathJax版本号

**Comment by MHuiG** [comment]
> > @xCss
> > 我在这个项目中配置math参数用以区分MathJax@2和MathJax@3.
> > 或许你可以尝试一下
> > https://github.com/MiniValine/MiniValine
> > ![image](https://user-images.githubusercontent.com/38281581/78540277-81344c00-7826-11ea-88d2-55c658865fef.png)
> > > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/62384464?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[MiniValine/MiniValine](https://github.com/MiniValine/MiniValine)**A simple and minimalist comment system based on Leancloud. - MiniValine/MiniValine
> 
> 没必要指定，可以直接判断MathJax版本号

OK

**Comment by MHuiG** [comment]
MathJax.version.substr(0,1)

**Comment by MHuiG** [comment]
@xCss 不好意思刚刚没表述清楚
![image](https://user-images.githubusercontent.com/38281581/78543815-ca3acf00-782b-11ea-99fb-ea60fcd45bce.png)

**Comment by MHuiG** [comment]
@xCss V1.4.0似乎在IE中不工作

**Comment by lei2rock** [comment]
> 官网的v1.4.0版本是属于内测版本，目前正在优化一些体验上的问题，后续将推出更新
> 

原来还是内测啊，默默地已经开始在我博客使用了 https://github.com/lei2rock/blog/blob/3c1d77da96a765317889700c74fe989aeca2948c/_config.yml#L462

**Comment by MHuiG** [comment]
![image.png](https://imgkr.cn-bj.ufileos.com/0991bc9b-d104-44a8-a17a-4490a15b89fd.png)

@xCss 
```
inlineMath: [ ['$', '$'], ['\\(', '\\)'] ]
```
此处MathJax渲染和Markdown冲突

```
document.body.append(e)
```
这里不兼容IE

你可以参考我这里最新版本的代码
https://github.com/MiniValine/MiniValine/blob/master/src/utils/plugins/initMathJax2.js#L10
https://github.com/MiniValine/MiniValine/blob/master/src/utils/plugins/initMathJax2.js#L35

**Comment by MHuiG** [comment]
@xCss 加油

**Comment by xaoxuu** [comment]
@xCss  你好，我发现 1.4.0 之后，网页中拖拽一段文字或者一个按钮，就会把文字或者按钮标题填入输入框，1.3.10 中不存在这个问题。

**Comment by xCss** [comment]
@xaoxuu 嗯，内测版难免会出现各种问题，而且，拖拽文字进评论框应该也不属于Bug吧？

**Comment by xCss** [comment]
> ![image.png](https://camo.githubusercontent.com/b8c8c0fcccc81d63b42ebf70d26bbce3b34759d8/68747470733a2f2f696d676b722e636e2d626a2e7566696c656f732e636f6d2f30393931626339622d643130342d343461382d613137612d3434393061313562383966642e706e67)
> 
> @xCss
> 
> ```
> inlineMath: [ ['$', '$'], ['\\(', '\\)'] ]
> ```
> 
> 此处MathJax渲染和Markdown冲突
> 
> ```
> document.body.append(e)
> ```
> 
> 这里不兼容IE
> 
> 你可以参考我这里最新版本的代码
> https://github.com/MiniValine/MiniValine/blob/master/src/utils/plugins/initMathJax2.js#L10
> https://github.com/MiniValine/MiniValine/blob/master/src/utils/plugins/initMathJax2.js#L35

嗯，MathJax和Markdown冲突是已知问题，`append`在IE中的问题已收到~

**Comment by xaoxuu** [comment]
很影响体验的，我观看网页的时候选中了一段文字不小心多点了一下就跳到底下评论框了；一个按钮按下去又不想点了鼠标移走就又跳到评论框了。如果是 1.4.0 代码导致，的建议取消掉这个效果。

**Comment by MHuiG** [comment]
> @xCss 不是主动拖拽进评论框，而是只要发生了拖拽操作，就会跳到评论框。
> 
> 例如： https://valine.js.org/ 随便按住一个按钮或者图片移动一点点再松开。
> 
> 很影响体验的，我观看网页的时候选中了一段文字不小心多点了一下就跳到底下评论框了；一个按钮按下去又不想点了鼠标移走就又跳到评论框了。如果是 1.4.0 代码导致，的建议取消掉这个效果。
@xCss 
可能是这些代码导致的

```
    Utils.on('paste',document,(e)=>{
        let clipboardData = "clipboardData" in e ? e.clipboardData : (e.originalEvent && e.originalEvent.clipboardData || window.clipboardData)
        let items = clipboardData && clipboardData.items;
        let files = [];
        if (items && items.length>0) {
            // 检索剪切板items
            for (let i = 0; i < items.length; i++) {
                if (items[i].type.indexOf('image') !== -1) {
                    files.push(items[i].getAsFile());
                    break;
                }
            }
            if(files.length) {
                for(let idx in files){
                    let file = files[idx],
                        uploadText = `![Uploading ${file['name']}]()`;
                    _insertAtCaret(_veditor, uploadText);
                    file && uploadImage(file,function(err,ret){
                        if(!err && ret) _veditor.value = _veditor.value.replace(uploadText,`\r\n![${file['name']}](${ret['data']})`)
                    })
                }
            }
        }

    })
```

**Comment by xCss** [comment]
> @xCss 不是主动拖拽进评论框，而是只要发生了拖拽操作，就会跳到评论框。
> 
> 例如： https://valine.js.org/ 随便按住一个按钮或者图片移动一点点再松开。
> 
> 很影响体验的，我观看网页的时候选中了一段文字不小心多点了一下就跳到底下评论框了；一个按钮按下去又不想点了鼠标移走就又跳到评论框了。如果是 1.4.0 代码导致，的建议取消掉这个效果。

恩，了解了~

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/78845813-473c9300-7a3c-11ea-9307-6f6797bce3e3.png)

@xCss  它现在不兼容谷歌浏览器夜间模式

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/78846321-f29a1780-7a3d-11ea-828b-4b5298b4476a.png)

@xCss MathJax@3 配置有误

预期样式：
![image](https://user-images.githubusercontent.com/38281581/78846352-13fb0380-7a3e-11ea-993c-046ce9f9c088.png)

**Comment by MHuiG** [comment]
@xCss IE浏览器 emoji 无法正常加载

![image](https://user-images.githubusercontent.com/38281581/78846924-ef079000-7a3f-11ea-9733-f7b7cbdfe9b9.png)

**Comment by MHuiG** [comment]
@xCss 支持es6的浏览器无需请求polyfill.io

![image](https://user-images.githubusercontent.com/38281581/78847287-eebbc480-7a40-11ea-969f-8c688347a76e.png)

**Comment by MHuiG** [comment]
@xCss  记得遵守GPL规定

**Comment by MHuiG** [comment]
@xCss 
![image](https://user-images.githubusercontent.com/38281581/78851291-03ea2080-7a4c-11ea-809e-c3c74695e9f3.png)
![image](https://user-images.githubusercontent.com/38281581/78851306-0e0c1f00-7a4c-11ea-8f23-6eb0db66d010.png)

**Comment by MHuiG** [comment]
@xCss 太强了

**Comment by Linhk1606** [comment]
@MHuiG 你MiniValine也很强啊

**Comment by MHuiG** [comment]
问题又来了，如何不暴露appID，和appKey以保证安全？

**Comment by xCss** [comment]
@everyone, v1.4.0已更新
