### ISSUE TITLE
Hexo NexT中Valine评论区在标题为Valine的时候不显示

### ISSUE THREAD

**Issue by my0sotis** [xCss/Valine#255]
- 使用版本
```yaml
Hexo: 3.9.0
NexT: 7.3.0
Valine: 1.3.10
```
- 在使用NexT内置的Valine，修改CDN为
```yaml
valine: https://cdn.jsdelivr.net/npm/valine@1.3.10/dist/Valine.min.js
```
在博客中使用Valine作为标题的时候，如
```markdown
# Valine
```
Valine评论区会显示不出来，浏览器控制台会显示
```
Uncaught TypeError: Valine is not a constructor
    at (index):823
    at Object.getScript (utils.js?v=7.3.0:352)
    at (index):817
```
- 使用Valine作为标题的时候：[Demo](https://mlogs.top/2020/Valine1/)
- 不使用Valine作为标题的时候：[Demo](https://mlogs.top/2020/Valine2/)

**Comment by xCss** [comment]
dalao，你给个localhost给我有啥用？

**Comment by my0sotis** [comment]
sorry，刚才忘记部署上去了，现在好了

**Comment by xCss** [comment]
额，这个。。。看不出来是哪的问题，`Valine未定义`是主题里的`getScript`方法未工作造成的

**Comment by my0sotis** [comment]
好吧，谢谢你了，我升级一下Hexo和NexT好了

**Comment by stevenjoezhang** [comment]
```
# Valine
```
会生成一个 id 为 Valine 的元素，`window.Valine`获取到了这个元素（相当于`document.getElementById('Valine')`），而不是 Valine 插件的全局变量，由此导致了问题。
升级 Hexo 和 NexT 无法解决此问题。

**Comment by my0sotis** [comment]
> ```
> # Valine
> ```
> 
> 会生成一个 id 为 Valine 的元素，`window.Valine`获取到了这个元素（相当于`document.getElementById('Valine')`），而不是 Valine 插件的全局变量，由此导致了问题。
> 升级 Hexo 和 NexT 无法解决此问题。

噢！原来是这样，十分感谢！

**Comment by my0sotis** [comment]
> ```
> # Valine
> ```
> 会生成一个 id 为 Valine 的元素，`window.Valine`获取到了这个元素（相当于`document.getElementById('Valine')`），而不是 Valine 插件的全局变量，由此导致了问题。
> 升级 Hexo 和 NexT 无法解决此问题。

不好意思，还是有一个问题，我在NexT中文群中问了一下，他们可以使用Valine作为标题，同时也可以使用Valine的评论区

**Comment by stevenjoezhang** [comment]
这取决于你所使用的 Markdown renderer。你所使用的 Markdown renderer 为名为 `Valine` 的 h1 标题生成了 `id="Valine"`，所以报错。

**Comment by my0sotis** [comment]
> 这取决于你所使用的 Markdown renderer。你所使用的 Markdown renderer 为名为 `Valine` 的 h1 标题生成了 `id="Valine"`，所以报错。

但是我看了他生成的网页中，它标题的id也是为Valine，我们两的html完全一致，但是他的能够显示Valine的评论区

**Comment by stevenjoezhang** [comment]
那你问「他」吧，我就不浪费时间了。
