### ISSUE TITLE
v1.4 回复评论后不能立即显示，要刷新后才显示

### ISSUE THREAD

**Issue by lei2rock** [xCss/Valine#257]
在使用 Hexo 4.2.0 NexT 7.8.0 时候，回复评论后不能立即显示，要刷新页面才能显示，不论 PJAX 是否启用都存在该问题，过去版本不存在该问题。

源代码：https://github.com/lei2rock/blog
博客：https://blog.dlzhang.com

**Comment by xCss** [comment]
这是一个已知问题，内测版今日已解决，可以在官网测试 Valine.js.org

感谢反馈
