### ISSUE TITLE
v1.4.2, v1.4.1 will always stats plugin from hm.baidu.com

### ISSUE THREAD

**Issue by karuboniru** [xCss/Valine#258]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
  - Use Valine v1.4.2 in a website
  - press `<F12>` to check loaded resources
  - Found https://hm.baidu.com/hm.gif loaded
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
No need to publish a demo, `valine.js.org` is enough:
![image](https://user-images.githubusercontent.com/3437889/79034393-29ac2c80-7be8-11ea-88ec-038566012489.png)
- Which versions of Valine, and which browser / OS are affected by this issue?
any above v1.4.0
----
This maybe because you forget to remove your stats plugin before publishing.

**Comment by xCss** [comment]
Here's what I wanted to stat Valine user usage, so sorry if it's affecting you.

**Comment by xCss** [comment]
@karuboniru [v1.4.3](https://github.com/xCss/Valine/releases) It has been modified to send statistics once per version when it is first loaded.
