### ISSUE TITLE
建议在初始化的时候在配置中加入emoji链接

### ISSUE THREAD

**Issue by FFRaycoder** [xCss/Valine#260]
目前的emoji在js中已经指定好，建议像[DesertsP](https://github.com/DesertsP/Valine)的Valine一样可以在初始化时加入emoji链接和emoji array。

**Comment by MHuiG** [comment]
emoji array 可以删掉

**Comment by xCss** [comment]
新版[v1.4.5](https://github.com/xCss/Valine/releases/tag/v1.4.5)已支持自定义表情~

**Comment by FFRaycoder** [comment]
好的 已经看到了~
