### ISSUE TITLE
建议表情资源懒加载

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#261]
你好，1.4.2 表情资源是页面加载时全部加载的，建议改成懒加载模式。

效果参考链接： https://www.moonster.life/

这位博主所用主题的评论系统，表情库中的图片只有点开的时候才加载资源。

> 还有，~默认的表情感觉有点老了，我这里有一些新一点的表情 https://github.com/xaoxuu/cdn-assets/tree/master/emoji~ 建议您建一个仓库来存放这些表情😊

**Comment by xaoxuu** [comment]
也建议 image cdn 改为可配置，这样用户想自定义表情也很方便了

**Comment by SaraKale** [comment]
哇这个效果好！我最近也才发现好多人也用上了很可爱的表情包~到今天我才发现我的valine还停留在1.3.10……看了下Valine.min.js文件，好多要修改的样子，有些不敢乱魔改……
你说的image cdn这个我也赞同！希望后续版本增加个CDN设置~我们可以自己弄唷

**Comment by xaoxuu** [comment]
好棒 👍🏼

**Comment by xCss** [comment]
新版v1.4.5已发布，支持自定义表情~
