### ISSUE TITLE
这个没有定义是什么回事

### ISSUE THREAD

**Issue by Stephon-Xuan** [xCss/Valine#263]
Valine.min.js?b138:12 Uncaught (in promise) TypeError: Cannot read property 'catch' of undefined
    at eval (Valine.min.js?b138:12)

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/79042430-63058c00-7c2a-11ea-89e4-c0a31fe750a5.png)
@xCss 出来 deBug

**Comment by Mister-Hope** [comment]
我也遇到了这个问题，请问你找到原因了么？
