### ISSUE TITLE
通过源码 build 出的 js 报错 Cannot redefine property: applicationId

### ISSUE THREAD

**Issue by imaegoo** [xCss/Valine#266]
Hi, @xCss 

我想添加对昵称和邮箱的防空判断功能，所以我 clone 了 1.4.4 版本的代码，在未作修改直接编译时，得到的 `Valine.min.js` 大小为 230 KB，我留意到仓库中原本的 `Valine.min.js` 大小为 123 KB，我尝试使用我自己编译的 `Valine.min.js`，会得到这样的错误：

```
Valine.min.js:26 Uncaught TypeError: Cannot redefine property: applicationId
    at Function.defineProperty (<anonymous>)
    at Valine.min.js:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (Valine.min.js:26)
    at t (Valine.min.js:12)
    at Object.<anonymous> (Valine.min.js:19)
    at t (Valine.min.js:12)
    at Valine.min.js:12
    at Valine.min.js:12
    at Valine.min.js:12
```

使用官方的 `Valine.min.js` 不会出现这样的错误。

我在项目中未搜索到任何 `applicationId` 关键字，我猜想和编译环境有关。

我尝试在 2 种环境下编译，编译的命令都是 `npm install` 和 `npm run build`，都得到了 200 KB+ 的文件：

环境1：Windows 10 & node v13.1.0 & npm 6.12.1
环境2：Ubuntu 16 & node v12.16.1 & npm 6.13.4

附上我在环境2编译得到的文件，请您参考：[Valine.min.js.zip](https://github.com/xCss/Valine/files/4465052/Valine.min.js.zip)

我查看了 Documentation 和 README，但是并未找到项目如何编译的描述，我该怎么做？

Thanks,
iMaeGoo

**Comment by imaegoo** [comment]
我试着切换至 1.3.10 版本编译，编译出的 js 可以正常使用，然后我添加了自己想要的功能，也能正常工作，请问 1.4 是否需要修改某些文件（如 `webpack.config.js`）才能正常编译？

**Comment by MHuiG** [comment]
事实上，你 clone 的是 1.4.0 - bate 版本的代码

1.4.4 并没有开源

**Comment by imaegoo** [comment]
From xCss:

> 由于某些原因，`src目录`将从`v1.4.0`后暂停更新.  
  For some reason, the `src directory` will be suspended from updating after `v1.4.0`.
