### ISSUE TITLE
MathJax in comment may not render when using `\require`

### ISSUE THREAD

**Issue by karuboniru** [xCss/Valine#268]
- The steps to reproduce.
 use MathJax 3 in website, and comment as following:
  ```
  $$
  \require{physics}
  \bra{1}\ket{2}
  $$
  ```
  preview may work, but comment itself will not be rendered after a refresh.
- DEMO: after reloading:
![image](https://user-images.githubusercontent.com/3437889/79067793-8d238080-7cf4-11ea-902f-c25d7254a33e.png)

- Which versions of Valine, and which browser / OS are affected by this issue?
1.4.4 with MathJax 3

-----
In [MathJax's documents](http://docs.mathjax.org/en/latest/advanced/typeset.html), we should use `MathJax.typesetPromise()` to do math typeset in MathJax 3 instead of `MathJax.typeset()` in dynamic content.  `MathJax.typeset()` will not work properly with `\require` or autoload. 

useful information
- http://docs.mathjax.org/en/latest/web/typeset.html#typeset-async
- http://docs.mathjax.org/en/latest/advanced/typeset.html

**Comment by xCss** [comment]
Ok, the issue will be fixed in the next version, Thx!

**Comment by xCss** [comment]
@karuboniru Sorry, after troubleshooting, the rendering error issue is not a `Valine`, but a `MathJax` configuration parameter issue on the page.

`Valine` itself does not do any additional resource file loading of `MathJax`, it only checks if the page is loaded and `MathJax` is loaded.

Here is the previous configuration:
``` js
      window['MathJax'] = {
          tex: {
            inlineMath: [ [ ['$','$']],
          },
          svg: {
            fontCache: 'global'
          }
      };
````

Modified configuration:
```js
      window['MathJax'] = {
          tex: {
            inlineMath: [ [ ['$','$']],
            autoload: {
                verb: ['verb'],
                COLOR: [],
                colorV2: ['color'],
                require: ['require']
            },
            packages: {'[+]': ['braket']}
          },
        loader: {load: ['[tex]/braket']},
          svg: {
            fontCache: 'global'
          }
      };
````
Now the [Valine website](https://valine.js.org) is able to render `MathJax` correctly, please try it, thanks for your feedback!

**Comment by karuboniru** [comment]
Specifying package is a workaround here, but MathJax is designed to be able to load extensions by `\require` or autoload.

Actually same Tex code, if presented in static HTML file, will render properly without specifying loading braket in MathJax's configuration. (But valine comments aren't static contents, they are dynamic, according to MathJax's documentation, async typesetting is needed for dynamic contents)

There can be a situation where the website itself didn't load certain package, while the user who comment want to use that package.

But it is a rare situation, maybe fine to left it unfixed.

**Comment by xCss** [comment]
Well, so far I have not found a better way to solve this problem, even with `MathJax.typesetPromise()`.
