### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by HTC-Group** [xCss/Valine#270]
我原本valine版本1.3.4在评论区代码高亮正常，

现在升级到1.4.4后代码高亮不显示，与hljs冲突。

具体而言1.4.4后html代码如下：
```html
<code class="language-cpp hljs">
     <span style="color: #23AC69">
               <span class="hljs-keyword">
                      <span class="hljs-keyword">int</span>
               </span>
      </span>
</code>
```
从而代码不高亮，请问一下有没有解决方案。

**Comment by xCss** [comment]
这是因为你的页面加引入了[highlightjs](https://highlightjs.org/)

建议你初始化Valine的时候设置代码高亮关闭试试:
``` js
new Valine({
   // ...
   highlight: false
})
```

**Comment by HTC-Group** [comment]
非常感谢作者大大的回复，我尝试关闭`highligt`后，渲染框架是正常的，但是这层颜色渲染好像被valine的默认配色覆盖了，仍然没有高亮，请问一下如何解决。（另：我蛮好奇为啥1.3.4版本不会引起冲突

**Comment by xCss** [comment]
因为在1.3.4的时候，没有正确检测`highlightjs`，造成渲染失败，所以使用的是Valine自带的高亮模块。

在1.4.x版本更改了检测方式，能够正确检测是否已加载`highlightjs`。

---------------

刚刚看了下，颜色被覆盖是属于`Valine`的`Bug`，将在下个版本中修复，感谢你的反馈~~

**Comment by HTC-Group** [comment]
我发现了新的问题了，不知道是不是和这个一样的问题。我如果一个页面有hljs渲染的代码框，在有valine评论的情况下高亮会消失，就拿我自己的博客举例：

[有valine的评论](https://enderturtle.gitee.io/2020/04/01/ZJOI2015-%E5%B9%BB%E6%83%B3%E4%B9%A1%E6%88%98%E7%95%A5%E6%B8%B8%E6%88%8F/)

[无valine的评论](https://enderturtle.gitee.io/2020/04/01/ZJOI2007-%E6%8D%89%E8%BF%B7%E8%97%8F/)

**Comment by xCss** [comment]
@HTC-Group 刚看了下，发现并不是`Valine`的样式影响，而有点像是受`hljs`代码块`注释样式`影响。

**Comment by HTC-Group** [comment]
我也觉得是`hljs-comment`的影响，不知道有没有解决方案，仍然是以前版本的valine不受影响，这个版本我也把`highlight`改成`false`了。

**Comment by xCss** [comment]
@HTC-Group 试下试下，新版发布了，理论上解决了这个问题~

**Comment by HTC-Group** [comment]
@xCss 啊，非常感谢作者大大付出，我恰完饭试一下实装

**Comment by HTC-Group** [comment]
@xCss emmm，我实装之后评论区代码高亮已经没有问题了，但还是只要有评论，文章里的高亮还是会消失，请问一下如何解决

**Comment by HTC-Group** [comment]
1.4.6已修好，谢谢作者的肝

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/79936332-c1800500-8489-11ea-9a93-f13bc79cabf5.png)
