### ISSUE TITLE
阅读次数在主页显示异常

### ISSUE THREAD

**Issue by Geniucker** [xCss/Valine#272]
更新到1.4.4后（Hexo NexT主题）使用Valine的文章阅读次数统计，文章只要标题含有中文在主页阅读次数就显示0，点进去以后显示正常，标题为纯英文无影响，换回1.3.10的js表现正常，在chromium内核的浏览器上似乎都这样，别的没有测试
demo: <https://geniucker.cf>前两篇文章中英文对比

**Comment by xCss** [comment]
@Geniucker Ok，收到，这个是已知Bug，将在下个版本中修复，感谢反馈~

**Comment by Geniucker** [comment]
作者加油![](https://cdn.jsdelivr.net/gh/geniucker/source/emoji/%E5%87%BB%E6%8E%8C.png)

**Comment by xCss** [comment]
@Geniucker 新版已发布，理论上已经解决了该问题，麻烦请测试并反馈，感谢~

**Comment by yummymath** [comment]
> @Geniucker 新版已发布，理论上已经解决了该问题，麻烦请测试并反馈，感谢~

作者大大您好，我在自己基于 jekyll 的博客里引入了 Valine 统计工具，也出现了「首页」不显示访问量的问题。

https://yummymath.gitee.io/index.html

看到您已更新，但是我们普通用户对 Valine 的引用，是简单的 JS 脚本引入，求问如何用上您的修复？

**Comment by xCss** [comment]
v1.4.8已修复，感谢反馈

**Comment by Geniucker** [comment]
> @Geniucker 新版已发布，理论上已经解决了该问题，麻烦请测试并反馈，感谢~

已测试，正常
