### ISSUE TITLE
触发表情包标签的bug

### ISSUE THREAD

**Issue by cungudafa** [xCss/Valine#275]
![image](https://user-images.githubusercontent.com/34543897/79569703-b1170580-80ea-11ea-8a53-df71b8c99093.png)
如图，英文双冒号间的内容都会识别为图片，望修改！tks

**Comment by xCss** [comment]
新版[v1.4.5](https://github.com/xCss/Valine/releases/tag/v1.4.5)已发布，修复了这个问题，感谢反馈~
