### ISSUE TITLE
请问有没有支持“评论先审核后显示”的功能的可能

### ISSUE THREAD

**Issue by UdUklm** [xCss/Valine#276]
**摘要**：我的网站在中国大陆备案，最新的等级保护 2.0 要求网站评论需要**先审核后显示**。不知 Valine 有没有可能支持该功能。

我本打算在 Valine 的项目上二次开发，配合我自己的后端程序实现。奈何我我对前端技术不太熟悉😭

假如继续使用 LeadCloud 的话可能审核的体验不会太好，感觉 LeadCloud 的移动端网页体验不太好。不用第三方存储的话好像整个项目要改动的地方又有点多。我原本打算二次开发 Valine 并自己开发后端程序，审核使用后端提供的管理界面。但是我看了看 Valine 的源代码感觉改起来可能有些吃力，之前没怎么接触过 js 代码。

不知道有没有可能支持一下先审核后显示的功能呢？哪怕是基于 LeanCloud 的。当然这也可能导致数据不互通的问题。

期待回复，谢谢 😃

**Comment by imaegoo** [comment]
Valine-Admin 应该做得到

https://github.com/DesertsP/Valine-Admin

变量 | 示例 | 说明
--- | ------ | ------
AKISMET_KEY | xxxxxxxxxxxx | [可选]Akismet Key 用于垃圾评论检测，设为MANUAL_REVIEW开启人工审核，留空不使用反垃圾

**Comment by UdUklm** [comment]
我自己在 Valine 的基础上开发了有**先审核再显示**功能的评论系统 NeoValine：[https://github.com/UdUklm/NeoValine](https://github.com/UdUklm/NeoValine)。当然这个评论系统需要部署配套开发的后端程序，所以需要自己拥有服务器才可以使用。

Valine-Admin 满足不了需求的小伙伴可以试一下😃

 我的网站已经上线了这套评论系统，欢迎尝试：

[NeoValine：一个基于 Valine 开发的支持人工审核的评论系统](https://www.ohmysites.com/archives/15/)

**Comment by alwxkxk** [comment]
我修改了min.js里的代码（v1.4.14），判断字段approval为ture时才会显示评论内容，而false时显示 “该评论等审批后才会显示~”。 然后到leanCloud添加字段approval，默认值为false即可。

链接：https://pan.baidu.com/s/1Q338CrGJWi6mQfmFinx5Fg 
提取码：vywp

**Comment by xunge0613** [comment]
参考了楼上几位大佬的分享， [NeoValine：一个基于 Valine 开发的支持人工审核的评论系统](https://www.ohmysites.com/archives/15/) 、[Valine-Admin](https://github.com/DesertsP/Valine-Admin)、[alwxkxk](https://github.com/xCss/Valine/issues/276#issuecomment-640048814)，我也做了一个基于 Valine 二次开发，具有有先审核再显示功能的评论系统：[XValine](https://github.com/xunge0613/XValine)

主要特点

- 支持预定义关键词屏蔽（昵称、评论内容）
- 支持人工审核（兼容普通 LeanCloud 管理和 Valine-Admin 管理）
