### ISSUE TITLE
建议在配置项里添加是否开启QQ邮箱或进行验证

### ISSUE THREAD

**Issue by FFRaycoder** [xCss/Valine#277]
如题，开启后无法使用loli.net的gravatar了，尤其是自定义的域名邮箱。

**Comment by xCss** [comment]
## enableQQ
- 类型: `Boolean`
- 默认值: `false`
- 必要性: `false`

是否启用`昵称框`自动获取`QQ昵称`和`QQ头像`, 默认关闭，需`博/网站主`主动启用 

-----------------
`v1.4.6`将新增这个属性

**Comment by FFRaycoder** [comment]
好的
