### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by xiyizhou** [xCss/Valine#278]
V1.4.4 -1.4.5
评论框输入以下以下评论内容不能显示在评论区
---

> 亲爱的小伙伴：我站信息更换啦~
> 原来的www.cunzher.top
> 更换站点信息：
> 名称：非常医学生
> 头像链接：https://ypcdnsave.cunzher.cn/img/logo.png
> 主页链接：https://www.cunzher.cn
> 说明信息[英]：Viewing life with medical ethics.
> 说明信息[中]：以医德观人生。
> 谢谢~~

**Comment by xCss** [comment]
请确认留言的博客是否使用了 https://github.com/DesertsP/Valine-Admin ，并开启了垃圾过滤

我这边用Valine-Admin测试，是直接被判断为垃圾评论了。
