### ISSUE TITLE
Gatsbyjs 博客如何使用 Valine

### ISSUE THREAD

**Issue by xiyizhou** [xCss/Valine#279]
RT

**Comment by FFRaycoder** [comment]
这个一样是插入代码啊，只是要看看GATSBY的模板位置了

**Comment by xiyizhou** [comment]
> 这个一样是插入代码啊，只是要看看GATSBY的模板位置了

直接插入不管用~~只有第一次或第一个页面加载，其余不加载

**Comment by FFRaycoder** [comment]
> > 这个一样是插入代码啊，只是要看看GATSBY的模板位置了
> 
> 直接插入不管用~~只有第一次或第一个页面加载评论框，其余不加载

我不了解Gatsby，是单页面应用吗？

**Comment by wizcas** [comment]
简单来说只要新建一个Component，在组件`componentDidMount()`中初始化Valine插件就可以了。然后把这个组件加到你的博客文章页面里，在每个文章页面都可以显示的。

我刚才在我新搭的博客上做了一下没有问题，已经成功部署了，写了一篇笔记可供参考~欢迎指教：

[在Gatsby页面中集成Valine评论系统](https://0x1c.dev/blog/apply-valine-in-gatsby/)

**Comment by xiyizhou** [comment]
建议 @xCss  考虑把 @wizcas 的方案 纳入官方技术文档

**Comment by xiyizhou** [comment]
> 简单来说只要新建一个Component，在组件`componentDidMount()`中初始化Valine插件就可以了。然后把这个组件加到你的博客文章页面里，在每个文章页面都可以显示的。
> 
> 我刚才在我新搭的博客上做了一下没有问题，已经成功部署了，写了一篇笔记可供参考~欢迎指教：
> 
> [在Gatsby页面中集成Valine评论系统](https://0x1c.dev/blog/apply-valine-in-gatsby/)

建议 @xCss 可否把 @wizcas 的方法纳入官方技术文档。

**Comment by wizcas** [comment]
@xiyizhou 考虑了一下我决定把这个方案做成一个gatsby插件，正在着手做，弄好了以后我可以提个PR到Vaine的文档中😄️

**Comment by wizcas** [comment]
@xiyizhou 插件已经发布，可以直接使用。@xCss希望可以把文档PR合并进官方文档~
