### ISSUE TITLE
邮件提示功能到底怎么配置才能生效啊

### ISSUE THREAD

**Issue by codefine** [xCss/Valine#28]
如题。。。

**Comment by xCss** [comment]
参考：https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE

**Comment by codefine** [comment]
我是完全按照这个设置的，并没有用啊。。。

**Comment by xCss** [comment]
@codefine  http://blog.lujingtao.com/2017/11/20/hexo-theme/#comment  
![tim 20171124105400](https://user-images.githubusercontent.com/10877162/33193775-d0832b66-d105-11e7-972b-7bfe9c9b3753.png)

**Comment by codefine** [comment]
这是什么情况 没看懂

**Comment by xCss** [comment]
这说明评论被回复的邮件提醒是成功的啊~

**Comment by codefine** [comment]
那为啥我的qq邮箱里没有邮件提示啊，你这个截图是从哪里看到的？

**Comment by xCss** [comment]
这是我的QQ邮箱啊。。。
我自己回复我自己，然后我收到的邮件提醒啊~

**Comment by codefine** [comment]
那别人在我的文章下评论，我没收到邮件，就说明我还是没设置正确，是吗？

**Comment by xCss** [comment]
文章评论时没有邮件提醒的。
只有在回复当前已存在的评论时，才会发送邮件提醒。

**Comment by codefine** [comment]
我收到了，我知道了。必须得@我，我才能收到。

**Comment by codefine** [comment]
亲爱的作者，你看这个是不是不太人性化。
按理来说只要是别人评论，我就应该能收到才对呀。这样我才能及时回复。
别人第一次评论的时候一般并不会@博主。

**Comment by xCss** [comment]
不是@ ，是回复。
哦，也相当于@ 吧。
只有被回复楼层存在邮箱，如果开启了提醒才会发送。
---------
抱歉。我当初也想过回复帖子给博主发提醒。结果发现需要设置博主的邮箱才行，然后就取掉了这步。

**Comment by codefine** [comment]
那是不是可以这样呢：
在config.yml中留个接口，设置博主邮箱。
然后在你的js文件里应该是可以获取到的。

**Comment by xCss** [comment]
这么做是可以的。
不过因为leancloud的限制，链接并不能到达指定文章页。所以这么做貌似也没什么必要？

**Comment by codefine** [comment]
那至少别人留言了，咱们能立刻知道呀。
其实你在暴露首页评论数接口之后，那个评论数对于博主而言是非常容易记住的。
就算不能到达指定文章页，也能很容易发现是哪个文章有了新评论。
尤其是对于我这种有问必答类型的，基本上单数就是有新评论，偶数就是没有。
要不要考虑一下？

**Comment by codefine** [comment]
然后我可以在我主题中写入类似如下的逻辑：

判断留言板中第一个li中的vname的innerHTML。
如果不是我的话，我就可以在主页中置顶该文章。

这样我也可以很轻易的锁定新留言的文章了。

**Comment by xCss** [comment]
emmm...

大概可以，我找个时间更新下吧~。

-------

对于你说的判断留言板中的第一个li，我觉得应该是没效果的。
因为你判断是需要html中存在，而我的li是动态生成插入的。

**Comment by codefine** [comment]
嗯，辛苦了辛苦了~

---

这个没关系，置顶做不成的话，我也可以监听dom的变化，写个tips之类的东西。

总之前提是得有完全的评论提醒的功能，后面的需求我可以换着花样实现嘛，哈哈哈。

**Comment by codefine** [comment]
点错了，等你实现了再关闭吧~

**Comment by APPLLEJN** [comment]
请问下这个功能现在有了么？ @xCss
