### ISSUE TITLE
是否可以增加一个博主标识

### ISSUE THREAD

**Issue by a1401358759** [xCss/Valine#280]
是否可以增加一个博主标识 比如通过邮箱判断是否是博主

**Comment by xaoxuu** [comment]
同求

**Comment by MHuiG** [comment]
同求

**Comment by Linhk1606** [comment]
同求啊

**Comment by Linhk1606** [comment]
https://gitee.com/lovelijunyi/mycode/blob/master/Valine.min.js

效果 https://blog.lhkstudio.me/about/#comments

**Comment by MHuiG** [comment]
> https://gitee.com/lovelijunyi/mycode/blob/master/Valine.min.js
> 
> 效果 https://blog.lhkstudio.me/about/#comments

一会儿去换
