### ISSUE TITLE
昵称或QQ号

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#282]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

输入qq号显示qq头像和昵称、qq邮箱这个特性太棒了，但是用户可能不知道，所以建议昵称栏占位文字改成 “昵称或QQ号” 

如果觉得这样不美观的话，可以在昵称输入框focus的时候占位文字改成 “昵称或QQ号” 。

**Comment by xCss** [comment]
如果改成`昵称或QQ`，那将和 #277 冲突

**Comment by xaoxuu** [comment]
如果加了配置项，根据配置来显示占位文字可以吗？或者干脆把占位文字开放配置

```yaml
meta:
  nick: 昵称
  mail: 邮箱
  link: 网址
```

**Comment by xCss** [comment]
现在本身就是开放的，用`自定义语言`可以实现`自定义占位符提示`

**Comment by xaoxuu** [comment]
了解 👌

**Comment by Zhangyue168** [comment]
输入QQ号后，能获取到头像和邮箱，但无法获取到昵称是什么情况呢？
