### ISSUE TITLE
配色又变了吗,,, 能否支持dark mode

### ISSUE THREAD

**Issue by Litreily** [xCss/Valine#283]
[我的博客](https://www.litreily.top/about/)使用的是本人写的黑色系主题，配上新的valine样式显得很奇怪，之前更新了valine后是自己修改css匹配的，但是最近貌似又更新了其它样式，虽然可以自己修改解决，但是每次这么整也好麻烦啊
所以可否支持两种样式，dark mode, 和light mode, 给个选项进行配置？

**Comment by FFRaycoder** [comment]
这个已经增加了，适用于浏览器黑色模式 :smirk:

**Comment by xCss** [comment]
@Litreily 你的页面中的`body`加个`night`样式试试:
``` html
<body class="night">
    <!--your other code-->
</body>
```

**Comment by Litreily** [comment]
@xCss 感谢，可用，但是和主题还是不是很搭，又稍加修改了下，哈哈

**Comment by Litreily** [comment]
发现个小问题，night 模式下，浏览器类型部分的`vhead vsys`的字体颜色和评论区正文一样，能否将正文部分的调亮一些呢，谢谢
预览地址：https://www.litreily.top/about/

**Comment by xCss** [comment]
@Litreily 抱歉，这个就需要博主自己去调了，毕竟Valine不能针对每个颜色都适配一遍

**Comment by Litreily** [comment]
> @Litreily 抱歉，这个就需要博主自己去调了，毕竟Valine不能针对每个颜色都适配一遍

这个我知道，但是我看light模式下，这两处的颜色是不一样的，可以形成对比，dark mode使用的却是一样的。 thanks any way.

**Comment by xCss** [comment]
@Litreily OK，了解了

**Comment by xCss** [comment]
@Litreily 新版已稍作修改。感谢反馈
