### ISSUE TITLE
文档里面的Valine样式和主题CSS冲突，Valine自己的CSS没了

### ISSUE THREAD

**Issue by FFRaycoder** [xCss/Valine#284]
文档里面的Valine样式和主题CSS冲突，Valine自己的CSS没了。
![image](https://user-images.githubusercontent.com/58381667/79929018-15cdb980-8477-11ea-8c4c-13e875b1073d.png)

**Comment by xCss** [comment]
抱歉哦，github的图片看不到，能用第三方图床留图，感谢~

**Comment by FFRaycoder** [comment]
https://proxy.raycoder.me/-----https://user-images.githubusercontent.com/58381667/79929018-15cdb980-8477-11ea-8c4c-13e875b1073d.png

**Comment by FFRaycoder** [comment]
一个代理，应该可以了吧~

**Comment by xCss** [comment]
OK，收到，感谢反馈~

**Comment by xCss** [comment]
v1.4.6 已修复，感谢反馈

**Comment by FFRaycoder** [comment]
抱歉，还没有修复，还是被覆盖了！
