### ISSUE TITLE
新版本的使用旧版本av-min.js仍初始化失败

### ISSUE THREAD

**Issue by shingkit** [xCss/Valine#285]
用的主题是[maupassant](https://github.com/tufu9441/maupassant-hexo)，使用的是1.4.7的Valine。
```
    script(src='//cdn1.lncld.net/static/js/3.0.4/av-min.js')
    script(src='//unpkg.com/valine@latest/dist/Valine.min.js')
```
 报错信息：
```
Code 98: Valine 初始化失败，请检查 av-min.js 版本
```

**Comment by xCss** [comment]
你好，感谢反馈，有可复现错误的预览地址吗，我需要定位详细错误~

**Comment by shingkit** [comment]
可以用我的[博客](https://shingkit.me/2020-04-19/cocos-sprite-or-imageview.html)调

**Comment by HTC-Group** [comment]
> 可以用我的[博客](https://shingkit.me/2020-04-19/cocos-sprite-or-imageview.html)调

emm，你是不是你的博客本身有引用av-min啊，如果是的话删掉那句就好了

**Comment by xCss** [comment]
@HTC-Group @shingkit 虽然删除`av-min.js`可以解决问题，但实际上也是属于Valine的问题，我已定位到问题所在，将在下个版本修复，感谢反馈 :smile:

**Comment by wmjtxt** [comment]
mark,同样的问题

**Comment by xCss** [comment]
新版 v1.4.8已修复，感谢反馈~
