### ISSUE TITLE
表情判断逻辑仍有漏洞

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#286]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

输入下面的格式就不会显示表情
```
表情:测试1 :smile:
```

建议增加一对符号来判断，双冒号太容易误判了。

例如：
```
[:smile:]
```
或者：
```
(:smile:)
```

**Comment by MHuiG** [comment]
@xCss  昨天有日语大佬过来改我的翻译，你看看顺便把你的翻译也给改了。

https://github.com/MiniValine/minivaline-i18n/blob/master/ja-JP/index.json

**Comment by Linhk1606** [comment]
应该学习MiniValine的判断逻辑, 如`!(:抖眼.gif:)`

**Comment by Linhk1606** [comment]
括号外面再加特殊字符

**Comment by Linhk1606** [comment]
而且评论时写行内代码, 即` `` `时表情也会失效

**Comment by MHuiG** [comment]
> 而且评论时写行内代码, 即`` `` ``时表情也会失效

Valine专业测试团队
<img width="82" alt="0450" src="https://user-images.githubusercontent.com/38281581/80201467-c0e89980-8656-11ea-9e0e-b9071e0a37f8.png">

**Comment by Linhk1606** [comment]
哦对了, 显然连输两个`https:`开头的网址也会报错

反正用冒号很不靠谱啦

**Comment by MHuiG** [comment]
> 哦对了, 显然连输两个`https:`开头的网址也会报错
> 
> 反正用冒号很不靠谱啦

然而Github这个评论框就用了冒号 :rocket:

```
:rocket:
```

**Comment by Linhk1606** [comment]
> > 哦对了, 显然连输两个`https:`开头的网址也会报错
> > 反正用冒号很不靠谱啦
> 
> 然而Github这个评论框就用了冒号 🚀
> 
> ```
> :rocket:
> ```

那你可以用正则搞一下, 如果出现非法字符(标点符号, 空格和大写字母)就不判断为emoji

**Comment by Linhk1606** [comment]
还有, 我换Gitalk了

**Comment by MHuiG** [comment]
> 还有, 我换Gitalk了

Gitalk 国内网络不稳定，我从Gitalk换到Valine 最后自己搞了一套MiniValine，最近换主题感觉MV和主题不搭又换回Valine，哈哈~

**Comment by Linhk1606** [comment]
> > 还有, 我换Gitalk了
> 
> Gitalk 国内网络不稳定，我从Gitalk换到Valine 最后自己搞了一套MiniValine，最近换主题感觉MV和主题不搭又换回Valine，哈哈~

http://googlehelper.net/

**Comment by MHuiG** [comment]
> > > 还有, 我换Gitalk了
> > 
> > 
> > Gitalk 国内网络不稳定，我从Gitalk换到Valine 最后自己搞了一套MiniValine，最近换主题感觉MV和主题不搭又换回Valine，哈哈~
> 
> http://googlehelper.net/

Got it!!

**Comment by xaoxuu** [comment]
gitalk太慢了

**Comment by MHuiG** [comment]
> gitalk太慢了，而且最老的评论排序在最上面，几年过去了还这样……

gitalk代码是开源的，给gitalk作者提Issue 发PR 

https://github.com/gitalk/gitalk

**Comment by Linhk1606** [comment]
@xaoxuu 你的主题是自带Gitalk吗? 我能不能手动用npm更新

**Comment by Linhk1606** [comment]
> gitalk太慢了，而且最老的评论排序在最上面，几年过去了还这样……

没有啊 https://blog.lhkstudio.me/about/
记得清除缓存, 不然你看到的是Valine🤣

**Comment by MHuiG** [comment]
> > 还有, 我换Gitalk了
> 
> Gitalk 国内网络不稳定，我从Gitalk换到Valine 最后自己搞了一套MiniValine，最近换主题感觉MV和主题不搭又换回Valine，哈哈~

现已换回Gitalk，成功回到起点

<img width="109" alt="5150" src="https://user-images.githubusercontent.com/38281581/80276410-459ceb80-871b-11ea-8c77-eebf7acae44e.png">

和Valine作者道别，近期不会再来了，说真的还有点不舍。

<img width="112" alt="5000" src="https://user-images.githubusercontent.com/38281581/80276425-5c434280-871b-11ea-9299-245514e2cb16.png">
 
最后，膜拜大佬。

**Comment by xCss** [comment]
v1.4.10 已修复，感谢反馈

**Comment by Linhk1606** [comment]
👍那我是不是又要换回来了

**Comment by MHuiG** [comment]
> 👍那我是不是又要换回来了

等漏洞补上再换吧

https://github.com/xCss/Valine/issues/298
