### ISSUE TITLE
评论区与阅读次数冲突无法正常显示

### ISSUE THREAD

**Issue by heibai23** [xCss/Valine#287]
> 页面提示：Code 98: Valine 初始化失败，请检查 av-min.js 版本。
我把引入的av-min.js 注释掉，评论区出来了，但是阅读次数又无法正常显示数字
如果使用其他的av-min.js，也是一个可以，一个不行

+ 版本：hexo: 4.2.0 next主题

**Comment by xCss** [comment]
可以关掉主题自带的`leancloud_visitor`，然后开启Valine中`visitors`再试。

`Code 98: Valine 初始化失败，请检查 av-min.js 版本。`属于当前版本`v1.4.7`的Bug，将在下个版本修复

**Comment by wbqzsl** [comment]
我的也是这个问题，还有那个next不是集成了valine吗，从哪里注释掉引入的av-min.js 
555555555

**Comment by wbqzsl** [comment]
更奇怪的是我明明没有动valine这一块，他就突然不行了。关于脚本的操作就是我装了一个百度的主动提交插件然后remove了，莫非是remove依赖了av-min.js ?

**Comment by heibai23** [comment]
> 下个



> 我的也是这个问题，还有那个next不是集成了valine吗，从哪里注释掉引入的av-min.js
> 555555555
在主题文件加下的valine.swig里
目录：layout\_third-party\comments\valine.swig

**Comment by heibai23** [comment]
> 更奇怪的是我明明没有动valine这一块，他就突然不行了。关于脚本的操作就是我装了一个百度的主动提交插件然后remove了，莫非是remove依赖了av-min.js ?

我也是突然不行了，在这之前的操作我是把leancloud里的记录删掉了。现在是阅读次数和评论会有一个不行

**Comment by heibai23** [comment]
> 可以关掉主题自带的`leancloud_visitor`，然后开启Valine中`visitors`再试。
> 
> `Code 98: Valine 初始化失败，请检查 av-min.js 版本。`属于当前版本`v1.4.7`的Bug，将在下个版本修复
> 
> #285

把lean的visitors关掉后，页面直接不显示阅读次数了。单独开始在new Valine中添加visitor:true  ？加了无效

**Comment by wbqzsl** [comment]
> > 下个
> 
> > 我的也是这个问题，还有那个next不是集成了valine吗，从哪里注释掉引入的av-min.js
> > 555555555
> 
> 在主题文件加下的valine.swig里
> 目录：layout_third-party\comments\valine.swig

谢了谢了，我的注释掉文件第二行的<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>就可以正常使用了。

**Comment by wbqzsl** [comment]
> 可以关掉主题自带的`leancloud_visitor`，然后开启Valine中`visitors`再试。
> 
> `Code 98: Valine 初始化失败，请检查 av-min.js 版本。`属于当前版本`v1.4.7`的Bug，将在下个版本修复
> 
> #285

我的leancloud_visitor计数功能并没有开，却依旧遇到了这个问题。

**Comment by xCss** [comment]
@heibai23 @wbqzsl 新版已发布，修复了code 98问题，感谢反馈
