### ISSUE TITLE
v1.4.7版本的av-min.js问题

### ISSUE THREAD

**Issue by hardcodeape** [xCss/Valine#288]
#### 在hexo-yilia主题下Valine v1.4.7版本的问题
![image](https://user-images.githubusercontent.com/50048882/79999495-8d8afb00-84ee-11ea-87ce-bca23d5b1183.png)

**Comment by xCss** [comment]
#287  #285

**Comment by xCss** [comment]
av-min.js 问题v1.4.8已修复，感谢反馈
