### ISSUE TITLE
hexo-yilia主题下报错问题

### ISSUE THREAD

**Issue by hardape** [xCss/Valine#289]
![image](https://user-images.githubusercontent.com/50048882/80000097-48b39400-84ef-11ea-8ee2-47448da5f733.png)

**Comment by xCss** [comment]
麻烦请留下预览地址，方便我定位问题

**Comment by hardcodeape** [comment]
> 麻烦请留下预览地址，方便我定位问题，谢谢~

https://code-ape.gitee.io/article/5bc9f198.html

**Comment by xCss** [comment]
@hardcodeape Valine已升级到v1.4.8，感谢反馈
