### ISSUE TITLE
后台一条莫名奇妙的错误提示

### ISSUE THREAD

**Issue by LiarOnce** [xCss/Valine#29]
```
Uncaught TypeError: Cannot redefine property: applicationId
    at Function.defineProperty (<anonymous>)
    at av-min.js:1
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (av-min.js:1)
    at e (av-min.js:1)
    at Object.t.exports (av-min.js:8)
    at e (av-min.js:1)
    at u (av-min.js:1)
    at av-min.js:1
    at av-min.js:1
```
正常访问和评论没有问题，但刷新页面评论区就显示undefined。

**Comment by xCss** [comment]
请留下预览地址~

**Comment by LiarOnce** [comment]
@xCss 忘了。。。。。。
[https://www.acgfclub.win](https://www.acgfclub.win/)

**Comment by xCss** [comment]
@LiarOnce 貌似是你用了`pjax`，造成属性重复定义(`redefine property`)

**Comment by LiarOnce** [comment]
@xCss 确实使用了PJAX，需要将初始化代码封装成一个函数调用吗？

**Comment by xCss** [comment]
@LiarOnce 不太明白该怎么处理`pjax`页面。
不过个人觉得你应该判断下，可以尝试重新加载页面的时候，阻止重复`初始化init`

**Comment by xCss** [comment]
Fixed .

**Comment by Teemwu** [comment]
最新版本依旧出现这个问题。。。

**Comment by xCss** [comment]
@Teemwu Valine目前对`Pjax`的加载方式不兼容。

**Comment by Teemwu** [comment]
已解决。我这里问题出在重复加载了 “av-min.js" 这个文件，由于之前项目里有配置过 LeanCloud，在配置 valin 的时候重复加载了 “av-min.js" ，导致 ”Cannot redefine property: applicationId“ 报错。感觉这个报错应该跟 pjax 关系不大，因为有用到 ” jquery.pjax.min.js " 能正常使用 valine 。

**Comment by Teemwu** [comment]
@xCss 对咯，我是按照你这个 [https://github.com/ahonn/hexo-theme-even/pull/179](https://github.com/ahonn/hexo-theme-even/pull/179) 来配置出现的问题

**Comment by xCss** [comment]
@Teemwu 如果排除Valine对Pjax的兼容问题，那就是因为主题自带的Leancloud阅读量统计和Valine冲突

**Comment by Teemwu** [comment]
@xCss 是的
