### ISSUE TITLE
使用最新1.4.8的无法使用评论

### ISSUE THREAD

**Issue by ITJoker233** [xCss/Valine#290]
![image](https://user-images.githubusercontent.com/39162691/80063886-7e955e80-8569-11ea-84eb-725a5ea33d63.png)

**Comment by xCss** [comment]
额，网络原因，github图片看不到，麻烦请用第三方图床留图。。最好能留下预览地址方便我定位问题。

感谢反馈

**Comment by ITJoker233** [comment]
> 额，网络原因，github图片看不到，麻烦请用第三方图床留图。。最好能留下预览地址方便我定位问题。
> 
> 感谢反馈

ok 我的blog正在同步，https://blog.itjoker.cn/post/605dIl4Tn/ 没有的话刷新下

**Comment by xCss** [comment]
@ITJoker233 看到你博客好像启用了`Hit-Kounter`，应该是有冲突，关掉试试

或者删掉 `<script src="https://cdn1.lncld.net/static/js/av-min-1.5.0.js"></script>`试试

**Comment by ITJoker233** [comment]
> @ITJoker233 看到你博客好像启用了`Hit-Kounter`，应该是有冲突，关掉试试
> 
> 或者删掉 `<script src="https://cdn1.lncld.net/static/js/av-min-1.5.0.js"></script>`试试

我在本地debug的时候去除掉了，一样....

**Comment by ITJoker233** [comment]
貌似可以了....还是冲突了....

**Comment by ITJoker233** [comment]
> @ITJoker233 看到你博客好像启用了`Hit-Kounter`，应该是有冲突，关掉试试
> 
> 或者删掉 `<script src="https://cdn1.lncld.net/static/js/av-min-1.5.0.js"></script>`试试

应该可能是我那个统计访问量的冲突了

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/80067762-10549a00-8571-11ea-98dc-219cb0a9cf22.png)

**Comment by ITJoker233** [comment]
> ![image](https://user-images.githubusercontent.com/10877162/80067762-10549a00-8571-11ea-98dc-219cb0a9cf22.png)
> 
> 虽然我看不到图片，但是我还是想发表情。。。

我这里看的到 XD
有点迷 我换个方法搞访问量去了XD

**Comment by xCss** [comment]
> > ![image](https://user-images.githubusercontent.com/10877162/80067762-10549a00-8571-11ea-98dc-219cb0a9cf22.png)
> > 虽然我看不到图片，但是我还是想发表情。。。
> 
> 我这里看的到 XD
> 有点迷 我换个方法搞访问量去了XD

偷偷的告诉你，你可以试试把`SDK`版本升级下， ` <script src="https://cdn1.lncld.net/static/js/av-min-1.5.0.js"></script>`换成`3.x`的版本试试。(不保证成功~逃~~

**Comment by ITJoker233** [comment]
> > > ![image](https://user-images.githubusercontent.com/10877162/80067762-10549a00-8571-11ea-98dc-219cb0a9cf22.png)
> > > 虽然我看不到图片，但是我还是想发表情。。。
> > 
> > 
> > 我这里看的到 XD
> > 有点迷 我换个方法搞访问量去了XD
> 
> 偷偷的告诉你，你可以试试把`SDK`版本升级下， ` <script src="https://cdn1.lncld.net/static/js/av-min-1.5.0.js"></script>`换成`3.x`的版本试试。(不保证成功~逃~~

试了不行 XD 我还是自己搞个 不引用别人的了XD
