### ISSUE TITLE
浏览量统计无法使用

### ISSUE THREAD

**Issue by ITJoker233** [xCss/Valine#291]
具体情况是这样，开启了浏览量统计功能无法使用，
主要现象是在Leancloud中的存储无法自动创建Counter这个Class，然而手动创建这个class之后还是无法统计....XD
具体地址：https://blog.itjoker.cn/post/605dIl4Tn/

**Comment by xCss** [comment]
控制台输入：`location.pathname`，得到`"/post/605dIl4Tn/"`
``` html

<span class="post-view">
   &nbsp;•&nbsp;
   <span id="605dIl4Tn" class="leancloud_visitors" data-flag-title="关于Gridea-theme-Chic主题的Doc">
   <i class="Card Card-view"></i>&nbsp;阅读量&nbsp;
   <i class="leancloud-visitors-count">0</i>
</span>

```

而你网页中的id却是` id="605dIl4Tn"`，不相等当然不能自增

**Comment by ITJoker233** [comment]
我知道了....XD
