### ISSUE TITLE
需求：点赞按钮

### ISSUE THREAD

**Issue by wu-kan** [xCss/Valine#292]
感谢作者开发的好用的评论系统，既然 valine 可以统计博文阅读量，那么可不可以用同样的方法提供一个统计点赞数的功能呀，提供一个函数填在 onclick 里面用于点赞，并将总共赞的数量像访客统计一样填在另外一个地方

**Comment by xCss** [comment]
Valine支持`阅读量统计`是为了兼容的`leancloud_visitor`，属于一个历史遗留功能。

如果留了主动操作的功能，又将面临可能被刷数据的问题。

所以，抱歉，这个点赞功能是不会提供的。

感谢对Valine的认可！
