### ISSUE TITLE
XSS 漏洞

### ISSUE THREAD

**Issue by MHuiG** [xCss/Valine#293]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
1.  转到 https://valine.js.org/
2. 输入以下内容
```
<input type="checkbox" onfocus="alert(1)" autofocus="">
```
3. 点击发送
4. 浏览器新建一个标签页转到百度，然后转到https://valine.js.org/ 标签页
，或者直接点击提交的 checkbox

5.效果
![image](https://user-images.githubusercontent.com/38281581/80200523-5420cf80-8655-11ea-8ad8-c02145aab324.png)

- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
https://valine.js.org/
- Which versions of Valine, and which browser / OS are affected by this issue?
all
all/all

**Comment by MHuiG** [comment]
@xCss 
现在直接跳转到 https://valine.js.org/ 即可看到效果

刚刚的测试，不要忘记删掉~

**Comment by Linhk1606** [comment]
> @xCss
> 现在直接跳转到 https://valine.js.org/ 即可看到效果
> 
> 刚刚的测试，不要忘记删掉~

我靠, 你够狠啊, 估计只能让他禁止直接渲染HTML了

**Comment by MHuiG** [comment]
> > @xCss
> > 现在直接跳转到 https://valine.js.org/ 即可看到效果
> > 刚刚的测试，不要忘记删掉~
> 
> 我靠, 你够狠啊, 估计只能让他禁止直接渲染HTML了

正则表达式了解一下

**Comment by xaoxuu** [comment]
可怕😨

**Comment by xCss** [comment]
v1.4.10 已修复，感谢反馈

**Comment by MHuiG** [comment]
@xCss ReOpen  回来重改！！！！
