### ISSUE TITLE
XSS 漏洞 第二波

### ISSUE THREAD

**Issue by MHuiG** [xCss/Valine#294]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
1.  转到 https://valine.js.org/
2. 输入以下内容
```
<a href="http://example.com/attack.html" style="display: block; z-index: 100000; opacity: 0.5; position: fixed; top: 0px; left: 0; width: 1000000px; height: 100000px; background-color: red;"> </a> 
```
3. 点击发送

- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
https://valine.js.org/
- Which versions of Valine, and which browser / OS are affected by this issue?
当前版本
all/all

**Comment by MHuiG** [comment]
@xCss 

https://valine.js.org/contact.html

记得删评论~~

**Comment by Linhk1606** [comment]
@MHuiG 作为一名熊孩子不小心试了一下, 然后...

**Comment by MHuiG** [comment]
> @MHuiG 作为一名熊孩子不小心又试了一下, 然后...
<img width="82" alt="1020" src="https://user-images.githubusercontent.com/38281581/80270119-06a17280-86e8-11ea-94c2-5e932c74d290.png">   

![中枪](https://user-images.githubusercontent.com/38281581/80270117-01442800-86e8-11ea-8d42-d5cac864b230.png)

**Comment by xaoxuu** [comment]
说实话，我感觉评论框只负责解析简单的md和上传图片就足够了，公式用截图就行了……

**Comment by FFRaycoder** [comment]
说实话，公式可以转换成知乎api的

**Comment by FFRaycoder** [comment]
https://www.zhihu.com/equation?tex=<Mathjax>
URLencode一下就行了

**Comment by xaoxuu** [comment]
其实大部分评论用户连md都不会用（或者是会用但懒得用，贴代码都不用codeblock直接贴）更别提公式了，安全和稳定比其它一切都重要。

**Comment by xaoxuu** [comment]
我的博客也算是技术型博客吧，主题官网也是必须会用md为前提的，就我对这两个网站的评论区观察，对于大部分评论，发表情和直接贴图的功能是使用率最高的，md语法的使用率都非常低，最长出现的md语法是代码框和链接。

**Comment by MHuiG** [comment]
> 其实大部分评论用户连md都不会用（或者是会用但懒得用，贴代码都不用codeblock直接贴）更别提公式了，安全和稳定比其它一切都重要。

之前我尝试推广MiniValine时有主题作者向我提出建议:
![image](https://user-images.githubusercontent.com/38281581/80279109-f9a77200-872d-11ea-966f-3d37bcba798a.png)

目前MiniValine包体积已经远小于Valine

因为我使用了webpack@3 的按需加载的新特性(Valine 还在用webpack@2)

我已将Valine模块化

只有用户用到Markedown，代码高亮，公式的时候才会请求相应的源码并加载，而不是请求加载全部代码

MiniValine代码已经开源，另外我不想继续维护了（因为我用Gitalk），剩下的所有问题就交给 @xCss 大佬解决了

**Comment by xCss** [comment]
v1.4.10 已修复，感谢反馈

**Comment by MHuiG** [comment]
@xCss ReOpen  回来重改！！！！

**Comment by Linhk1606** [comment]
???

**Comment by MHuiG** [comment]
> ???

https://valine.js.org/

**Comment by Linhk1606** [comment]
> > ???
> 
> https://valine.js.org/

噗

**Comment by Linhk1606** [comment]
> > ???
> 
> https://valine.js.org/
> 
> #298

噗

**Comment by xaoxuu** [comment]
<a href="http://example.com/attack.html" style="display: block; z-index: 100000; opacity: 0.5; position: fixed; top: 0px; left: 0; width: 1000000px; height: 100000px; background-color: red;"> </a>
