### ISSUE TITLE
表情大小适配

### ISSUE THREAD

**Issue by FFRaycoder** [xCss/Valine#295]
有时候表情太大就会出现这种奇怪的问题~
![](https://cdn.jsdelivr.net/gh/FFRaycoder/cdn/imgs/20200425142747.png)

**Comment by FFRaycoder** [comment]
这个其实就是两个表情叠在一起了

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/80273030-6bb59200-8701-11ea-9265-ee3ac6a6111f.png)

2333，这么看这也很有趣啊~

**Comment by FFRaycoder** [comment]
:trollface: 真奇怪吼

**Comment by xCss** [comment]
:trollface: 卧槽，这个表情也很牛逼哦~

**Comment by FFRaycoder** [comment]
哈哈哈哈建议修复下

**Comment by FFRaycoder** [comment]
（小人noi测试中不打扰了）

**Comment by xCss** [comment]
收到，将在下个版本修复~

Ps: 因为是自定义表情(长宽可能不一致)，Valine不保证展现效果一致 :trollface:

**Comment by FFRaycoder** [comment]
:trollface:

**Comment by xCss** [comment]
:trollface: v1.4.10已修复，感谢反馈~~
