### ISSUE TITLE
嗯，valine的表情又出问题了

### ISSUE THREAD

**Issue by FFRaycoder** [xCss/Valine#296]
![](https://cdn.jsdelivr.net/gh/FFRaycoder/cdn/imgs/20200425160808.png)

**Comment by xCss** [comment]
已知Bug，参考#286

**Comment by FFRaycoder** [comment]
貌似是中文的问题

**Comment by xCss** [comment]
不管是中文还是英文，都是bug

**Comment by FFRaycoder** [comment]
但是英文开头的可以，真奇怪

**Comment by FFRaycoder** [comment]
![](https://cdn.jsdelivr.net/gh/FFRaycoder/cdn/imgs/20200425161245.png)

**Comment by xCss** [comment]
v1.4.10已修复，赶快去试试吧~~ :妙啊:
