### ISSUE TITLE
建议优化表情选择框（表情包分类）

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#297]
![iShot2020-04-2601.43.46 _1_.png](https://i.loli.net/2020/04/26/ic9nVXUSBD8tfYp.png)

随着表情开放自定义，用户可能会同时使用多种风格表情包。大佬能不能支持分类？

```js
emojiMaps: {
  "QQ": {
    "qq-1": "https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/valine/qq/qq-1.gif",
    ...
  },
  "贴吧": {
    "tieba-1": "https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/valine/tieba/tieba-1.png",
    ...
  }
}
```

参数与现在的不兼容，建议 1.5 及以后能够支持这个功能。

**Comment by MHuiG** [comment]
一周前有用户向我反映，他不会JSON解析，这个JSON嵌套对用户来讲难度可能有点高

**Comment by xaoxuu** [comment]
文档中直接给个示例copy呗

**Comment by Mister-Hope** [comment]
> 一周前有用户向我反映，他不会JSON解析，这个JSON嵌套对用户来讲难度可能有点高

NB

**Comment by UFOAlastor** [comment]
同求

**Comment by MHuiG** [comment]
表情包分类: https://minivaline.github.io/xCss.html
