### ISSUE TITLE
XSS 漏洞

### ISSUE THREAD

**Issue by MHuiG** [xCss/Valine#298]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
https://valine.js.org/
https://valine.js.org/faq.html
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
https://valine.js.org/
https://valine.js.org/faq.html
- Which versions of Valine, and which browser / OS are affected by this issue?
当前版本
all/all

前端验证都是无效的，可以绕过的。

请在展示数据的时候过滤数据。

@xCss 回来重改！！！！

**Comment by Linhk1606** [comment]
😂

**Comment by MHuiG** [comment]
不想要Gitalk了 /哭了

**Comment by MHuiG** [comment]
@Linhk1606 OK了 换 Valine

**Comment by Linhk1606** [comment]
> @Linhk1606 OK了 换 Valine

不过话说Gitalk的细节做的真的比Valine好一点点欸😅

**Comment by MHuiG** [comment]
> > @Linhk1606 OK了 换 Valine
> 
> 不过话说Gitalk的细节做的真的比Valine好一点点欸😅

Gitalk是用了UI框架

**Comment by MHuiG** [comment]
膜拜一下大佬

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/80295465-6a3da580-87a5-11ea-9646-c488fd13be55.png)

**Comment by FFRaycoder** [comment]
太狠了 @xCss 你这直接屏蔽HTML那我的自定义标签咋办:smirk:

**Comment by xCss** [comment]
> 太狠了 @xCss 你这直接屏蔽HTML那我的自定义标签咋办😏

没了，下一个~

**Comment by FFRaycoder** [comment]
> > 太狠了 @xCss 你这直接屏蔽HTML那我的自定义标签咋办😏
> 
> 没了，下一个~

不懂就问（你肝了多久）

**Comment by xCss** [comment]
> > > 太狠了 @xCss 你这直接屏蔽HTML那我的自定义标签咋办😏
> > 
> > 
> > 没了，下一个~
> 
> 不懂就问（你肝了多久）

我也不知道，实在肝不动就睡了，也没看时间~~

**Comment by lilydjwg** [comment]
我是不是一不小心错过了一个亿的广告费 :joy:

**Comment by Linhk1606** [comment]
@lilydjwg  大兄弟，很有想法啊
