### ISSUE TITLE
遵循 npm 版本号标准

### ISSUE THREAD

**Issue by Mister-Hope** [xCss/Valine#299]
目前的版本更新规则像少了一位似的。

1.4.0+版本已经出现了多个feature，希望下次出现feature的时候，提升第二位版本号。像1.4.0丢弃了邮件特性，这是一个breaking change，理论上应该提升到2.0

遵循版本号规则能够让一些用bot的人更好的查看并完成valine的版本更新，谢谢。

另外breaking changes 如果实在较小不想提升大版本号，也希望能够显著在release Page注明出来。

**Comment by MHuiG** [comment]
1.4.0丢弃了邮件特性，但是API向下兼容，不应该升级主版本号。

**Comment by Mister-Hope** [comment]
是，那好歹也在release page标一下吧，release Page轻描淡写的。

**Comment by 2642319042** [comment]
我这邮件都看不过来了。

**Comment by MHuiG** [comment]
> 我这邮件都看不过来了。

我在几年前就把邮件关了，哈哈~

**Comment by 2642319042** [comment]
> > 我这邮件都看不过来了。
> 
> 我在几年前就把邮件关了，哈哈~

我最近才玩gh，落伍了
