### ISSUE TITLE
[Feature Request] 旧版emoji表情支持

### ISSUE THREAD

**Issue by Mister-Hope** [xCss/Valine#300]
希望能够恢复旧版emoji表情支持，目前我还没找到一种能够较好回复旧版emoji表情的方式。

**Comment by Linhk1606** [comment]
emoji都是通用的吧，自己都能敲

**Comment by Mister-Hope** [comment]
电脑上有个表情面板更好敲啊，windows自带输入法的emoji快捷键是 `Ctrl + Shift + B`，和 Chrome 的切换书签栏显隐冲突。

**Comment by Linhk1606** [comment]
Windows 10的快捷键不是Ctrl+。吗

**Comment by MHuiG** [comment]
当光标在输入框时，`Ctrl + Shift + B`显示emoji，否则的话就只能切换书签栏了

**Comment by MHuiG** [comment]
当光标在输入框时，`Ctrl + Shift + B`显示emoji，否则的话就只能切换书签栏了

**Comment by xaoxuu** [comment]
自己加一些twemoji表情呢？

![QQ20200426-145442@2x.png](https://i.loli.net/2020/04/26/hQfL6EqIRHjGDNZ.png)

**Comment by Mister-Hope** [comment]
> 当光标在输入框时，`Ctrl + Shift + B`显示emoji，否则的话就只能切换书签栏了

不一定，我这边经常弹不出来，上面的书签栏在那鬼畜

**Comment by Mister-Hope** [comment]
> 自己加一些twemoji表情呢？
> 
> ![QQ20200426-145442@2x.png](https://camo.githubusercontent.com/27483d8489f5e3f72173c5e27495cbbeea0cd157/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f32362f6851664c3645714952486a47444e5a2e706e67)
> 
> https://volantis.js.org/getting-started/
> https://github.com/twitter/twemoji

想要原版 emoji，啊我又找不到图片库。

**Comment by 2642319042** [comment]
win10的表情不是Win+；键么。。。

**Comment by Mister-Hope** [comment]
> win10的表情不是Win+；键么。。。

那可能是我记错了，你看我都记不住，你能指望访客把这东西调出来？我就想用一下原生的emoji

**Comment by 2642319042** [comment]
跟这个没关系吧。。

**Comment by MHuiG** [comment]
访客为什么一定要用原生的emoji？？？搞不懂访客的思维逻辑

**Comment by 2642319042** [comment]
+1 而且想用这emoji的肯定是知道有这个快捷键，不然根本不会提这个

**Comment by Mister-Hope** [comment]
> +1 而且想用这emoji的肯定是知道有这个快捷键，不然根本不会提这个

？？？前几个版本不都是原生的emoji么，1.4.5前后才换的微博表情

**Comment by 2642319042** [comment]
我不知道，我1.4.4才用valine，然后第二天就1.4.7了，我不太了解

**Comment by MHuiG** [comment]
https://www.google.com/search?newwindow=1&safe=active&source=univ&tbm=isch&q=emoji+png&sa=X&ved=2ahUKEwiZroX45oXpAhUJhZQKHY8_BEYQ7Al6BAgKEDk&biw=1536&bih=722

**Comment by MHuiG** [comment]
http://www.5imoban.net/ziyuan/ico_png/201806263337.html

**Comment by 2642319042** [comment]
你不会一直在找这emoji吧

**Comment by MHuiG** [comment]
> 你不会一直在找这emoji吧

不是，就刚刚找了一下

**Comment by MHuiG** [comment]
这个应该可以吧

**Comment by xCss** [comment]
如果想使用旧版表情可以回退旧版Valine，也可以用输入法输入。感谢支持
