### ISSUE TITLE
下方出现错误代码 code -1

### ISSUE THREAD

**Issue by HBRoad** [xCss/Valine#301]
完整代码如下：
Code -1: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc. [N/A GET https://avoscloud.com/1.1/classes/Comment]

版本: 1.3.10
浏览器：edge、chrome、华为自带浏览器（其他未测试）

**Comment by xCss** [comment]
评论一下试试~~

**Comment by HBRoad** [comment]
评论后可以了，感谢

**Comment by iyltang** [comment]
同样的问题，无法评论解决，设置安全域名也不行

**Comment by xCss** [comment]
> 同样的问题，无法评论解决，设置安全域名也不行

![image](https://user-images.githubusercontent.com/10877162/82138777-a40a4500-9855-11ea-8da0-a63c01cb17bd.png)


leancloud的域名证书过期了，静待leancloud修复吧，或者等我更新~

**Comment by Wittoy** [comment]
> > 同样的问题，无法评论解决，设置安全域名也不行
> 
> ![image](https://user-images.githubusercontent.com/10877162/82138777-a40a4500-9855-11ea-8da0-a63c01cb17bd.png)
> 
> leancloud的域名证书过期了，静待leancloud修复吧，或者等我更新~

`us.avoscloud.com`证书目前正常
`tab.avoscloud.com` 与 `cdn1.lncld.net` 证书均过期
