### ISSUE TITLE
valine在页面源代码中能不能将app_id和app_key显示为非明文？

### ISSUE THREAD

**Issue by Duter2016** [xCss/Valine#303]
当前使用的v1.4.14版本，偶尔发现valine在页面源代码中将app_id和app_key显示为明文。valine能否在页面源代码中隐藏掉app_id及app_key？这样对于绑定域名及使用虚拟空间服务器的静态博客，可以不暴露app_id及app_key。

**Comment by zkqiang** [comment]
都已经是静态了，怎么样都无法隐藏的

**Comment by qistchan** [comment]
如对app_id和app_key的用法有疑问可以阅读[Leancloud相关文档](https://leancloud.cn/docs/sdk_setup-js.html#hash641427453)

**Comment by FFRaycoder** [comment]
> 当前使用的v1.4.14版本，偶尔发现valine在页面源代码中将app_id和app_key显示为明文。valine能否在页面源代码中隐藏掉app_id及app_key？这样对于绑定域名及使用虚拟空间服务器的静态博客，可以不暴露app_id及app_key。

这个是不可能的 除非你到时候直接删掉`<script>`标签

**Comment by MHuiG** [comment]
@FFRaycoder 你来找一下这个页面的app_id和app_key ![得意](https://user-images.githubusercontent.com/38281581/80552662-ee886680-89f9-11ea-8b23-d872dc29168f.png)

https://minivaline.github.io

**Comment by FFRaycoder** [comment]
> @FFRaycoder 你来找一下这个页面的app_id和app_key ![得意](https://user-images.githubusercontent.com/38281581/80552662-ee886680-89f9-11ea-8b23-d872dc29168f.png)
> 
> https://minivaline.github.io

槽？
![image](https://user-images.githubusercontent.com/58381667/80553152-5ee3b780-89fb-11ea-9c7e-7be79f497acb.png)

**Comment by FFRaycoder** [comment]
> @FFRaycoder 你来找一下这个页面的app_id和app_key ![得意](https://user-images.githubusercontent.com/38281581/80552662-ee886680-89f9-11ea-8b23-d872dc29168f.png)
> 
> https://minivaline.github.io

破解成功我要私信发给你吗

**Comment by FFRaycoder** [comment]
![image](https://user-images.githubusercontent.com/58381667/80553302-e16c7700-89fb-11ea-9eff-75c7392b84ae.png)

**Comment by MHuiG** [comment]
还是那句话，前端加密和验证都是无效的。

**Comment by FFRaycoder** [comment]
> 还是那句话，前端加密和验证都是无效的。

有道理，哈哈

**Comment by sviptzk** [comment]
前端验证 ==  不验证

**Comment by Linhk1606** [comment]
随便弄个MD5加密得了，反正这东西又不是很重要，别人拿走了不过就是接收你博客的评论而已，况且没什么人会无聊到破解这种东西吧

**Comment by Linhk1606** [comment]
hexo文章加密插件现在还很多人用呢

**Comment by Linhk1606** [comment]
倒是可以搞一个以LeanCloud为后端的用户登入，这样可以防止别人用你的邮箱乱发东西（滑稽

**Comment by MHuiG** [comment]
> 随便弄个MD5加密得了，反正这东西又不是很重要，别人拿走了不过就是接收你博客的评论而已，况且没什么人会无聊到破解这种东西吧

问题是用到app_id和app_key的时候需要解密，，，，，，，，
MD5摘要算法不可逆
既然需要解密，那么，，，，，，要把解密的密钥藏在哪里？？
![喜极而泣](https://user-images.githubusercontent.com/38281581/80801723-d83bff80-8bdf-11ea-97a9-897b9af0541a.png)

**Comment by MHuiG** [comment]
> hexo文章加密插件现在还很多人用呢

这个好像是用的AES对称加密，解密密钥是访问者手动输入的。

**Comment by MHuiG** [comment]
总结一下：valine在页面源代码中将app_id和app_key显示为非明文是可行的，但是也是无效的。除非你有后端，或者使用原创非公开加密算法。

**Comment by inkss** [comment]
插一句，我在早期的时候截到过 LeanCloud 的这张图，里面有这么一句:

> App Key是客户端中使用的 Key，理论上客户端中所有请求都不应被信任,默认应认为 App Key 是泄露的，防御恶意请求，不应通过加密 App Key，而应通过设置 ACL（访问权限控制列表）来实现。

现在的 LeanCloud 关于这块，虽然没说的那么直白，但是也有提及：

> AppKey 是公开的访问密钥，适用于在公开的客户端中使用。使用 AppKey 进行的访问受到 ACL 的限制。

![image](https://user-images.githubusercontent.com/31947043/80867710-30e6c780-8cc8-11ea-902e-a6dff7988393.png)

**Comment by kongfl888** [comment]
在安全域名那里限死，直接告诉你又何妨？有leancloud做安全把关，一点都不担心。[Web 应用安全设置](https://leancloud.cn/docs/data_security.html#hash532104796l)。各位有点复（xiang）杂（duo）化（le）了（ba），

**Comment by FFRaycoder** [comment]
> 总结一下：valine在页面源代码中将app_id和app_key显示为非明文是可行的，但是也是无效的。除非你有后端，或者使用原创非公开加密算法。

顺便问一下，你之前那个加密咋做的，真萌:trollface:

**Comment by MHuiG** [comment]
[Try to use cloudflare workers edge computing to improve the security](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline)

**Comment by FFRaycoder** [comment]
> [Try to use cloudflare workers edge computing to improve the security](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline)

目前有http版的api了，只需要md5即可（好像作者又咕了

**Comment by MHuiG** [comment]
> > [Try to use cloudflare workers edge computing to improve the security](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline)
> 
> 目前有http版的api了，只需要md5即可（好像作者又咕了

我在页面源代码中隐藏了app_id和app_key，https://blog.mhuig.top/   ，serverless###代###理###一下ServerURL就可以实现

**Comment by FFRaycoder** [comment]
> > > [Try to use cloudflare workers edge computing to improve the security](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline)
> > 
> > 
> > 目前有http版的api了，只需要md5即可（好像作者又咕了
> 
> 我在页面源代码中隐藏了app_id和app_key，https://blog.mhuig.top/ ，serverless###代###理###一下ServerURL就可以实现

看过啦，就是不懂实现原理……（带佬的世界俺不懂

**Comment by MHuiG** [comment]
想要个https版的api

**Comment by FFRaycoder** [comment]
这有啥区别嘛。。。。。。。。。

**Comment by MHuiG** [comment]
有个跨域的区别，有时候很烦人

**Comment by inkss** [comment]
@MHuiG 大佬( ఠൠఠ )ﾉ

leancloud 的 REST-API 能用嘛，它有个用 sign 替代 key 的方法。

sign = md5(timestamp + key)
X-LC-Sign: sign,timestamp
