### ISSUE TITLE
文章阅读计数查询异常

### ISSUE THREAD

**Issue by inkss** [xCss/Valine#306]
- [X] 可复现问题的步骤：查询异常 balabala
- [X] 可复现问题的网页地址:
        1. https://inkss.cn/friends/index.html
        2. https://inkss.cn/info/index.html
- [X] 受影响的Valine版本、操作系统，以及浏览器信息：`v1.4.14` `Edge Beta`

咳咳，我看了文档说明：

> 如果开启了阅读量统计，Valine 会自动检测 leancloud 应用中是否存在 Counter 类，如果不存在会自动创建，无需手动创建~

然后我发现全都报了 404 ，Counter 类没有自动创建，就很奇怪，不知道会不会是因为什么权限问题，然后我就参考你的返回格式手动创建了这个类，结果是文章内的计数倒也正常了，but ，意外发现了还有两个独立页面计数不对，检查了下请求，参数是个很奇怪的样子：

![image](https://user-images.githubusercontent.com/31947043/80897318-d5e5bc80-8d29-11ea-9192-69efdd13c262.png)

我接着按照格式，找着上面链接 1 的样子（链接 2 没处理），手动在数据库里添加了一条，竟也能查的到，但是无法 +1 了，这是个神马情况？

**Comment by kongfl888** [comment]
阅读统计好像是双开关，配置项开关+标签开关，前者要求置true，后者要求存在一个合格的标签元素

**Comment by xCss** [comment]
@inkss 请确认你创建的Class的读写权限

**Comment by inkss** [comment]
嗯？文章中的也是这个标签，是显示正常的来着，权限这边，我刚才看了下没什么特殊的，都是 ‘所有用户’。

文章中：

![image](https://user-images.githubusercontent.com/31947043/81361865-1a020400-9112-11ea-8909-3b7083db9d88.png)

**Comment by inkss** [comment]
@xaoxuu need u

```js
  <div class="new-meta-item browse valine">
    <a class='notlink'>
      <i class="<%- theme.meta.counter.icon %> fa-fw" aria-hidden="true"></i>
      <span id="<%- url_for(post.path || page.path) %>" class="leancloud_visitors" data-flag-title="<%- post.title || page.title %>">
      <p>
        <span class="leancloud-visitors-count"></span>
      </p>
      </span>
    </a>
  </div>
```

**Comment by xCss** [comment]
@inkss 哦，好像p元素不影响，那就看看数据权限了

**Comment by inkss** [comment]
这个，没怎么修改过：

![image](https://user-images.githubusercontent.com/31947043/81362558-b8db3000-9113-11ea-9a1c-d3d2411dee48.png)

**Comment by xCss** [comment]
> 这个，没怎么修改过：
> 
> ![image](https://user-images.githubusercontent.com/31947043/81362558-b8db3000-9113-11ea-9a1c-d3d2411dee48.png)

当条数据的访问权限看看

**Comment by inkss** [comment]
![image](https://user-images.githubusercontent.com/31947043/81362749-271ff280-9114-11ea-821a-fb9298667748.png)

**Comment by xCss** [comment]
这就很尴尬了，貌似看起来没问题，不确定是不是Pjax影响~

**Comment by inkss** [comment]
查询参数很奇怪，会不会是这个问题，正常的参数和这一页（独立页面）发送的不太一样

**Comment by xCss** [comment]
> 查询参数很奇怪，会不会是这个问题，正常的参数和这一页（独立页面）发送的不太一样

查询参数有`$in`是因为Valine认为当前页面中只有展示，没有叠加

啊~，知道了，你把当前数据的`index.html`去掉，页面和数据库中都去掉试试

**Comment by inkss** [comment]
页面链接的 index.html 和数据库条目删掉了，好像没啥变化啊  😅

**Comment by xCss** [comment]
> 页面链接的 index.html 和数据库条目删掉了，好像没啥变化啊 😅

额，我说的是这里
``` html
<span id="/info/index.html" class="leancloud_visitors" data-flag-title="留言板"><p><span class="leancloud-visitors-count">0</span></p></span>
```
把` id="/info/index.html"`改成` id="/info/"`

**Comment by inkss** [comment]
👍   可以了，ok

**Comment by inkss** [comment]
@xaoxuu  等你修 bug。 layout/_meta/counter.ejs 😏

我先写了个判断顶着了 

```
  <%
      var path = post.path || page.path;
      if(path.substring(path.length - 10) == 'index.html') {
        path = path.substring(0, path.length - 10);
      }
  %>
```

**Comment by xaoxuu** [comment]
好的

**Comment by xaoxuu** [comment]
但是不光我的主题会这样，估计任何主题都会这样吧

**Comment by note4** [comment]
> 但是不光我的主题会这样，估计任何主题都会这样吧

hexo的bug，不知道算不算bug，文章页默认按文章配置输出类似qq.com/hexo,但是到了页面同样的配置却默认输出qq.com/hexo/index.html

<%- url_for(post.path) %>

这个比较头疼，特别是从一些类似php动态博客程序迁移过来的，一般页面默认不会自动在url加index.html

**Comment by note4** [comment]
>   <%
>       var path = post.path || page.path;
>       if(path.substring(path.length - 10) == 'index.html') {
>         path = path.substring(0, path.length - 10);
>       }
>   %>

这不算模板bug，你用哪个模板，页面模块用valine统计都会这样，当然valine的调用代码优化应该也可以解决问题。

大佬你这个判断怎么用。强迫症，不想页面加index.html

**Comment by inkss** [comment]
https://github.com/xaoxuu/hexo-theme-volantis/blob/6bc052d67f3847397d4af6a05556fdc69f948446/layout/_meta/counter.ejs#L5-10

https://github.com/xaoxuu/hexo-theme-volantis/blob/6bc052d67f3847397d4af6a05556fdc69f948446/layout/_meta/counter.ejs#L11
