### ISSUE TITLE
希望支持Katex ~

### ISSUE THREAD

**Issue by MakiseVon** [xCss/Valine#307]
使用的是Next+Katex.
引入Mathjax文章的公式会重复，不引入Mathjax评论区又无法渲染orz
希望能支持Katex ~

如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [ ] 可复现问题的步骤 The steps to reproduce.
- [ ] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- [ ] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by MHuiG** [comment]
https://blog.sweetlemon.top/NOIP2018-day4/

**Comment by MakiseVon** [comment]
> https://blog.sweetlemon.top/NOIP2018-day4/

makisevon.net

我用的next的math设置引入的katex，好像没有效果 orz
