### ISSUE TITLE
手机上输入表情不方便

### ISSUE THREAD

**Issue by Makysdd** [xCss/Valine#308]
![IMG_20200504_122103](https://user-images.githubusercontent.com/38821898/80935979-c0dc5c80-8e01-11ea-857e-8e982ac6921a.JPG)
**手机**输入表情，点开表情面板，之后点一个表情，焦点就会回到输入框并且会弹出虚拟键盘，想要连续输入表情就得关了虚拟键盘再点，很不方便。

虽然也可以开着虚拟键盘点表情，但是虚拟键盘几乎占了屏幕一半的位子，这样点表情会很尴尬。

*虚拟键盘就是手机打字用的输入法那个。*

**Comment by xCss** [comment]
@Makysdd 我也不想这样，欢迎提出你的解决方案~

**Comment by Makysdd** [comment]
我也不知道了😂，看看其他人有什么想法吧

**Comment by SekiBetu** [comment]
这是业界难题，你可以问谷歌
