### ISSUE TITLE
表情包大小第二弹

### ISSUE THREAD

**Issue by FFRaycoder** [xCss/Valine#309]
咳咳，表情包发送出来能不能大点啊
![](https://cdn.jsdelivr.net/gh/FFRaycoder/cdn/imgs/20200508101953.png)
![](https://cdn.jsdelivr.net/gh/FFRaycoder/cdn@latest/imgs/emoji/alu/%E5%90%90%E8%A1%80%E5%80%92%E5%9C%B0.png)

**Comment by xCss** [comment]
这个就需要你自己写css覆盖调整了，毕竟不是所有人都要大表情~~~
