### ISSUE TITLE
[idea]使用 GitHub Actions 发送通知邮件 

### ISSUE THREAD

**Issue by MHuiG** [xCss/Valine#310]
# 问题
LearnCloud流控使得ValineAdmin邮件通知不可用
![](https://user-images.githubusercontent.com/38281581/81493175-e28d8600-92d0-11ea-8faa-1b787f1f50a8.png)

# 方案
使用 githGitHub actionActions 发送通知邮件

# Example
https://github.com/ruanyf/weather-action

**Comment by Linhk1606** [comment]
？干嘛关了

**Comment by MHuiG** [comment]
带有 repo 权限的 Personal access token

**Comment by MHuiG** [comment]
好像可以用云函数隐藏Personal access token

**Comment by MHuiG** [comment]
云函数被刷数据就不好办了
