### ISSUE TITLE
提交相同的评论两遍

### ISSUE THREAD

**Issue by moi-mo** [xCss/Valine#311]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [x] 可复现问题的步骤 The steps to reproduce.
> 在我的博文下随便评论一条即可
- [x] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
> https://rain.moimo.me/about/2038/01/19/send-me-a-message.html
- [x] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?
> v1.4.14 win10 1909 chrome v81.0

（我已经在lencloud手动删除了已有的双重评论）
点击提交后，会提交两遍相同的评论，在网页端可以看到，leancloud后台也显示两条相同的评论被提交了。

**Comment by xCss** [comment]
> 如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:
> 
> * [x]  可复现问题的步骤 The steps to reproduce.
> 
> > 在我的博文下随便评论一条即可
> 
> * [x]  可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
> 
> > https://rain.moimo.me/about/2038/01/19/send-me-a-message.html
> 
> * [x]  受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?
> 
> > v1.4.14 win10 1909 chrome v81.0
> 
> （我已经在lencloud手动删除了已有的双重评论）
> 点击提交后，会提交两遍相同的评论，在网页端可以看到，leancloud后台也显示两条相同的评论被提交了。

抱歉，我并没有复现你所描述的情况。
![image](https://user-images.githubusercontent.com/10877162/81536286-e0452d80-939d-11ea-84bf-2096f3117f23.png)

**Comment by moi-mo** [comment]
啊这……



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nine"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午3:41
收件人:&nbsp;"xCss/Valine"<Valine@noreply.github.com&gt;;
抄送:&nbsp;"moi.rpy"<3066628847@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xCss/Valine] 提交相同的评论两遍 (#311)





  
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:
  
  可复现问题的步骤 The steps to reproduce.
   
在我的博文下随便评论一条即可
   
  可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
   
https://rain.moimo.me/about/2038/01/19/send-me-a-message.html
   
  受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?
   
v1.4.14 win10 1909 chrome v81.0
  
（我已经在lencloud手动删除了已有的双重评论）
 点击提交后，会提交两遍相同的评论，在网页端可以看到，leancloud后台也显示两条相同的评论被提交了。
  
抱歉，我并没有复现你所描述的情况。

**Comment by xCss** [comment]
@moi-mo 看起来像是你的页面上的sw.js的锅，先去掉试试？

**Comment by moi-mo** [comment]
……这个是主题的……抱歉我真的不理解它是干什么的xxx
先在本地试一下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nine"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午3:48
收件人:&nbsp;"xCss/Valine"<Valine@noreply.github.com&gt;;
抄送:&nbsp;"moi.rpy"<3066628847@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xCss/Valine] 提交相同的评论两遍 (#311)





 
@moi-mo 看起来像是你的页面上的sw.js的锅，先去掉试试？

**Comment by moi-mo** [comment]
然并卵orz


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nine"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 下午3:48
收件人:&nbsp;"xCss/Valine"<Valine@noreply.github.com&gt;;
抄送:&nbsp;"moi.rpy"<3066628847@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xCss/Valine] 提交相同的评论两遍 (#311)





 
@moi-mo 看起来像是你的页面上的sw.js的锅，先去掉试试？

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/81537243-7ded2c80-939f-11ea-8105-deab65c779d1.png)

确实是受sw.js影响，重复提交了~

**Comment by moi-mo** [comment]
诶……
https://github.com/moi-mo/moi-mo.github.io/blob/master/sw.js
请问可以帮忙看一下吗……这方面真的一窍不通x
谢谢！

**Comment by xCss** [comment]
> 诶……
> https://github.com/moi-mo/moi-mo.github.io/blob/master/sw.js
> 请问可以帮忙看一下吗……这方面真的一窍不通x
> 谢谢！

抱歉，帮不了你，sw这玩意儿我没研究过~_~!

**Comment by moi-mo** [comment]
嗯……谢谢了
我去主题那边再提个issue吧x orz
