### ISSUE TITLE
想要一个全站访问统计

### ISSUE THREAD

**Issue by inkss** [xCss/Valine#312]
### 一、全站访问统计

现在只有对文章的阅读统计，按照现有的阅读统计思路，分开个统计,添加个全站统计挺简单的啊。

使用的时候，页脚放：`<span id="/" class="leancloud_visitors_pv" data-flag-title="Web Title"><span class="leancloud-visitors-count-pv"></span></span>`

<details>
<summary>相关代码</summary>

```
let CounterFactory = {
    add(Counter,currPath) {
        let root = this
        let lvs = Utils.findAll(document, '.leancloud_visitors,.leancloud-visitors');

        let lpv = Utils.findAll(document, '.leancloud_visitors_pv,.leancloud-visitors-pv');
        if(lpv.length) {
            let lv = lpv[0];
            let url = Utils.attr(lv, 'id');
            let title = Utils.attr(lv, 'data-flag-title');
            let xid = encodeURI(url);
            let o = {
                el: lv,
                url: url,
                xid: xid,
                title: title
            }
            if(url == '/') {
                let query = new AV.Query(Counter);
                query.equalTo('url', url);
                query.find().then(ret => {
                    if (ret.length > 0) {
                        let v = ret[0];
                        v.increment("time");
                        v.save().then(rt => {
                            $('.leancloud-visitors-count-pv').text(rt.get('time'));
                        }).catch(ex => {
                            console.log(ex)
                        });
                    } else {
                        createCounter(Counter, o)
                    }
                }).catch(ex => {
                    ex.code == 101 && createCounter(Counter, o)
                })
            }
        }
        //...
```

</details>

我按照这个思路，在自己网站页脚里改了一下的。

**Comment by inkss** [comment]
# 二、文章评论数计数

我在翻 LeanCloud 文档时，看到这么一个函数：

![image](https://user-images.githubusercontent.com/31947043/81696977-38138f80-9497-11ea-8c6d-8e79362890a0.png)

所以，同样的，类似于阅读计数，是不是可以根据文章 url 统计出当前文章评论数，做到这种效果：

![image](https://user-images.githubusercontent.com/31947043/81697564-b40dd780-9497-11ea-9a84-4a2c22803561.png)

思路类似于，只查询不自增那部分呢？

**Comment by inkss** [comment]
瞎吉儿改，写出了一版，起码证明思路是对的，不过还是希望你这边提供这个功能了。

![image](https://user-images.githubusercontent.com/31947043/81706387-92661d80-94a2-11ea-9e89-731120ec82b3.png)

**Comment by inkss** [comment]
感觉，进一步的可以做出，当前热门评论的文章列表了，emmm

**Comment by xCss** [comment]
> ### 二、文章评论数计数
> 我在翻 LeanCloud 文档时，看到这么一个函数：
> 
> ![image](https://user-images.githubusercontent.com/31947043/81696977-38138f80-9497-11ea-8c6d-8e79362890a0.png)
> 
> 所以，同样的，类似于阅读计数，是不是可以根据文章 url 统计出当前文章评论数，做到这种效果：
> 
> ![image](https://user-images.githubusercontent.com/31947043/81697564-b40dd780-9497-11ea-9a84-4a2c22803561.png)
> 
> 思路类似于，只查询不自增那部分呢？

文章评论数统计是早已实现的，参考Next主题~

**Comment by confessioncn** [comment]
楼主是真的爱折腾！

**Comment by inkss** [comment]
啊嘞，那我去看看 @xCss

**Comment by xaoxuu** [comment]
我觉得访问统计（包括全站和页面）可以做一个单独的轻量级的库。

**Comment by removeif** [comment]
> 感觉，进一步的可以做出，当前热门评论的文章列表了，emmm

尝试过热门文章评论，暂时是实现不了的，hql不支持group，so你查不到哪个文章的评论数多

**Comment by inkss** [comment]
> > 感觉，进一步的可以做出，当前热门评论的文章列表了，emmm
> 
> 尝试过热门文章评论，暂时是实现不了的，hql不支持group，so你查不到哪个文章的评论数多

查出所有文章的评论数，然后对结果进行排序呢?

或者，进一步的写云函数，每天特定时间里，查一遍文章评论数，存到另外一张表里，沉淀一下，用的时候单独查这张表呢？

**Comment by removeif** [comment]
> > > 感觉，进一步的可以做出，当前热门评论的文章列表了，emmm
> > 
> > 
> > 尝试过热门文章评论，暂时是实现不了的，hql不支持group，so你查不到哪个文章的评论数多
> 
> 查出所有文章的评论数，然后对结果进行排序呢?
> 
> 或者，进一步的写云函数，每天特定时间里，查一遍文章评论数，存到另外一张表里，沉淀一下，用的时候单独查这张表呢？

好吧，没毛病
