### ISSUE TITLE
设置了 path 之后阅读统计失效

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#314]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [x] 可复现问题的步骤 设置页面A的 path 为页面B （即页面A使用页面B的评论数据）进入页面A刷新访问量不会变。
- [x] 可复现问题的网页地址 https://xaoxuu.com/news/2020-05-18/
- [x] 受影响的Valine版本、操作系统，以及浏览器信息 `v1.4.14`

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/82328184-1f185a80-9a12-11ea-9fca-4e39a28260e2.png)

![image](https://user-images.githubusercontent.com/38281581/82328223-2ccde000-9a12-11ea-8158-813035fcb0fc.png)

@xaoxuu 这两个必须一致

https://github.com/xCss/Valine/blob/master/src/index.js#L361

**Comment by xaoxuu** [comment]
Valine 支持设置页面的 `path` 来共用评论数据，一旦设置了 `path` 那么当前页面的 path 就一定和评论数据的 path 不一致。如果规定必须一致才 `+1` ，那么两个功能就前后矛盾了呀。

**Comment by xaoxuu** [comment]
好像官方没这么说，，是我自己这样用的。那么 path 就必须是当前页面的 path 了。

如果访问统计功能独立出来多好啊，这样全站统计也好弄了。

**Comment by MHuiG** [comment]
其实Valine真的需要解耦~

**Comment by xaoxuu** [comment]
好的，那这个 issue 我先关了，希望 @xCss 大佬考虑一下。
