### ISSUE TITLE
建议样式从 js 文件中分离出来

### ISSUE THREAD

**Issue by xaoxuu** [xCss/Valine#317]
官方可以提供一个默认的主题 css 文件 `themes/valine.css`
然后我们可以编写主题，提交到 `themes/` 中
集成 Valine 的站长就可以选择喜欢的主题
顺便又减少了一点 js 文件的体积。

**Comment by xCss** [comment]
https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/Valine.Pure.min.js

这个是无Css文件

**Comment by xaoxuu** [comment]
ok
