### ISSUE TITLE
考虑支持新浪微博登录吗？

### ISSUE THREAD

**Issue by kangkaisen** [xCss/Valine#32]
您好，这个评论系统很赞，有考虑支持新浪微博登录吗？

**Comment by xCss** [comment]
你好，#22 也提出过相同的需求或建议。

抱歉，在[FAQ](https://valine.js.org/#/faq) 中已经很明确表达了`无后端`这个观点。

当然，如果你有好的前端解决方案，欢迎留言。

感谢支持~
