### ISSUE TITLE
Leancloud华东域名已更换

### ISSUE THREAD

**Issue by Wittoy** [xCss/Valine#320]
`https://tab.avoscloud.com` 已不再支持，已更换成 `https://tab.leancloud.cn`
>https://forum.leancloud.cn/t/https-tab-avoscloud-com/22795

**Comment by xCss** [comment]
已知bug，将在下个版本修复，感谢反馈~

**Comment by daiweinus** [comment]
最新海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢

**Comment by Healock** [comment]
> 最新的海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢

海外版同样的问题，具体就是单击发送按钮卡死。希望下个版本解决

**Comment by catbro666** [comment]
> > 最新的海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢
> 
> 海外版同样的问题，具体就是单击发送按钮卡死。希望下个版本解决

碰到同样问题，发送请求后没有响应。无法获取评论数统计，也无法发表新的评论。

**Comment by ukityh** [comment]
海外版碰到同样的问题

> > > 最新的海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢
> > 
> > 
> > 海外版同样的问题，具体就是单击发送按钮卡死。希望下个版本解决
> 
> 碰到同样问题，发送请求后没有响应。无法获取评论数统计，也无法发表新的评论。

也是海外版，遇到同样的问题

**Comment by Duter2016** [comment]
> 最新海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢

https://github.com/xCss/Valine/issues/340

**Comment by Duter2016** [comment]
> > 最新的海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢
> 
> 海外版同样的问题，具体就是单击发送按钮卡死。希望下个版本解决

https://github.com/xCss/Valine/issues/340

**Comment by Duter2016** [comment]
> > > 最新的海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢
> > 
> > 
> > 海外版同样的问题，具体就是单击发送按钮卡死。希望下个版本解决
> 
> 碰到同样问题，发送请求后没有响应。无法获取评论数统计，也无法发表新的评论。

https://github.com/xCss/Valine/issues/340

**Comment by Duter2016** [comment]
> 海外版碰到同样的问题
> 
> > > > 最新的海外评论无法提交评论，旧的评论内容也消失了。但leancloud数据库的数据还在，请问如何解决，谢谢
> > > 
> > > 
> > > 海外版同样的问题，具体就是单击发送按钮卡死。希望下个版本解决
> > 
> > 
> > 碰到同样问题，发送请求后没有响应。无法获取评论数统计，也无法发表新的评论。
> 
> 也是海外版，遇到同样的问题

https://github.com/xCss/Valine/issues/340
