### ISSUE TITLE
建议提供直接存储邮箱 MD5 的选项

### ISSUE THREAD

**Issue by xiaopc** [xCss/Valine#321]
目前存储的方式相当于直接可以请求到所有评论用户的邮箱。
显示 Gravatar 只需要邮箱的 MD5 hash 的嘛（
（如果有需要保存原始邮件地址供第三方使用的话，加一个只可写入的 Class 存储 hash 对应关系也可以吧

**Comment by MHuiG** [comment]
[Try to use cloudflare workers edge computing to improve the security](https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline)
