### ISSUE TITLE
chrome浏览器不显示评论内容  safari可以显示

### ISSUE THREAD

**Issue by seasonfif** [xCss/Valine#324]
chrome浏览器不显示评论内容  safari可以显示

![image](https://user-images.githubusercontent.com/6039633/83252411-c1d49400-a1dd-11ea-8776-389eb425ff7c.png)

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/83254653-c13dfc80-a1e1-11ea-900c-771a37d6959f.png)
![image](https://user-images.githubusercontent.com/10877162/83254705-ce5aeb80-a1e1-11ea-85df-5001f94793df.png)

抱歉，我这边正常

---------------------------

还有，我不是风水大师，不能凭一张图就能看出问题。。。。

如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [ ] 可复现问题的步骤 The steps to reproduce.
- [ ] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- [ ] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by Linhk1606** [comment]
你选中一下，看看有没有字？感觉是CSS的问题，文字变成白色的了。。。 @seasonfif

**Comment by seasonfif** [comment]
@Linhk1606 不能选中   看过控制台  html节点是有值的   目前看来就是没有显示出来 @xCss
