### ISSUE TITLE
按钮位置错误

### ISSUE THREAD

**Issue by RuoLv** [xCss/Valine#325]
![image](https://user-images.githubusercontent.com/40071018/83362998-20447280-a396-11ea-9d0d-87e4abf37519.png)
在我的网页中按键位置都不对了这可怎么办

**Comment by RuoLv** [comment]
我的主题模板：https://1drv.ms/u/s!AguDemNSrdFc-XT59YHWkekwmjIv?e=d5ALu8

**Comment by xCss** [comment]
> ![image](https://user-images.githubusercontent.com/40071018/83362998-20447280-a396-11ea-9d0d-87e4abf37519.png)
> 在我的网页中按键位置都不对了这可怎么办

位置不对可能是你的主题样式覆盖了valine的样式，自己修改样式或者写样式覆盖原有样式
