### ISSUE TITLE
关于如何在Wikidot页面下实现Valine的问题

### ISSUE THREAD

**Issue by MCSeekeri** [xCss/Valine#326]
我想在一个Wikidot站点上使用Valine作为评论系统(自带评论不符合我要求),但是Wikidot无法解析HTML代码,Wiki语法选择插入HTML块之后也无法工作。

我已经测试了多种方案,可是由于本人水平有限依旧无法解决。

[测试页面](http://wsw-cnna.wikidot.com/sandbox:valine)
可以点击"检视源代码"查看使用Wiki语法导入的HTML块。

**Comment by xCss** [comment]
> 我想在一个Wikidot站点上使用Valine作为评论系统(自带评论不符合我要求),但是Wikidot无法解析HTML代码,Wiki语法选择插入HTML块之后也无法工作。
> 
> 我已经测试了多种方案,可是由于本人水平有限依旧无法解决。
> 
> [测试页面](http://wsw-cnna.wikidot.com/sandbox:valine)
> 可以点击"检视源代码"查看使用Wiki语法导入的HTML块。

我想可能需要你修改源码，而不是选择wiki语法插入

**Comment by MCSeekeri** [comment]
非常令人悲伤的是......Wikidot就是这么设计的
直接改最后的HTML是不行的,只能修改Wiki语法
目前似乎是可以通过主题什么的实现近似于修改HTML的效果
但我技术力实在达不到（叹气
如果没法调用Valine我这文章基本就废了（叹气
