### ISSUE TITLE
Valine项目是否继续开源

### ISSUE THREAD

**Issue by ghost** [xCss/Valine#328]
最近只更新dist目录

想要稍微修改一下，好像无从下手啊😄

**Comment by FFRaycoder** [comment]
![image](https://user-images.githubusercontent.com/58381667/84583125-b3b28480-ae27-11ea-936a-fce2b0ce5716.png)

**Comment by thepiee** [comment]
所以以后就不能自己修改了😒

**Comment by thepiee** [comment]
由于某些原因，需要关闭这个issue

https://blog.csdn.net/diloudiao5379/article/details/101196267

**Comment by thepiee** [comment]
在此呼吁请善待开源项目维护者

**Comment by FFRaycoder** [comment]
@xCss 可以关issue了

**Comment by zealseeker** [comment]
如果真是因为这个原因就停止"开源"还是挺可惜的，营造好的社区环境可能需要所有人的努力吧。

看了issue的标题开始怀疑自己是不是访问的是Github :joy:
（很好奇这些用户的年龄段，包括作者[偷笑]）

**Comment by FFRaycoder** [comment]
> 由于某些原因，需要关闭这个issue
打脸

**Comment by FFRaycoder** [comment]
账号直接注销了

**Comment by zealseeker** [comment]
@FFRaycoder 发现个中学生  😀 佩服，我初中的时候还只会做静态网页

**Comment by FFRaycoder** [comment]
> @FFRaycoder 发现个中学生 😀 佩服，我初中的时候还只会做静态网页

？？你咋知道
