### ISSUE TITLE
评论者昵称显示的是邮件地址而不是网站地址

### ISSUE THREAD

**Issue by LiarOnce** [xCss/Valine#33]
Demo(依然是这个)：[https://www.acgfclub.win](https://www.acgfclub.win)
版本：v1.1.8-rc3

网站需要保证邮箱保密~~其实是因为WP和TE下自带评论习惯了~~。
可否对输出评论者的网站链接进行自定义，如果没有输入网站链接就直接取消超链接。

![snipaste_20171126_221826.png](https://i.loli.net/2017/11/26/5a1aceb3ec4e9.png)

**Comment by xCss** [comment]
你好，目前valine的三个评论者属性是可配置的，如果不需要的话可以自己设置。

valine目前的链接逻辑是网址优先，如果没有填网址，那就会把邮箱地址作为链接地址。😁

**Comment by LiarOnce** [comment]
@xCss 问题是我填了网址还是把邮箱作为链接地址了

**Comment by xCss** [comment]
@LiarOnce 我刚刚尝试了下，发现填写网址后会将网址作为链接。

并没有什么问题。https://www.acgfclub.win/archives/5/

**Comment by LiarOnce** [comment]
@xCss 我发现问题了，网址不支持带`http://`和`https://`的输入。。。。。。

**Comment by xCss** [comment]
额，有这种问题？我本地先试试~

**Comment by xCss** [comment]
Fixed  7bfdccf

**Comment by xCss** [comment]
@LiarOnce https://github.com/xCss/Valine/releases/tag/v1.1.9-beta4
`v1.1.9-beta4`针对`单页`和`pjax`页面做了优化修改，你试试能否解决你在https://www.acgfclub.win/archives/13/ 页面中点击`上一篇/下一篇`出现无法评论的问题

**Comment by LiarOnce** [comment]
@xCss 可惜并没有用，还有错误：
```
TypeError: Cannot read property 'Query' of undefined
```
而且将初始化代码移出`div#pjax-container`后依然出错，貌似问题更严重了。。。。。。

**Comment by xCss** [comment]
@LiarOnce 额，我看你源码，貌似初始化还是在`div#pjax-container`元素里啊

**Comment by xCss** [comment]
![1](https://user-images.githubusercontent.com/10877162/35901537-16a21bec-0c12-11e8-85ce-134ff2e59b9f.png)  
![2](https://user-images.githubusercontent.com/10877162/35901538-16e83924-0c12-11e8-960c-5bb89b688217.png)

而且，我看你网页上引用了两次js文件。。。

**Comment by LiarOnce** [comment]
@xCss 问题是不管在不在都不能正常使用
