### ISSUE TITLE
 1.4.14设置了QQ获取头像和必填项无效

### ISSUE THREAD

**Issue by CodeXey** [xCss/Valine#332]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [ ] 设置了必填邮箱和昵称，不填仍旧可以正常评论
- [ ] ioser.io
- [ ] Valine:1.4.14, macOS 10.14.6, Chrome 83.0.4103.116

![屏幕快照2020-07-21下午2.53.09](https://hexoblogpic.oss-cn-beijing.aliyuncs.com/imgs/屏幕快照%202020-07-21%20下午2.53.09%20.png)

![屏幕快照2020-07-21下午2.51.34](https://hexoblogpic.oss-cn-beijing.aliyuncs.com/imgs/屏幕快照%202020-07-21%20下午2.51.34%20.png)

**Comment by CodeXey** [comment]
忘记修改Valine.swig文件了

**Comment by RershallzzZ** [comment]
请问需要修改哪些内容

**Comment by RershallzzZ** [comment]
> 忘记修改Valine.swig文件了

请问需要修改哪些内容
