### ISSUE TITLE
是否博主回复？

### ISSUE THREAD

**Issue by robinch-top** [xCss/Valine#333]
是否存在，我不是博主，但我使用博主的邮箱昵称进行评论。
在初始化的时候存入密码，当博主进行回复评论的时候，在头像或邮箱、博客输入密码，此条评论头像上或昵称后显示博主标识或管理员标识。
未输入密码不能使用博主邮箱进行评论。

**Comment by FFRaycoder** [comment]
这个只有别人的魔改版。。。
