### ISSUE TITLE
手机浏览器无法显示评论

### ISSUE THREAD

**Issue by Neteraxe** [xCss/Valine#335]
- 打开valine.js.org
- 使用非QQ浏览器
- 不能显示他人评论

这个bug这么重要为什么没人报www

**Comment by Neteraxe** [comment]
已经测试过Opera, Via, 极速浏览器, Kiwi等浏览器

**Comment by Neteraxe** [comment]
只有QQ的X5内核可以渲染，其他都无他人评论

**Comment by Neteraxe** [comment]
又观察了一下似乎是我的手机的webview实现问题，但是不确定，有其他人有同样问题吗？

**Comment by moi-mo** [comment]
可能是最近的更新导致的8，毕竟先前都没有这个问题。


整理了一下：
## 可以：
- 手机chrome
- Microsoft Edge 44.19041.1.0

## 不行：
- firefox（pc&手机）
- MIUI自带浏览器
- pc chrome

**Comment by Neteraxe** [comment]
@moi-mo 你和我的问题不太一样

**Comment by moi-mo** [comment]
唔……？

**Comment by Neteraxe** [comment]
@moi-mo 我的是edge，chrome等都不可以，就X5内核可以
作者好像是咕了，上期更新是4月

**Comment by moi-mo** [comment]
你的edge是最新版chromium内核的吗？

**Comment by Neteraxe** [comment]
不是，就是原版的，最新版也不可以

**Comment by moi-mo** [comment]
啊这……

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/88878455-9ceeb280-d25a-11ea-910b-0f8e23c9bf1f.png)

![image](https://user-images.githubusercontent.com/10877162/88878508-b55ecd00-d25a-11ea-9260-0023577b51b7.png) jsdelivr服务崩了，等jsdelivr修复吧~。。。你们版聊这么久没抓到重点。

**Comment by moi-mo** [comment]
好的x谢谢qwq

**Comment by YexuanXiao** [comment]
> 好的x谢谢qwq

关闭issue吧。。
