### ISSUE TITLE
无法输入3个字以内的昵称

### ISSUE THREAD

**Issue by kuretru** [xCss/Valine#337]
#281 这个Pull requests限制了昵称的字符，这导致了我的昵称现在无法回复了，建议增加一个选项，可以自由设置昵称的长度。

**Comment by FFRaycoder** [comment]
这是因为开启了必须填昵称嘛？

**Comment by kuretru** [comment]
> 这是因为开启了必须填昵称嘛？

我的昵称只有两个字，作为博主，我总得填写昵称吧，但是现在我只能填写三个字的昵称，然后去LeanCloud里改成2个

**Comment by FFRaycoder** [comment]
> > 这是因为开启了必须填昵称嘛？
> 
> 我的昵称只有两个字，作为博主，我总得填写昵称吧，但是现在我只能填写三个字的昵称，然后去LeanCloud里改成2个

嗯 这好像是一个问题。。。。是有必要加一个配置项了
