### ISSUE TITLE
无法正确发送邮件提醒

### ISSUE THREAD

**Issue by hjthjthjt** [xCss/Valine#34]
Valine版本v1.1.8-rc4

我使用的是 hexo-theme-material，有关配置如下
comment:
    use: valine
    valine_leancloud_appId:  ***********
    valine_leancloud_appKey:  ***********
    valine_notify: true # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
    valine_verify: true # valine verify code (true/false)
    valine_pageSize: 10 # comment list page size
    valine_avatar: identicon # gravatar style https://valine.js.org/#/avatar
    valine_lang: zh-cn # i18n
    valine_placeholder: 评论啊，快活啊！ # valine comment input placeholder(like: Please leave your footprints )
    valine_guest_info: nick,mail,link #valine comment header info

目前评论可以正常工作，但是无法收到邮件提醒（评论已有评论）
[https://jakting.com](https://jakting.com)

**Comment by xCss** [comment]
@hjthjthjt 你好，请问是按照这个教程来配置邮件提醒的吗？ https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
