### ISSUE TITLE
有删除评论的功能么

### ISSUE THREAD

**Issue by chen-yuan-yuan** [xCss/Valine#343]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [ ] 可复现问题的步骤 The steps to reproduce.
- [ ] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- [ ] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by Shulun** [comment]
在leancloud里面直接删除评论就好。

**Comment by FFRaycoder** [comment]
这是一个匿名评论系统，从设计上是不支持的
