### ISSUE TITLE
昵称3个字符

### ISSUE THREAD

**Issue by XRSec** [xCss/Valine#349]
昵称填写QQ号自动变成QQ昵称，但是3个字符就不行，但是我是两个汉字，用的是1.4.14，buttfly主题

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/73819467/101969748-0cd96480-3c61-11eb-8552-ed36aedc83fe.png)

**Comment by zRains** [comment]
也许你可以修改一下
https://github.com/xCss/Valine/blob/87da8204db50194c338f6929166f80f41ca87222/src/index.js#L846
