### ISSUE TITLE
无法拉取带有中文的 QQ 昵称，只显示 QQ 号和 QQ 头像

### ISSUE THREAD

**Issue by wushuobjfu** [xCss/Valine#354]
- [x] 可复现问题的步骤 **拉取任意带有中文字符的 QQ 号，即可复现**
- [x] 可复现问题的网页地址 **任意带有 Valine 评论系统的网页**如 [Valine 官网](https://valine.js.org)
- [x] 受影响的Valine版本、操作系统，以及浏览器信息 **在 ver1.4.14 下，在```Windows Chrome/Firefox``` ```MacOS Safari``` ```iOS Safari``` ```Android Chrome```**均无法拉取
- [ ] 可能造成的原因 **腾讯用户信息获取接口变动**

**Comment by NichtsVonChaos** [comment]
可考虑使用 #357 的代码。

**Comment by q1393877285** [comment]
同问题，楼上说的换接口需要动刀的地方有点多啊 返回的data属性名字不一样

**Comment by NichtsVonChaos** [comment]
@q1393877285 你可以用我改好的：https://github.com/NichtsVonChaos/nichtsvonchaos.github.io/blob/master/assets/js/dist/Valine.min.js

**Comment by q1393877285** [comment]
> @q1393877285 你可以用我改好的：https://github.com/NichtsVonChaos/nichtsvonchaos.github.io/blob/master/assets/js/dist/Valine.min.js

感谢！

**Comment by xCss** [comment]
https://github.com/xCss/Valine/releases/tag/v1.4.16
