### ISSUE TITLE
云引擎域名无法删除，文件域名无法绑定

### ISSUE THREAD

**Issue by wyxogo** [xCss/Valine#362]
云引擎域名无法删除
![image](https://user-images.githubusercontent.com/61509470/118370880-6234eb80-b5dc-11eb-8e5f-19ce7c3ea8fd.png)
文件域名无法绑定
![image](https://user-images.githubusercontent.com/61509470/118370906-81cc1400-b5dc-11eb-85f0-5d18068b19d2.png)

**Comment by X1lyS** [comment]
<h1>test</h1>

**Comment by X1lyS** [comment]
<sript>alert(1)</sript>

**Comment by X1lyS** [comment]
https://www.baidu.com

**Comment by X1lyS** [comment]
<img src="aaa">
