### ISSUE TITLE
无法加载和发布评论

### ISSUE THREAD

**Issue by yucho123987** [xCss/Valine#369]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [ ] 可复现问题的步骤 The steps to reproduce.
- [x] 点击图标时，无反应
- [x] 评论无法加载，也无法发布评论
- [x] 控制台ajax返回错误：“Class or object doesn't exists.”
- [x] 手动在leancloud添加class“Comment”后未继续报错，但仍无法加载表情和评论。
- [ ] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- [x] https://jsfiddle.net/0benLt5q/
- [ ] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?
- [x] 最新版本，设备Android 9 VIVO Y3s，Via及firefox nightly都试过

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/125713448-79dd238e-fb3e-4ebc-bf55-4bd0084efffa.png)

**Comment by yucho123987** [comment]
@xCss 谢谢，已经解决，我说怎么加载不出来，原来是我用innerHTML动态添加内容时把原来的事件覆盖了，怪不得我无法用js给页面元素动态设置事件，但在控制台里设置又可以。谢谢了
