### ISSUE TITLE
新版本不显示原来的评论。

### ISSUE THREAD

**Issue by cugxuan** [xCss/Valine#37]
新版本不显示原来的评论。但是新评论的内容显示正常。

**Comment by xCss** [comment]
🙉 啊？麻烦提供预览地址。

最好能够将Leancloud中存储的新旧评论中的`url`对比下~

**Comment by cugxuan** [comment]
确实是url的问题。二十多条评论自己手动改下？
![image](https://user-images.githubusercontent.com/23120372/33793281-dbc1050c-dcef-11e7-91eb-e160eccf177e.png)
![image](https://user-images.githubusercontent.com/23120372/33793283-e51a76ba-dcef-11e7-8c63-8bef5eb7b929.png)

**Comment by cugxuan** [comment]
还好现在评论不多。已经自己改好。谢谢。 @xCss
