### ISSUE TITLE
不使用LeanCloud，如何部署在自己的服务器呢？

### ISSUE THREAD

**Issue by flatblowfish** [xCss/Valine#370]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [ ] 可复现问题的步骤 The steps to reproduce.
- [ ] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- [ ] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by kuohuanhuan** [comment]
使用 leancloud 國際版

**Comment by flatblowfish** [comment]
> 使用 leancloud 国际版

哥们，看不懂标题吗？leancloud垃圾，被人刷了几个评论就全国范围宕机了。我用个几把。

**Comment by kuohuanhuan** [comment]
> > 使用 leancloud 国际版
> 
> 
> 
> 哥们，看不懂标题吗？leancloud垃圾，被人刷了几个评论就全国范围宕机了。我用个几把。

那就別用

**Comment by flatblowfish** [comment]
![郭桓桓](https://kuohuanhuan.gq/?id=郭桓桓)

**Comment by flatblowfish** [comment]
你域名拼错了，不是`kuohuanhuan.gq`，是`guohuanhuan.gq`。

**Comment by flatblowfish** [comment]
你怎么换了啊？继续用啊？
我只要多开几个线程刷评论，他就会全国宕机了。

**Comment by flatblowfish** [comment]
有空写个爬虫，把使用这个评论的网站全刷了，哈哈哈
