### ISSUE TITLE
Leancloud URL bug in av.js

### ISSUE THREAD

**Issue by HetBenkt** [xCss/Valine#376]
I don't know if I'm in the correct place here, but never shooting is always miss!
It looks like the dependent av.js from `//cdn1.lncld.net/static/js/3.0.4/av.js` contains a bug based on the region CN (default) or US (like I am). This broke the commenting system for my website because of (I guess) a domain change on the leancloud side of things. The solution can be found in the attached file. Maybe someone knows more and maybe there is a new version available with the real fix?

![2021-11-26 17_06_24-Window](https://user-images.githubusercontent.com/15157563/143607370-cd5be3ff-b9a6-4634-8d3b-5331496580e3.png)

**Comment by hubojing** [comment]
The latest link is 
```js
<script src="//code.bdstatic.com/npm/leancloud-storage@4.12.0/dist/av-min.js"></script>
```

**Comment by raolixiang-up** [comment]
nice

**Comment by CoreJa** [comment]
nice one, saving huge time

**Comment by Lo-Y-eH** [comment]
好
