### ISSUE TITLE
控制台报错：us.leancloud 域名无法找到

### ISSUE THREAD

**Issue by nojsja** [xCss/Valine#377]
![image](https://user-images.githubusercontent.com/19613878/143977657-12e834bd-a00b-405c-ab42-8cb04b862732.png)

**Comment by xinyu-yang** [comment]
Leancloud的API域名更新了，你需要手动设置 `serverURLs`，请参考[官方文档](https://leancloud.cn/docs/rest_api.html#hash-1722650509)；
另外，你的 valine 版本似乎有点老了
