### ISSUE TITLE
Github/Gitee 调用阅读量统计拒绝访问

### ISSUE THREAD

**Issue by hahaxiaowai** [xCss/Valine#379]
我将vuepress的博客部署在gitee上，使用Valine做评论和阅读量统计，在本地测试时，阅读量能够正常请求到，但是在Gitee或者在GitHub的静态Pages中报错：ERR_CONNECTION_REFUSED
这是我的部署地址，https://hahaxiaowai.gitee.io/    ，F12便能看到报错信息
我该如何解决这个问题呢？

**Comment by xCss** [comment]
![image](https://user-images.githubusercontent.com/10877162/144816856-b3db8b69-4e05-4bf0-ab7a-bb624ca0e930.png)

**Comment by xCss** [comment]
我这正常访问
![image](https://user-images.githubusercontent.com/10877162/144819699-b54a2ce9-f042-4d65-875b-3889e0e4bb42.png)

**Comment by hahaxiaowai** [comment]
啊，好吧。。换了台电脑就可以了，大概是浏览器插件问题，感谢！

**Comment by InkyTea** [comment]
> 

不是浏览器插件问题，是电脑DNS问题
