### ISSUE TITLE
valine 评论不能显示

### ISSUE THREAD

**Issue by Vincentqyw** [xCss/Valine#38]
电脑系统：win7；浏览器：chrome（其他浏览器可以）；valine评论无法显示，如下图所示：

![](http://oofx6tpf6.bkt.clouddn.com/17-12-12/73127241.jpg)

**Comment by xCss** [comment]
可怕。。。
我这边居然可以~
![tim 20171212204728](https://user-images.githubusercontent.com/10877162/33885212-b4f86b46-df7d-11e7-977e-665a38143d7a.png)

**Comment by Vincentqyw** [comment]
@xCss   没错，我在自己电脑上也可以。但是我当时在图书馆打开的，就出现了这种情况，也是莫名其妙 。
