### ISSUE TITLE
关于评论图片上传

### ISSUE THREAD

**Issue by lllyin** [xCss/Valine#380]
图片上传域名失效了，现在无法上传图片。并且无报错提示。

**建议**：暴露一个onUpload Api, 返回文件对象支持用户自定义上传。

**Comment by lllyin** [comment]
> 

因为现在看不了源码，也无法提PR，或者再开发，很尴尬，盼复。

**Comment by lllyin** [comment]
或者默认插入base64也行

**Comment by lllyin** [comment]
mark

**Comment by xCss** [comment]
新版本已发布，已更新为存储base64的方式，感谢对Valine的支持 ❤️
