### ISSUE TITLE
评论框在firefox和edge下字体过小

### ISSUE THREAD

**Issue by indes** [xCss/Valine#39]
评论框和评论在firefox和edge中字体太小了，在chrome中显示正常

**Comment by xCss** [comment]
抱歉，请确认你的页面中字体设置。
我这边显示正常~
![tim 20171214124311](https://user-images.githubusercontent.com/10877162/33975890-9d24fdf4-e0cc-11e7-95c8-d0aba930403c.jpg)
![tim 20171214124412](https://user-images.githubusercontent.com/10877162/33975891-9d56c014-e0cc-11e7-97a3-ae0e6ad3f3b3.jpg)
![tim 20171214124430](https://user-images.githubusercontent.com/10877162/33975892-9d885c1e-e0cc-11e7-8f02-46b62d7cda71.jpg)

**Comment by indes** [comment]
找到原因了，我自己写css吧
