### ISSUE TITLE
看过你的快速开始，我还是没有弄明白什么原理

### ISSUE THREAD

**Issue by fbigun** [xCss/Valine#40]
请问这个评论系统与 `leancloud.cn` 上的应用有什么关系

- 是静态博客的上的评论系统的内容存储到leancloud应用的数据库中？

请原谅我不是一个程序员。希望得到一个解答

**Comment by xCss** [comment]
是的，把leancloud当做一个数据库，所有评论数据都是存储到leancloud上面的~

**Comment by fbigun** [comment]
明白了，现在试过了，基本功能都有了。

感谢百忙之中抽出时间回答
