### ISSUE TITLE
A  XSS bug that can execute code（用户恶意修改 评论 的ua可触发XSS执行代码）

### ISSUE THREAD

**Issue by young-xz** [xCss/Valine#400]
如果您想报告错误，请提供以下信息 If you want to report a bug, please provide the following information:

- [x] 可复现问题的步骤 The steps to reproduce.
- [x] 可复现问题的网页地址 A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- [x] 受影响的Valine版本、操作系统，以及浏览器信息 Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by young-xz** [comment]
帮忙把评论删除，谢谢

**Comment by young-xz** [comment]
就是把别人测试的评论删除

**Comment by xCss** [comment]
已修复，感谢对Valine的支持~ ❤️

**Comment by xCss** [comment]
收到，感谢反馈，将在下个版本修复
