### ISSUE TITLE
打开记录ip后访问速度太慢的问题

### ISSUE THREAD

**Issue by MoeCinnamo** [xCss/Valine#401]
由于ip.sb的问题，因此在打开记录ip功能后国内访问速度过慢。

推荐增加显示ip以及其它第三方接口，以解决这个问题。

- 可复现问题的步骤: 在打开记录ip功能后在大陆的某些地区访问
- 可复现问题的网页地址: https://blog.mojy.xyz/
- 受影响的Valine版本、操作系统，以及浏览器信息: lastest、iOS/iPadOS/MacOS、Safari

**Comment by xCss** [comment]
你好，新版本已发布，将ip.sb换成了speedtest.cn

**Comment by MoeCinnamo** [comment]
> 你好，新版本已发布，将ip.sb换成了speedtest.cn

好的好的
