### ISSUE TITLE
较长的邮箱无法完全被记录的问题

### ISSUE THREAD

**Issue by MoeCinnamo** [xCss/Valine#402]
我的邮箱是比较长的邮箱地址，它已经超过了20位，但是程序却只会记录前20位，后4位并不会记录，请解决这个bug。

- 可复现问题的步骤：在邮箱一栏中输入超过20位的邮箱地址后，超过的将不再记录
- 可复现问题的网页地址：https://blog.mojy.xyz/
- 受影响的Valine版本、操作系统，以及浏览器信息：V1.5.0、iOS/iPadOS/MacOS、Safari

**Comment by xCss** [comment]
收到，很抱歉没有考虑到超过20位的邮箱地址，将于近期解决该问题，感谢对Valine的支持 :heart:

**Comment by MoeCinnamo** [comment]
> 收到，很抱歉没有考虑到超过20位的邮箱地址，将于近期解决该问题，感谢对Valine的支持 ❤️

好的好的，我的邮箱地址是abcd2890000456@gmail.com，以前没有这个bug，直到最近几天升级到V1.5.0的时候才出现的。

**Comment by xCss** [comment]
@MoeCinnamo @kasisama 你们好，新版本已发布，限制到了35位 :smile:

**Comment by MoeCinnamo** [comment]
> @MoeCinnamo @kasisama 你们好，新版本已发布，限制到了35位 😄

感谢
