### ISSUE TITLE
如果我只想修复 图片上传的功能，不想改其他的，需要改哪些代码？ 

### ISSUE THREAD

**Issue by tzy13755126023** [xCss/Valine#403]
![image](https://user-images.githubusercontent.com/47850990/175909667-15ef25f8-8ad1-4023-b014-bc8c6eb2904a.png)

如果我只想修复 图片上传的功能，不想改其他的，需要改哪些代码？ 并未找到 [#396](https://github.com/xCss/Valine/issues/396) [#380](https://github.com/xCss/Valine/issues/380) 这部分的代码

**Comment by xCss** [comment]
你好，如果你是基于当前仓库的源码修改的，可以找到以下代码：
https://github.com/xCss/Valine/blob/c40826c5816c98d797a6b1ed8b62bddf73ed4f65/src/index.js#L1045-L1068

将其修改为本地：

``` js
let uploadImage = (file,callback)=>{ 
    let reader = new FileReader();
    reader.onload = function(){
        // 这里能获取到文件的Base64
        console.log(reader.result)
        callback && callback(null,{data: reader.result})
    }
    reader.readAsDataURL(file)
 } 
```

如果你想优化显示，可以使用`URL.createObjectURL`来创建blob URL：
``` js
let key = URL.createObjectURL(image)
```
-------------------------------
参考： 
 - [URL.createObjectURL](https://developer.mozilla.org/zh-CN/docs/Web/API/URL/createObjectURL)
 - [FileReader](https://developer.mozilla.org/zh-CN/docs/Web/API/FileReader)

**Comment by tzy13755126023** [comment]
emmm 我的版本是&nbsp;Valine v1.4.14


我找到了这部分代码 是否改这段代码&nbsp; 可以将 图片上传到我自己的图床呢
Q=function(e,t){
&nbsp; var n=new FormData;
&nbsp; n.append("image",e),
&nbsp; y.default.ajax({
&nbsp; &nbsp; &nbsp;type:"post",
&nbsp; &nbsp; &nbsp;url:"https://pic.alexhchu.com/api/upload",
&nbsp; &nbsp; &nbsp;data:n,
&nbsp; &nbsp; &nbsp;success:function(e){
&nbsp; &nbsp; &nbsp; &nbsp;t&amp;&amp;t(e)
&nbsp; &nbsp; &nbsp;}
})}}




------------------&nbsp;Original message&nbsp;------------------
From: "YY"; 
Sendtime: Wednesday, Jun 29, 2022 4:15 PM
To: "xCss/Valine"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [xCss/Valine] 如果我只想修复 图片上传的功能，不想改其他的，需要改哪些代码？  (Issue #403)





 
你好，如果你是基于当前仓库的源码修改的，可以找到以下代码：
 https://github.com/xCss/Valine/blob/c40826c5816c98d797a6b1ed8b62bddf73ed4f65/src/index.js#L1045-L1068
 
将其修改为本地：
 let uploadImage = (file,callback)=&gt;{      let reader = new FileReader();     reader.onload = function(){         // 这里能获取到文件的Base64         console.log(reader.result)         callback &amp;&amp; callback(null,{data: reader.result})     }     reader.readAsDataURL(file)  } 
 
如果你想优化显示，可以使用URL.createObjectURL来创建blob URL：
 let key = URL.createObjectURL(image)
 
 
参考：
  
URL.createObjectURL
 
FileReader

**Comment by xCss** [comment]
> emmm 我的版本是&nbsp;Valine v1.4.14 我找到了这部分代码 是否改这段代码&nbsp; 可以将 图片上传到我自己的图床呢 Q=function(e,t){ &nbsp; var n=new FormData; &nbsp; n.append("image",e), &nbsp; y.default.ajax({ &nbsp; &nbsp; &nbsp;type:"post", &nbsp; &nbsp; &nbsp;url:"https://pic.alexhchu.com/api/upload", &nbsp; &nbsp; &nbsp;data:n, &nbsp; &nbsp; &nbsp;success:function(e){ &nbsp; &nbsp; &nbsp; &nbsp;t&amp;&amp;t(e) &nbsp; &nbsp; &nbsp;} })}}

如果是要上传到你自己的图床，直接修改图床地址`url:"https://pic.alexhchu.com/api/upload"` 为你自己的地址就行了。
  
返回数据格式应该是类似于这样：
``` js
{
    'code': 200,
    'data': 'your image url',
    'msg': ''
}
```
你可以试试看~
