### ISSUE TITLE
v1.5.0 User Agent 判断中将所有的 Windows 10 和 11 都识别为 Windows 11

### ISSUE THREAD

**Issue by netgc** [xCss/Valine#405]
问题描述：如题
问题示例页面：https://valine.js.org/ 首页评论
可能原因：return{"10.0":"11"，无论 Windows 10 或者 11 的 ua 中的系统版本号都是10.0
参考微软解决方法：https://docs.microsoft.com/zh-cn/microsoft-edge/web-platform/how-to-detect-win11

**Comment by xCss** [comment]
Valine是根据`UserAgent`字符串来解析操作系统，部分win10和win11的这个字符串是一样的，造成解析结果也是win11。

微软的解决办法无法从根本上解决Valine的问题

_________________________________

> 除非用新的字段来存相关信息
