### ISSUE TITLE
vitepress 构建报错 window is not defined

### ISSUE THREAD

**Issue by wulisensen** [xCss/Valine#408]
在vitepress 中引用，构建时报错

build error:
 ReferenceError: window is not defined
    at /Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:17:38752
    at /Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:17:38714
    at e.exports (/Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:17:39216)
    at Object.<anonymous> (/Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:17:22624)
    at t (/Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:7:316)
    at Object.<anonymous> (/Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:17:40271)
    at t (/Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:7:316)
    at /Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:7:699
    at /Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:7:710
    at /Users/wuguangsen/self/blog-vitepress/node_modules/valine/dist/Valine.min.js:7:81
error Command failed with exit code 1.

**Comment by ZhongxuYang** [comment]
解决了吗？我也有相同的错误

**Comment by ZhongxuYang** [comment]
You can use dynamic [import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) and call in `mounted` function.

like this:

```ts
const initValine = async () => {
  const { default: Valine } = await import('valine');
  const valineOptions = {
    el:'#vcomments',
    appId: '******',
    appKey: '******',
    path: window.location.pathname,
  };

  new Valine(valineOptions)
};

onMounted(() => {
  initValine()
})
```

**Comment by boring-plans** [comment]
> You can use dynamic [import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) and call in `mounted` function.
> 
> like this:
> 
> ```ts
> const initValine = async () => {
>   const { default: Valine } = await import('valine');
>   const valineOptions = {
>     el:'#vcomments',
>     appId: '******',
>     appKey: '******',
>     path: window.location.pathname,
>   };
> 
>   new Valine(valineOptions)
> };
> 
> onMounted(() => {
>   initValine()
> })
> ```

It works to me. Great thanks :D
