### ISSUE TITLE
hexo配置好valine输入评论没反应

### ISSUE THREAD

**Issue by xuesj1** [xCss/Valine#413]
各位大佬好，为什么我在hexo博客配置了valine后输入评论没有反应
我的配置步骤是，注册leancloud国际版账号，新建了一个名叫“valine”的应用，然后记录了appid和appkey，复制到了butterfly的评论配置处，在butterfly的配置文件中开启评论功能，然后部署了我的博客。接着我进入了我的博客，输入了评论，点击发布后底下的评论显示处转了一个圈并没有显示我的评论
我的博客：xuesj.top

**Comment by xCss** [comment]
Leancloud已经禁止了国内访问国际版
https://forum.leancloud.cn/t/2022-8/25408

**Comment by xuesj1** [comment]
谢谢
