### ISSUE TITLE
Valine从固定的CDN导入av-min.js导致加载缓慢

### ISSUE THREAD

**Issue by DiamondHunters** [xCss/Valine#416]
Valine版本：1.5.1
问题：
Valine 从 unpkg.com 加载 js av-min.js,这导致评论加载缓慢甚至失败
![image](https://user-images.githubusercontent.com/13744511/200828416-6d6ca1cd-89ed-4e90-850a-cc15841307bd.png)
![image](https://user-images.githubusercontent.com/13744511/200828774-fd18876e-5510-4fba-a8c0-9a80b5bcc043.png)
是否能将加载地址改为配置的形式呢？

**Comment by DiamondHunters** [comment]
可能是leancloud sdk的行为，不过不知道如何解决。

**Comment by xCss** [comment]
直接在网页源码中引入sdk试试：
``` html
<script src="https://cdn.jsdelivr.net/npm/leancloud-storage@3.15.0/dist/av-min.js"></script>
```

**Comment by DiamondHunters** [comment]
> 直接在网页源码中引入sdk试试：
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/leancloud-storage@3.15.0/dist/av-min.js"></script>
> ```

感谢您的回复已通过这种方式解决，翻看以前的issue发现也有类似解决方案，如果能加入文档使用CDN篇就好了，目前unpkg与jsdelivr在国内访问并不是很通畅
#404 在这个PR中看到了饿了吗CDN目前国内及国外访问速度都比较流畅，同时这个PR应该采用您在这里提到的方法解决
目前使用的CDN如下：
```
<script src="//github.elemecdn.com/leancloud-storage@3/dist/av-min.js"></script>
<script src='//github.elemecdn.com/valine@1.5.1/dist/Valine.min.js'></script>
```
感谢您与您的项目
