### ISSUE TITLE
Win10也显示Win11

### ISSUE THREAD

**Issue by Out-Of-Rain** [xCss/Valine#417]
![image](https://user-images.githubusercontent.com/102637907/205493519-dfbd3117-b690-4682-999b-fdb31c842c14.png)
实际用的是win10，显示的却是win11

最新版Valine版本
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

**Comment by xCss** [comment]
> 方才关注到#405 ![image](https://user-images.githubusercontent.com/102637907/205494754-8778a5aa-3124-468d-aed0-81d6ab05a380.png) Leancloud中ua一列识别是正确的，考虑从ua中取值？

既然关注到#405，那应该不会看漏`** 部分win10和win11的这个字符串是一样的，造成解析结果也是win11。**` 😸

**Comment by Out-Of-Rain** [comment]
好的，谢谢！
