### ISSUE TITLE
Valine.pure 打包输出问题

### ISSUE THREAD

**Issue by yscoder** [xCss/Valine#42]
前一阵子我提交了一个分离 CSS 后的 pure 版本打包的 PR，以便于自定义主题。一直没来得及实际运用，刚才加到博客试了一下，发现打包的输出有问题。

![image](https://user-images.githubusercontent.com/12295378/34427478-a6e2e6aa-ec7d-11e7-8860-f4ff1d30ddb7.png)

因为 webpack 中配置的 `output.library` 是 `'[name]'`，所以直接以文件名作为包名输出了。

![image](https://user-images.githubusercontent.com/12295378/34427506-f431eae6-ec7d-11e7-9e6d-84cf0ea9103b.png)

有两个修改建议，想征求下作者的意见：

1. 把 `library` 写成固定值 `Valine`，引用两个文件的调用一致，都是 `new Valine`
2. 把 `pure` 版本名称变为 `Valine_pure` 或 `ValinePure`，以便于可以直接访问（目前因为名称包含 `.`，必须 `window['Valine.pure']` 调用）

**Comment by xCss** [comment]
@yscoder ，最近太忙，很抱歉现在才回复你。
如果是把`library name`写成固定值`Valine`，打包出来会生成同样的`Valine.min.js`，目测应该会造成文件覆盖。

为了方便，那就使用`ValinePure`吧，后续版本加上~

感谢。
