### ISSUE TITLE
请问一下qq头像和昵称是怎么触发的

### ISSUE THREAD

**Issue by xiyuvi** [xCss/Valine#420]
我尝试在昵称输入qq号码后评论，没有获取到qq头像和昵称。还尝试在邮箱框输入qq邮箱，也没有获取到昵称和头像。请问一下，正确触发qq头像的操作是什么
![image](https://user-images.githubusercontent.com/38217058/210052197-adaa59e0-1c78-4265-aa32-fff9469f7803.png)
![image](https://user-images.githubusercontent.com/38217058/210052236-688a04b7-e8da-4b8e-a078-aa6d5b841dfd.png)

**Comment by xCss** [comment]
貌似接口证书过期了，我抽时间修复下，谢谢反馈

<img width="777" alt="image" src="https://user-images.githubusercontent.com/10877162/210210133-45e7bc38-7bae-49ba-b91c-cabea97f3e7e.png">

**Comment by Sitaye** [comment]
> 貌似接口证书过期了，我抽时间修复下，谢谢反馈
> 
> 
> 
> <img width="777" alt="image" src="https://user-images.githubusercontent.com/10877162/210210133-45e7bc38-7bae-49ba-b91c-cabea97f3e7e.png">
> 
> 

请问qq头像获取这个问题解决了吗？

**Comment by xCss** [comment]
@Sitaye @xiyuvi 已修复，每年要换SSL证书
