### ISSUE TITLE
leancloud国际版无法发布评论

### ISSUE THREAD

**Issue by Bayi-Cat** [xCss/Valine#421]
环境：Windows11，edge浏览器，nodejs版本v18.12.1，hexo-cli版本4.3.0，fluid主题版本1.9.4，leancloud国际版
leancloud白名单里配置了我的GitHub Page地址和localhost:4000
报错：
![image](https://user-images.githubusercontent.com/106531422/211759507-c50abed4-b8f7-4851-af97-9d751e332321.png)
发布评论后：
![image](https://user-images.githubusercontent.com/106531422/211760561-a7ad3f2f-f095-42c3-ad0e-3db8e3d78fd6.png)
lncldglobal.com也无法ping通：
![image](https://user-images.githubusercontent.com/106531422/211759829-cd0a09fa-6aa9-4528-8185-d50312d3078f.png)
网上还没有查到我这种问题，思来想去只能来这里提lssues了（手动捂脸哭），第一次用hexo搭个人Blog，希望大家指教

**Comment by ads38** [comment]
@Bayi-Cat 
楼主你好，我这两天也碰到这个问题.
但是Leancloud的 ```设置``` >> ```安全中心``` 有一段提示：
> 为方便开发调试，localhost 总是会被放行。

顺带提一下，```设置``` >> ```安全中心``` >> ```Web 安全域名``` 最好也填一下，比如 ```https://xxxxxxx.github.io```

我和你都使用的这种域名，即 ```https://你的appid前8位.api.lncldglobal.com```，在**主题配置文件**  ```_config.yml```里的```serverURLs```填的也是这个。

检查了好几遍```appId```, ```appKey```配置都没问题。后来发现这个 **域名（serverURLs）**无法访问。
具体表现是：我没翻墙的时候，valine无法加载，也不能发评论；但是用了翻墙软件之后**又可以**加载出来了，也可以发评论了。

所以我觉得是**Leancloud国际版**这个前8位appid域名的问题，我觉得这类域名应该是被防火墙屏蔽了。

**Comment by ads38** [comment]
我去了你的博客页面 [Hello world](https://bayi-cat.github.io/2023/01/11/hello-world/) 看到了valine评论组件
试了一下，没翻墙的时候评论没法加载也发不出去，但是翻墙之后就可以
@Bayi-Cat

**Comment by Bayi-Cat** [comment]
> 我去了你的博客页面 [Hello world](https://bayi-cat.github.io/2023/01/11/hello-world/) 看到了valine评论组件 试了一下，没翻墙的时候评论没法加载也发不出去，但是翻墙之后就可以 @Bayi-Cat

谢谢，祝你新年快乐

**Comment by Bayi-Cat** [comment]
> 我去了你的博客页面 [Hello world](https://bayi-cat.github.io/2023/01/11/hello-world/) 看到了valine评论组件 试了一下，没翻墙的时候评论没法加载也发不出去，但是翻墙之后就可以 @Bayi-Cat

@ads38 
非常感谢，在这里祝你新年快乐，原本用国际版是想图省事，但没想到真的给我《省事》了😅

**Comment by Zaitonn** [comment]
前几天也遇到了同样的问题，去问了官方

以下是官方回复，按照说明里面的设置自定义api域名即可，亲测有效
---
2022 年 8 月起，国际版共享域名不再向中国大陆提供服务。您可以绑定自己的 API 域名使用国际版，或者选择国内节点（华北或者华东节点）。详情见[这里](https://forum.leancloud.cn/t/2022-8/25408)的说明。

谢谢！

**Comment by Zaitonn** [comment]
![image](https://user-images.githubusercontent.com/103164490/215262344-d99670cb-e50f-439c-83c9-24e896348973.png)
![image](https://user-images.githubusercontent.com/103164490/215262347-67640878-d4f1-44cc-beca-b70788d683f5.png)

**Comment by klong970730** [comment]
我遇到同样的问题，但是就在刚刚，我找到了这个公告 [2022 年 8 月起，国际版共享域名不再向中国大陆提供服务](https://forum.leancloud.cn/t/2022-8/25408)，可能能够解答疑问，我没有买域名的打算，因此，我将考虑使用gitalk来实现评论
