### ISSUE TITLE
无法正常发送评论

### ISSUE THREAD

**Issue by pzwboy** [xCss/Valine#423]

**Comment by pzwboy** [comment]
使用的是LeanCloud国际版
APP ID和APP Key也配置好了
安全域名也有
正常显示评论框
![image](https://user-images.githubusercontent.com/88925003/212807216-ac6fdd4e-343e-4fca-9988-3cfb0791ade2.png)
无法发送评论
![image](https://user-images.githubusercontent.com/88925003/212807346-c5ad35b8-1747-48c6-82af-035304b17ed4.png)

**Comment by xCss** [comment]
[![image](https://user-images.githubusercontent.com/10877162/212823116-1bbfe91f-f5a1-4a7a-8aef-671313991e58.png)](https://user-images.githubusercontent.com/10877162/212823116-1bbfe91f-f5a1-4a7a-8aef-671313991e58.png)
抱歉，并没有看到Valine相关配置，给不了你相关建议~

**Comment by pzwboy** [comment]
sorry，刚刚换了个评论系统（还是用不了），配置在注释里

> ![image](https://user-images.githubusercontent.com/10877162/212823116-1bbfe91f-f5a1-4a7a-8aef-671313991e58.png) 抱歉，并没有看到Valine相关配置，给不了你相关建议~

**Comment by pzwboy** [comment]
<div id="vcomments"></div>
<script>
new Valine({
el: '#vcomments',
appId: 'RNHD6eVbeXRjkabXZBEnwGDM-MdYXbMMI',
appKey: 'vKPyxcjjedx3vPC2afXeyN3R'
})
</script>

**Comment by pzwboy** [comment]
@xCss 
看了下控制台，可能是因为us.avoscloud.com访问不了？

**Comment by xCss** [comment]
初始化的时候，加入`serverURLs`试试:
``` diff
new Valine({
    el: '#comments',
    appId: '',
    appKey: ''
+   serverURLs: https://xxxxxxxx.api.lncldglobal.com # 把xxxxxxxx替换为自己AppID的前8位字符
})
```

**Comment by pzwboy** [comment]
加入了，但仍然不能评论
```
我的AppId.api.lncldglobal.com/1.1/classes/Comment?where=%7B%22%24or%22%3A%5B%7B%22rid%22%3A%7B%22%24exists%22%3Afalse%7D%7D%2C%7B%22rid%22%3A%22%22%7D%5D%2C%22url%22%3A%22%2F%22%7D&order=-createdAt%2C-insertedAt&limit=0&count=1:1 
Failed to load resource: net::ERR_CONNECTION_CLOSED
```

**Comment by xCss** [comment]
> 



> @xCss 加入了，但仍然不能评论
> 
> ```
> 我的AppId.api.lncldglobal.com/1.1/classes/Comment?where=%7B%22%24or%22%3A%5B%7B%22rid%22%3A%7B%22%24exists%22%3Afalse%7D%7D%2C%7B%22rid%22%3A%22%22%7D%5D%2C%22url%22%3A%22%2F%22%7D&order=-createdAt%2C-insertedAt&limit=0&count=1:1 
> Failed to load resource: net::ERR_CONNECTION_CLOSED
> ```

我这是可以的~

**Comment by pzwboy** [comment]
`
Code 401: 未经授权的操作，请检查你的AppId和AppKey.
`
还是算了吧

**Comment by pzwboy** [comment]
waline正常发送评论
