### ISSUE TITLE
被恶意刷评论

### ISSUE THREAD

**Issue by asxez** [xCss/Valine#427]
被恶意刷评论！怎么办啊兄弟们

**Comment by so1ve** [comment]
Valine没后端 和数据库的交互都是直接在前端进行的，没法防 赶紧用waline吧

**Comment by YHX5129** [comment]
> Valine没后端 和数据库的交互都是直接在前端进行的，没法防 赶紧用waline吧

站主可以到leancloud删数据的

**Comment by YHX5129** [comment]
> 被恶意刷评论！怎么办啊兄弟们

到leancloud里删
