### ISSUE TITLE
使用npm模块方式无法导入

### ISSUE THREAD

**Issue by stkevintan** [xCss/Valine#43]
```json
{
  "name": "valine",
  "version": "1.1.8",
  "description": "A simple comment system based on Leancloud.",
  "main": "/src/Valine.js",
  "author": "xCss <xioveliu@gmail.com> (https://github.com/xCss)",
  "scripts": {
    "test": "webpack",
    "build": "webpack",
    "dev": "webpack-dev-server --env.dev",
    "clear": "rm -rf dist/* "
}
...
}
```
上述package.json里面把main指向了`src/Valine.js`,然而整个安装目录里面并没有`src`这个文件夹.

**Comment by Lucky4** [comment]
https://stackoverflow.com/questions/27267707/npm-warn-install-refusing-to-install-hapi-as-a-dependency-of-itself
应该修改package.json中的name。亲测好用。 @xCss @stkevintan

**Comment by xCss** [comment]
@stkevintan @Lucky4 很抱歉，最近太忙，现在才回复。
@stkevintan 所指出的问题应该是我发布到`npm`的时候，忽略了`src/Valine.js`文件，而`package.json`里的`main`又是指定的`src/Valine.js`文件，所以引用失败。下个版本修复

感谢反馈，祝好~
