### ISSUE TITLE
Valine有事件回调机制吗？想在提交评论成功能触发回调，做些其他处理

### ISSUE THREAD

**Issue by yangyongzhen** [xCss/Valine#431]
您好，Valine很不错。但是我翻遍文档没找到相关的话题。
想问下Valine有事件回调机制吗？想在提交评论成功能触发回调，做些其他处理。
如提交评论成功后，可以在回调事件里向后台发个消息告知后台。

目前Valine好像没有暴露出来事件接口，
希望有类似 onCommentSubmitted的回调接口，这样在外层，提交评论成功能触发可以做些其他处理。

**Comment by bnEars** [comment]
自己动手丰衣足食兄弟
`
    //提交评论
    document.querySelector('#vcomments').addEventListener('click',e=>{
        if(e.target==document.querySelector('#vcomments .vsubmit')){
            let nick = document.querySelector('#vcomments>.vpanel .vinput.vnick').value || 'Anonymous';
            let mail = document.querySelector('#vcomments>.vpanel .vinput.vmail').value || '';
            let content = document.querySelector('#vcomments>.vpanel #veditor').value || '';
            if(content){
                console.log(`${nick}(${mail})提交了评论：${content}`)
            }
        }
    })
`

**Comment by xCss** [comment]
已添加，请参考[v1.5.2](https://github.com/xCss/Valine/releases/tag/v1.5.2)
