### ISSUE TITLE
无法拉取 QQ 昵称，只显示 QQ 号和 QQ 头像 

### ISSUE THREAD

**Issue by Druadach** [xCss/Valine#432]
![image](https://github.com/xCss/Valine/assets/27998897/21147253-5a4a-411c-8d82-5572651624e1)

Version：1.5.1
Website：https://valine.js.org/

**Comment by xCss** [comment]
已在新版[v1.5.3](https://github.com/xCss/Valine/releases)中修复，感谢反馈🙏
