### ISSUE TITLE
能不能限制一下评论字数

### ISSUE THREAD

**Issue by wsly47** [xCss/Valine#46]
加一个自定义最大字数的设置项

**Comment by xCss** [comment]
抱歉，不太明白你为何需要这个限制。

既然是评论，那就有可能很长，为何要限制？

**Comment by wsly47** [comment]
https://valine.js.org/try.html 在手机上评论已经加载不出来了

**Comment by xCss** [comment]
可怕。。。

知道了，我限制下吧~

**Comment by xCss** [comment]
已加限制，最多10000字
