### ISSUE TITLE
评论不能键入空格和回车键

### ISSUE THREAD

**Issue by itgoyo** [xCss/Valine#48]
环境`Chrome 57.0.2987.133`  

系统`Ubuntu 17.04`

在[https://valine.js.org/try.html](https://valine.js.org/try.html)中测试，不能输入空格还有回车，是过滤掉了么，还是什么原因，不知道是不是我自身浏览器的原因，换了同事的win7 chrome也是不能键入空格和回车。

**Comment by xCss** [comment]
@itgoyo 感谢反馈，问题出在昨天做字数限制修改后动态替换掉了空字符串。
已修复，
祝好~ 😄
