### ISSUE TITLE
Jekyll怎么装呢

### ISSUE THREAD

**Issue by link9596** [xCss/Valine#51]
无意中看到了一个这么好的评论系统:heart_eyes:，可是到官网看教程只有Hexo的安装教程，Jekyll怎么装呢？也是类似的吗？:bowtie:

顺便反馈一个小Bug，就是评论框IE11内核无法输入中文:see_no_evil:

**Comment by xCss** [comment]
感谢反馈，`jekyll`请参考 https://staticblog.github.io/
