### ISSUE TITLE
建议添加最近评论接口，以及一些小意见。

### ISSUE THREAD

**Issue by a632079** [xCss/Valine#54]
需求和 #53 类似， 建议添加获取最近 x 条评论的接口 （可以做限制）。 以便实现和 WordPress 最近回复的类似功能。
小意见：
* 支持识别 IP位置 （如： 江苏，南京）
* 可以给浏览器信息，系统信息添加上 icon
* 支持异步加载 `<script async="async"` or `<script defer="defer"`
* 支持 emoji 😃 （可以尝试集成 owo 表情）
* 建议发布到 cdnjs， 这意味这将同步到国内大部分开放CDN。如：
  * BootCDN (https://github.com/bootcdn/cdnjs)
  * Staticfile (https://www.staticfile.org/about.html#howto , 同时支持手动提交)
* 增加喜欢功能. ❤️

**Comment by a632079** [comment]
* 头像异步加载

**Comment by BillYang2016** [comment]
资瓷，最后一个喜欢功能是顶踩功能的意思吧

**Comment by a632079** [comment]
@BillYang2016 对的
