### ISSUE TITLE
评论框添加问题

### ISSUE THREAD

**Issue by sillyY** [xCss/Valine#57]
显示错误:
ReferenceError: AV is not defined
Valine:1.1.7
反馈：https://github.com/xCss/Valine/issues

然后修改 code 为
var valine = new Valine({
            av: AV,
            el:'#vcomments',
            ...
          })
然后评论框消失

**Comment by wushaopei** [comment]
我也报这个错，请问怎么解决？

**Comment by sillyY** [comment]
我应该解决了，但我忘了解决过程， @wushaopei 你能具体描述下问题吗。

**Comment by sillyY** [comment]
突然发现这是好久之前的问题了

**Comment by wushaopei** [comment]
在valine 评论框下显示一下报错信息：

ReferenceError: AV is not defined
Valine:1.1.7
反馈：https://github.com/xCss/Valine/issues

然后评论框下方的进度条一直在缓冲之中

**Comment by wushaopei** [comment]
请问当时的解决方案还记得吗？我试过在 new Valine（{}）中进行定义 AV , 但是定义后，评论框就消失了

**Comment by sillyY** [comment]
不太记得之前的解决方案了，甚至不记得这里有个issue。 你能否提供下仓库地址？

**Comment by wushaopei** [comment]
https://github.com/wushaopei/wushaopei.github.io

**Comment by xCss** [comment]
还在1.1.7？这都多久之前的版本了？升级下版本不好么？

**Comment by sillyY** [comment]
现在好像没有av参数了吧? @xCss

**Comment by xCss** [comment]
> 现在好像没有av参数了吧? @xCss

有没有不影响~

**Comment by sillyY** [comment]
@wushaopei 你这仓库不是开发版本。 这样吧，升级下版本吧，我记得前段时间用了一次，没啥问题。
