### ISSUE TITLE
使用pjax时，报错：TypeError: Cannot read property 'Query' of undefined

### ISSUE THREAD

**Issue by yelog** [xCss/Valine#58]
##  问题描述
主题使用pjax，切换页面时不刷新整个页面。会出现下面的问题：
第一次加载页面，评论框可以正常使用，但是切换其他页面后（没有刷新整个页面），评论框下就显示`TypeError: Cannot read property 'Query' of undefined` ，需要刷新整个页面才能使用。

## 报错位置：new _root.v.Query('Comment');
这个 _root 中没有 v 这个属性。
刷新整个页面时，第一次执行到这句话是有 v 这个属性。
但是异步加载第二个页面后，第二次执行到这句话是没有 v 这个属性的。

## 报错效果
第一次访问加载成功，并且可以评论。
![image](https://user-images.githubusercontent.com/14227866/36719942-7881e98a-1be1-11e8-98f9-1f9913760bb4.png)

切换到其他文章就会出现问题。
![image](https://user-images.githubusercontent.com/14227866/36719901-5399c41c-1be1-11e8-974d-58b624ed36ae.png)

博客系统：`hexo`
主题：[hexo-theme-3-hexo](https://github.com/yelog/hexo-theme-3-hexo)
valine版本：`v1.1.9-beta4`

## 配置信息：

```html
<script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
<script src='//unpkg.com/valine/dist/Valine.min.js'></script>
<div id="comments"></div>
<script>
    var notify = '<%= theme.valine.notify %>' == true ? true : false;
    var verify = '<%= theme.valine.verify %>' == true ? true : false;
    new Valine({
        el: '#comments',
        notify: notify,
        verify: verify,
        app_id: "<%= theme.valine.appid %>",
        app_key: "<%= theme.valine.appkey %>",
        placeholder: "<%= theme.valine.placeholder %>",
        avatar:"<%= theme.valine.avatar %>",
        path: '<%=url%>'
    });
</script>
```

**Comment by xCss** [comment]
收到反馈，正在寻找解决办法~
