### ISSUE TITLE
增加 guest info 的必输项

### ISSUE THREAD

**Issue by geekrainy** [xCss/Valine#59]
当前 Valine 没有配置项导致 nick,mail,website 三者全为空也可以提交，希望增加对必输项的检测配置。

**Comment by xCss** [comment]
本来就是匿名评论啊，所以没必要强制必须吧~

**Comment by geekrainy** [comment]
只是建议哈，因为很多人并不知道需要填写信息，这样的话如果什么信息都没填写可能就收不到邮件通知等反馈了。

**Comment by LEAFERx** [comment]
同希望能增加选项 很多没有留邮箱就很难进一步联系

**Comment by ZvonimirSun** [comment]
我觉得这个可以加一个参数让用户来选择是否可以匿名，这样比较好

**Comment by redstoneleo** [comment]
建议还是增加下这个选项，以便站长有权把Valine当作匿名还是非匿名的评论系统，我搜了下有好几个类似的issue呢。
没有强制输入email的功能气人的一点是：你耐心地回复了别人，结果人家没有回看，得不偿失啊！
