### ISSUE TITLE
XSS Vulnerability

### ISSUE THREAD

**Issue by Goshin** [xCss/Valine#61]
## Vulnerability

Currently, the markdown input from users is processed into HTML preceding saving to BaaS server.

When querying comments, the raw HTML of comments, fields of `nick` and `link` are getting directly inserted in DOM in function `insertDom()` without any filtering and escaping.

This is **VULNERABLE** to XSS due to the potential unauthorized changes to the HTTP request and JS variables before saving to the backend.

## Demonstration

"Malicious" script can be appended and successfully run in client side.

```html
<img src="" onerror="alert('I can do something here')" />
```

![screenshot from 2018-03-14 11-05-22](https://user-images.githubusercontent.com/10056397/37381355-a0ef7e86-2777-11e8-8cbc-429dba6e1cd7.png)

## Fix

The most appropriate solution is to render markdown when querying comments and proceed to remove HTML tags again for other fields before inserted into DOM. However, it could break the backward compatibility for the present rendered data.

My workaround for this is to filter unnecessary HTML tags and attributes in `ret.comment`, with the [xss](https://github.com/leizongmin/js-xss) module imported.

https://github.com/Goshin/Valine/commit/b6dc0ffdbd829a2e52e1edf17fdbbae7161520c6

Feel free to ask for a pull request.

**Comment by xCss** [comment]
OK, I've got it, thank you for feedback.
