### ISSUE TITLE
邮件发送问题

### ISSUE THREAD

**Issue by XiaoPika** [xCss/Valine#62]
![](https://ws1.sinaimg.cn/large/83a16b6egy1fpf39j56zwj20aj02qq2t.jpg)
如图提示失败，我按照 https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE 的教程设置了后，评论回复别人没有邮件提醒，在LeanCloud选发送邮件直接提示未开启功能，能不能指点一二

**Comment by xCss** [comment]
抱歉，没遇到过这种情况。
能详细描述操作过程吗？

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/40033017-309bc300-5829-11e8-8322-4a0da71fc290.png)
勾选这个，但我设置了之后还是没有邮件提醒

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/40033591-9cacbb74-582b-11e8-885a-ff8d5d0438fe.png)
![image](https://user-images.githubusercontent.com/12557847/40033601-a9a419c6-582b-11e8-99b9-68833995f423.png)
我这样设置之后还是收不到邮件通知

**Comment by xCss** [comment]
@jintangWang 预览地址来一发~

**Comment by jintangWang** [comment]
@xCss [堂的博客](jintang.github.io)

**Comment by xCss** [comment]
@jintangWang 
`Code 403: 访问被api域名白名单拒绝，请检查你的安全域名设置.`

**Comment by jintangWang** [comment]
@xCss 哪个接口403了，大佬要不加个qq，这儿说不方便，841107370我的qq

**Comment by xCss** [comment]
@jintangWang https://shang.qq.com/wpa/qunwpa?idkey=0b1d38a3af24851aa2717fcb0fcf618a2ccb00811eb6d6f177c8f0d10dc2e81e

**Comment by jintangWang** [comment]
添加了
![image](https://user-images.githubusercontent.com/12557847/40034555-faece250-582f-11e8-9293-6d0d968fd242.png)，普通留言是收不到邮件通知的，但是@的时候可以，@xCss 666

**Comment by XiaoPika** [comment]
我的邮件问题也在这位博主@panjunwen 的帮助下完美解决了，谢谢两位大佬！
