### ISSUE TITLE
关于评论者邮箱的隐私问题

### ISSUE THREAD

**Issue by ZvonimirSun** [xCss/Valine#64]
我认为填写的邮箱应该只是用作接收评论通知的作用，不应该展现出来。

我现在发现，如果评论者只填写了邮箱而没有填写个人网站的话，评论后，点评论者的名称是一个mailto链接。这样基本等于是公开了评论者的邮箱，很不合适。

而且，可以查看评论者的邮箱和昵称，就可以伪造成他人的评论，毕竟就这两个关键字嘛。这样会造成很大的问题，强烈希望更改。

**Comment by ZvonimirSun** [comment]
我的朋友来评论我，结果我发现邮箱居然被这样公开了，实在是不太合适。

**Comment by fengzhao** [comment]
这个issue提的很好，我觉得很有必要了解一下

**Comment by ZvonimirSun** [comment]
@fengzhao 现在新的已经没有这个问题了
