### ISSUE TITLE
建议提供一个配置本地头像的设置

### ISSUE THREAD

**Issue by othorizon** [xCss/Valine#65]
因为gravatar在国内是无法显示的，建议提供一个本地头像文件设置选项

**Comment by a632079** [comment]
valine使用了反代， 不存在无法访问的问题

**Comment by othorizon** [comment]
@a632079 并没有使用吧，比如头像的地址链接是gravatar.cat.net

**Comment by a632079** [comment]
这个就是代理。。





------------------ 原始邮件 ------------------
发件人: "Rizon"<notifications@github.com>;
发送时间: 2018年3月23日(星期五) 晚上10:55
收件人: "xCss/Valine"<Valine@noreply.github.com>;
抄送: "Jonson Petard"<a632079@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [xCss/Valine] 建议提供一个配置本地头像的设置 (#65)




@a632079 并没有使用吧，比如头像的地址链接是gravatar.cat.net

**Comment by wsly47** [comment]
如果可以自定义镜像地址就好了

**Comment by Showfom** [comment]
因为备案原因，我们把 `gravatar.cat.net` 已经更换域名为 `gravatar.loli.net` 并且设置缓存为 7 天，之前设置缓存是 30 天

旧的域名目前是 301 跳转，所以暂时不会做改变

**Comment by xCss** [comment]
惊现烧饼，缘来如此。

目前头像镜像已经支持自定义啦~

**Comment by Showfom** [comment]
默认的头像可以用我们的 `gravatar.loli.net` 国内部署在阿里云 CDN 国外部署在 Cloudflare 嘿嘿

**Comment by othorizon** [comment]
@a632079 嗯，之前是我搞错了，`https://gravatar.cat.net`这个我这里的确实访问不了，因此也就没多想，想当然以为是没配置，话说看下域名也知道是个镜像地址了啊，丢人了🤦‍♂️。

----
后来发现自己的服务器的https也访问不了，一番非常艰辛的探查后才发现是被网关屏蔽了
