### ISSUE TITLE
Markdown关于公式渲染的问题

### ISSUE THREAD

**Issue by BillYang2016** [xCss/Valine#67]
能否让valine使用LaTeX渲染数学公式。  
比如接入hexo里装好的mathjax引擎（配置文件添加选项），或者自行接入。  
毕竟如果支持markdown却不支持LaTeX就如同鸡肋了。

**Comment by Blog-Shq** [comment]
+1 强烈建议滋瓷MathJax / LeTaX

**Comment by xCss** [comment]
下个版本会自动检测当前网页是否已经引入过`mathjax`
如果已引入就会自动渲染。
