### ISSUE TITLE
头像设置 与 评论删除 问题

### ISSUE THREAD

**Issue by monster-gump** [xCss/Valine#69]
看了一下官网的头像设置... 坦白说没太看懂，哪位大神能详细解说下吗？
评论能否删除呢？有点担心开放评论后可能会被爬虫攻击之类的，要如何防护和管理呢？谢谢。

**Comment by xCss** [comment]
### 评论数据管理：
`登录Leancloud`>选择你创建的`应用`>`存储`>选择Class`Comment`，然后就可以尽情的发挥你的权利啦(～￣▽￣)～

### 关于攻击：
你可以开启验证码选项`verify: true`
