### ISSUE TITLE
Code 403: 访问被api域名白名单拒绝，请检查你的安全域名设置.

### ISSUE THREAD

**Issue by raydied4** [xCss/Valine#72]

**Comment by xCss** [comment]
这个提示这么明显了。
请确认你当前访问的域名在`安全域名`列表中
> 请注意http和https

**Comment by soon-will** [comment]
@raydied4 @xCss 请问这个安全域名怎么查看呢，我设置了：https://soon-will.github.io，但依然提示上面的错误。

**Comment by xCss** [comment]
@soon-will 你的不是正常的吗？

[![_20181209144612](https://user-images.githubusercontent.com/10877162/49694215-35857a00-fbc1-11e8-906c-2feb18119861.png)](https://user-images.githubusercontent.com/10877162/49694215-35857a00-fbc1-11e8-906c-2feb18119861.png)

**Comment by soon-will** [comment]
@xCss 谢谢你哈，可能是我这边缓存没有清除干净。
