### ISSUE TITLE
头像设置问题

### ISSUE THREAD

**Issue by monster-gump** [xCss/Valine#73]
想问一下作为博主有什么办法定义自己的头像吗？
就是当自己回复别人的时候 让其他人看得出来这是博主的回复？
我对 gravatar 不是太了解，看了一下是说注册一个账号之后可以通用吗？ 但这个和 valine 的评论区又是什么关系，没看到设置文件里面可以绑定的呀。

**Comment by xCss** [comment]
去 [Gravatar 官网](https://en.gravatar.com/) 注册一个账号，然后设置好头像。在留言的时候留下你的邮箱，就会自动去同步匹配`Gravatar`的头像。
