### ISSUE TITLE
Valine评论在移动端的适配问题

### ISSUE THREAD

**Issue by TianZonglin** [xCss/Valine#76]
- Android个别浏览器比如夸克，会加载失败，不显示评论
- 在可适配的浏览器内，现有布局为竖型布局，但左侧留空不足，会出现控件整体溢出，会遮挡到一小部分头像
- Valine自定义的样式如何实现？官方网站好像没找到

**Comment by xCss** [comment]
@TianZonglin 感谢反馈。
- 在夸克中无法显示评论这是个已知Bug，目前暂未找到解决办法
- `在可是配的浏览器内`，请问是哪些浏览器出现布局问题。
- 自定义样式请参考[Valine.scss](https://github.com/xCss/Valine/blob/master/src/Valine.scss)

**Comment by TianZonglin** [comment]
了解。布局整体结构没问题，我说的主要是美观的方面，现在外加了一层section包裹已经解决了。
感谢解答。
