### ISSUE TITLE
Code 403: 访问被api域名白名单拒绝

### ISSUE THREAD

**Issue by Lamborshea** [xCss/Valine#77]
我的博客（blog.xienanbo.com）开启 https 后，加载 Valine.js后的评论框里出现了这个内容，是什么意思呢？

**Comment by Lamborshea** [comment]
已经解决了，LeanCloud里之前配的Web 安全域名是 http 协议开头，现在添加 https 之后当然会报错了。

**Comment by yangxuyu** [comment]
谢谢!

**Comment by yyymmp** [comment]
记住,https端口443.mmp,忘记了,卡了半天
