### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [xCss/Valine#79]
Hi

We would like to host your library on cdnjs

We have question about [files to host](https://github.com/cdnjs/cdnjs/pull/12331#pullrequestreview-85617753) and [library license](https://github.com/cdnjs/cdnjs/pull/12331#discussion_r158764428)
Could you help with it?
Thanks

**Comment by xCss** [comment]
Yep~ Recently too busy, I'm sorry to reply you now.
I'm honored to be able to help you, but this pull request belongs to @cy91244 . 
What should I do?

Ps: I once submitted pr to this repo https://github.com/cdnjs/cdnjs/pull/12649

**Comment by sashberd** [comment]
![screen shot 2018-05-03 at 10 10 01 1](https://user-images.githubusercontent.com/11975561/39563798-40ff6008-4eba-11e8-81e8-f9f5d2cce799.png)
![screen shot 2018-05-03 at 10 10 12](https://user-images.githubusercontent.com/11975561/39563799-411fe83c-4eba-11e8-8469-3ad8edc1eaf0.png)

**Comment by xCss** [comment]
These two documents are in my locality. 
- [escape.js](https://github.com/xCss/Valine/blob/master/src/escape.js) 
- [escape.min.js](https://github.com/xCss/Valine/blob/master/dist/escape.min.js) 
- [detect.js](https://github.com/xCss/Valine/blob/master/src/detect.js)
- [detect.min.js](https://github.com/xCss/Valine/blob/master/dist/detect.min.js)

They don't have to be added to the CDNJS. Thanks.

**Comment by sashberd** [comment]
And license of the library is ISC?

**Comment by xCss** [comment]
License of the library is [GPL-2.0](https://github.com/xCss/Valine/blob/master/package.json#L19)

**Comment by sashberd** [comment]
Thanks

**Comment by sufuf3** [comment]
@xCss Thank you for your help.
Would you please let us know can `src/Valine.js` be used in web front-end?
Many thanks.

**Comment by xCss** [comment]
@sufuf3 Sorry, because of the new syntax of ES6, some browsers will not support it. And it also contains the SCSS file.
But compiled `dist/Valine.min.js` can be used for front-end.

**Comment by sufuf3** [comment]
Thank you for your reply. :)
