### ISSUE TITLE
The target element was not found.

### ISSUE THREAD

**Issue by codefine** [xCss/Valine#8]
在next中配置valine后，首页报错The target element was not found.
另外希望在首页中能加入评论显示数量

**Comment by codefine** [comment]
已解决。
检查了一遍逻辑，我在valine.swig里面把page.comments的判断加上就好了。

**Comment by xiaweiss** [comment]
我配置了之后，不显示数量，也报这个错。请问具体怎么加？主题配置文件里 并没有这个变量 page.comments

**Comment by codefine** [comment]
@xiaweiss 评论数量只在评论区显示，在主页和文章页页头区域本来就不显示，估计是没有这个功能。
关于这个报错的解决方法：
打开文件themes/next/layout/_third-party/comments/valine.swig。
第1行`{% if theme.valine.enable and theme.valine.appid and theme.valine.appkey %}`添加page.comments判断条件，改为`{% if page.comments and theme.valine.enable and theme.valine.appid and theme.valine.appkey %}`。
第4行，插件版本更新为1.1.6。

**Comment by xCss** [comment]
@codefine next主题中首页报`The target element was not found.`是我判断不严谨造成的。后面会提交pr修复。感谢反馈
@xiaweiss 针对首页评论数量的展示，目前正在寻找解决方案，如果解决了会及时通知大家的~

感谢关注。
