### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by fengbjhqs** [xCss/Valine#80]
您好

这个好像会导致App Key的泄露，会不会存在安全问题？

就必须设置安全域名？

有没有考虑使用 preact做视图层的渲染呢？

**Comment by xCss** [comment]
安全域名存在的作用是存在你设置的域名列表里的域名才能使用这个appkey和appid，未在域名列表中的域名则没有权限使用。

就是因为appkey和appid是明文，所以才让你设置安全域名。

现在暂时还没空学习Preact，等我学会了再看吧。~

祝好！
