### ISSUE TITLE
可以支持微信小程序评论插件吗？

### ISSUE THREAD

**Issue by yicm** [xCss/Valine#81]
微信小程序不支持直接导入js使用，因此av-min.js和Valine.min.js可以导出开放的函数吗？然后去调用，从而支持微信小程序的评论插件？

**Comment by xCss** [comment]
抱歉，由于小程序不支持HTML元素，所以valine暂时还不支持小程序。

后面如果有时间，我会写一个独立版本吧。~

**Comment by yicm** [comment]
我自己写了个，也是使用leancloud，无需个人或者云服务器即可使用 [https://github.com/yicm/WxComment](https://github.com/yicm/WxComment)
