### ISSUE TITLE
希望修改Avatar的CDN

### ISSUE THREAD

**Issue by myloft** [xCss/Valine#83]
https://gravatar.loli.net/avatar的CDN缓存时间太长，导致用户修改头像无法及时生效,Automattic近期自建了CDN，不再使用被墙严重的EdgeCast，所以大陆已经可以正常访问。希望使用源地址。

**Comment by xCss** [comment]
@myloft 
`Valine` 已经在上个版本支持自定义`头像镜像`，参考：https://valine.js.org/configuration/#avatar_cdn

**Comment by myloft** [comment]
谢谢
