### ISSUE TITLE
无法评论，Code 119: 119

### ISSUE THREAD

**Issue by yanzhonghui** [xCss/Valine#84]
发表评论时，提示Code 119: 119

**Comment by xCss** [comment]
请留下预览地址~

我好定位问题。

**Comment by xCss** [comment]
`Code 119 ：该操作已被禁止，请变更应用选项『禁止客户端创建 Class』。`

请确认你的设置。

![_20180514165159](https://user-images.githubusercontent.com/10877162/39987367-29bfeac6-5797-11e8-8911-79900d46f6c5.png)

**Comment by yanzhonghui** [comment]
![image](https://user-images.githubusercontent.com/29450950/39987250-cd4d38a2-5796-11e8-8164-43b9f0acc6b0.png)
前两天的时候，把加进去了，当时也没有测试一下，今天准备论的时候，发现无法评论。
你可以在这个页面评论一下看看，https://yanzhonghui.cn/about/
![image](https://user-images.githubusercontent.com/29450950/39987433-5fd1dd18-5797-11e8-8b32-81e835cfe60b.png)
![image](https://user-images.githubusercontent.com/29450950/39987460-6df4782e-5797-11e8-88b4-cf7b18da15b3.png)

**Comment by yanzhonghui** [comment]
😓原来是要去掉呀，我当初创建的时候，还特意勾选了！估计当时眼睛看花了。谢谢！我试一下。
