### ISSUE TITLE
Valine 部署在 hexo next主题上出现Code 119: 119情况

### ISSUE THREAD

**Issue by Blog-Shq** [xCss/Valine#87]
操作系统: Linux Deepin15 浏览器: Chrome

![img](https://raw.githubusercontent.com/Blog-Shq/Blog-Pictures/master/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20180526131834.png)

我已阅读相关的Issues : [无法评论，Code 119: 119](https://github.com/xCss/Valine/issues/84)
但是，我使用上述方法，更改`禁止客户端创建 Class`的选项，并没有什么改变

已重新卸载/安装，但是好像并没有什么用

My Blog: [链接](https://blog.ishq.site)

**Comment by Blog-Shq** [comment]
`hexo s --debug`命令其中显示`GET /articles/NOIP-2018-zero/dist/Valine.min.js 404 3.223 ms - 181
`

**Comment by xCss** [comment]
请尝试以下操作：
- 1、`存储`>`设置`>`其他`里面 **去掉**`禁止客户端创建Class` 前面的`√`，然后刷新页面
- 2、如果**操作1**不生效，请删除Class`Comment`，具体操作：`存储`>`Comment`>数据操作行`其他`>`删除Class`，然后刷新页面
- 3、如果**操作2**也不生效，那就请删除当前`应用`，然后重新创建`应用`并获取`APP_ID`和`APP_KEY`

> 注: 出现这种情况，一般都是自己手贱。
    所以，下次请注意。
