### ISSUE TITLE
问几个问题

### ISSUE THREAD

**Issue by fengzhao** [xCss/Valine#88]
If you want to report a bug, please provide the following information:

请问作为博主，如何实时收到别人评论？考虑过做微信接入吗？
请问作为博主，如何进行在线回复游客？
请问作为游客，评论之后，如何还能看到博主的回复？

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

**Comment by xCss** [comment]
> 请问作为博主，如何实时收到别人评论？

抱歉，暂不支持。

-------------------
> 考虑过做微信接入吗？

抱歉，暂不考虑。

--------------------
> 请问作为博主，如何进行在线回复游客？

很抱歉，Valine不是即时聊天，无法做到在线回复。

--------------------
> 请问作为游客，评论之后，如何还能看到博主的回复？

目前的Valine支持[邮件提醒](https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE)。游客如果有留下邮箱，那么博主的回复就能发送到游客邮箱。
