### ISSUE TITLE
为什么评论区变成了数字啊

### ISSUE THREAD

**Issue by fengzhao** [xCss/Valine#89]
If you want to report a bug, please provide the following information:

- The steps to reproduce.
- A minimal demo of the problem via https://jsfiddle.net or http://codepen.io/pen if possible.
- Which versions of Valine, and which browser / OS are affected by this issue?

为什么评论区变成了数字啊

**Comment by xCss** [comment]
Valine目前正在升级，由于操作失误，造成了某些bug，目前正在紧急修复，请耐心等待~

带来的不便，万分抱歉 🤦‍♂️

**Comment by dldylan** [comment]
原来是在升级？我也变成数字了就赶紧过来提 Issue 了，不是我这边的问题就好。
