### ISSUE TITLE
邮件提醒功能无法使用？

### ISSUE THREAD

**Issue by tanmx** [xCss/Valine#90]
version : v1.1.9-beta9
leancloud email: gmail

next settting:
valine:
  enable: true
  appid: *********************
  appkey: **********************
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: (发表评论) # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

no email alerts when new comments are made

**Comment by xCss** [comment]
邮件提醒目前的逻辑是：
> 回复已存在的评论的时候，如果当前被回复对象存在邮件，就给被回复对象发送邮件提醒。
