### ISSUE TITLE
Error 99也是由于升级造成的bug吗

### ISSUE THREAD

**Issue by 2048being** [xCss/Valine#91]
如图
![](https://i.loli.net/2018/06/15/5b2386d0b2f4b.png)

昨天晚上同时出现了Valine评论区变为数字“0”以及控制台显示Error 99的问题。
今天Valine能正常显示了，但Console还是有Error99错误。
另外我今天测试评论发现，刷新后评论消失了，不知是不是因为Error99而造成的

**Comment by 2048being** [comment]
我是最新的v1.1.9-rc2

![](https://i.loli.net/2018/06/15/5b2386d0e9e98.png)

![](https://i.loli.net/2018/06/15/5b2386d0f2282.png)

![](https://i.loli.net/2018/06/15/5b2386d0f3c72.png)

**Comment by xCss** [comment]
🤦‍♂️ 预览地址，网址、或者仓库地址~

**Comment by 2048being** [comment]
我的博客可以吗，打扰了
https://conyyon.ren

**Comment by xCss** [comment]
@2048being 这真的是你页面中的`el`元素不存在。
![qq 20180616114448](https://user-images.githubusercontent.com/10877162/41495472-b48171ac-715a-11e8-8366-514918929b56.png)

**Comment by 2048being** [comment]
小小白问一下该怎么办呢🤦‍♂️

**Comment by xCss** [comment]
@2048being 你用的是next主题，next主题里默认就已经嵌入好了valine，只需要配置config.yml里就好了

不过貌似你修改过。。。看不出来你的next主题版本是多少。。。

从next 5.1.3就开始内置valine了。

**Comment by 2048being** [comment]
对，我就是用的5.1.3，只是没有让他在页面底部现实版本，Valine里面填了appkey和appid，感觉步骤应该没错吧

**Comment by xCss** [comment]
@2048being 你是自己处理valine的吧？而不是用的内置版本？

**Comment by 2048being** [comment]
我用的内置版本，我知道了，是我的LeanCloud操作方式不对，现在可以了，打扰了，非常感谢，一直觉得Valine是hexo里面最好看而且使用最方便的评论系统，希望以后发展得更好😄😄😄
