### ISSUE TITLE
好像在未有评论的界面，会出现 Error 99 错误.

### ISSUE THREAD

**Issue by wangziling** [xCss/Valine#93]
- 打开 https://ling.js.org
- 打开 开发者工具
- you see.

![image](https://user-images.githubusercontent.com/24818903/41673384-5cdf8d2e-74ef-11e8-9755-780dfadb7a69.png)

### 下面是 相关的文件内容.
- _config.yml

![image](https://user-images.githubusercontent.com/24818903/41673448-89e4dc20-74ef-11e8-8e35-ccb87caa3e03.png)

- layout/_macro/post.swig

![image](https://user-images.githubusercontent.com/24818903/41673500-b927ed42-74ef-11e8-8382-387526765acc.png)

- layout/_third-party/comments/valine.swig

![image](https://user-images.githubusercontent.com/24818903/41673542-d21bf0b4-74ef-11e8-9b27-68facde55b8f.png)

**Comment by xCss** [comment]
好的，已重现bug，下个版本修复~

感谢反馈。:smile:

**Comment by xCss** [comment]
已修复 [#release - v1.1.9](https://github.com/xCss/Valine/releases/tag/v1.1.9)
