### ISSUE TITLE
应该加上邮箱强制小写？以保证gravatar头像正确显示

### ISSUE THREAD

**Issue by YohoYang** [xCss/Valine#94]
邮箱应该是不区分大小写的，gravatar识别的md5处理前的邮箱应该为全小写。

在valine的邮箱中输入全小写的邮箱可以对应到gravatar头像
但将几个字母修改为大写后md5码就不同了。

是否应该在提交前或者是输入时强制将用户输入的email处理为小写后再存储呢。

**Comment by xCss** [comment]
抱歉，这应该是属于用户习惯，而不是Valine来强制或者不强制大小写~
