### ISSUE TITLE
旧版Valine创建的空rid评论升级后消失

### ISSUE THREAD

**Issue by q234rty** [xCss/Valine#95]
使用Valine v1.1.9-rc2：
![image](https://user-images.githubusercontent.com/11485439/41833646-c7b3e14e-7883-11e8-8b1c-3a4233a1aa6d.png)

使用Valine v1.1.9或Valine v1.1.9-rc3：
![image](https://user-images.githubusercontent.com/11485439/41833627-aa3cf2c2-7883-11e8-99f1-bc6abb6ed6e4.png)

**Comment by q234rty** [comment]
![image](https://user-images.githubusercontent.com/11485439/41834007-32638dc2-7885-11e8-8f62-299d185d6fa6.png)
![image](https://user-images.githubusercontent.com/11485439/41834050-5cf9d870-7885-11e8-843f-bc34902590d4.png)
似乎是因为有没有rid这一项的影响。

**Comment by xCss** [comment]
@q234rty 这不是bug
因为`v1.1.9`版本启用了楼中楼评论样式，没有`rid`的评论会被程序认为是主评论，而带有`rid`的评论则是上一个`id`为当前`rid`的评论的子评论。

如果你手动删掉了`当前子评论`的`父级评论`，则程序会认为`当前子评论`没有`父级评论`而被抛弃

**Comment by q234rty** [comment]
@xCss 但是旧版Valine对于主评论会创建空的`rid`（而不是没有`rid`），导致评论消失

**Comment by xCss** [comment]
@q234rty 我研究下吧，看看有什么好的处理方式。

不过还是推荐尽快升级~ :smile:
