### ISSUE TITLE
配置完成后评论结果是undefined

### ISSUE THREAD

**Issue by Rain120** [xCss/Valine#97]
![1](https://user-images.githubusercontent.com/20939839/42310649-8c1edca4-806e-11e8-8d3b-711b36073fd2.png)
![2](https://user-images.githubusercontent.com/20939839/42310651-8c586366-806e-11e8-883c-81723a3bb673.png)

问题截图，这是为什么怎么解决啊

**Comment by Rain120** [comment]
@xCss  https://rain120.github.io/2018/06/25/netease-slider/

**Comment by xCss** [comment]
@Rain120 
你开启了`leancloud_visitor`，然而并没有设置阅读量统计的appId和appKey
Valine的初始化被`leancloud_visitor`初始化(`空初始化`)覆盖了，所以会造成回复出现`undefined`

解决办法：
> 关闭`leancloud_visitor`
> **或者**
> 设置`leancloud_visitor`的appid、appkey为Valine的appid、appkey
---------------------------
> Ps: 你还开启了`disqus`、`来比力`

**Comment by Rain120** [comment]
@xCss 问题已经解决，disqus,来必力开发版本已经关闭了，线上版本没有提交，谢谢大佬
