### ISSUE TITLE
使用新版似乎跟leancloud_visitor冲突

### ISSUE THREAD

**Issue by cugxuan** [xCss/Valine#99]
我一两个月前更新了hexo和next版本，现在的valine版本是v1.2.2
但是现在评论数还是显示的valine应用中的评论数，但是在显示栏并没有这些评论，显示的是leancloud_visitor应用中_comment里面的评论。
我的博客就是一个例子--->[Xuan's blog](http://cugxuan.coding.me)

**Comment by xCss** [comment]
@cugxuan ，对于`Valine`和`leancloud_visitor`冲突问题是一直都存在的。

如果你是使用的两个不同的应用，就会出现冲突。

是因为`Valine`初始化被`leancloud_visitor`初始化覆盖，造成评论数据存储到`leancloud_visitor`应用的`Comment`里了，所以可能会出现`有评论数`，但`评论列表为空`的情况。

解决办法：
> 请换成`同一个应用`(使用相同的`appid`和`appkey`)。或者使用Valine自带的[visitor](https://valine.js.org/visitor.html)

**Comment by cugxuan** [comment]
我想过要换成同一个应用，但是有个问题是没找到leancloud数据导出的地方，这样会丢失一些数据。
我晚上回去再试试吧，谢谢！

**Comment by xCss** [comment]
@cugxuan `数据导出`了解下
[![qq 20180710094413](https://user-images.githubusercontent.com/10877162/42484500-d4f4839c-8425-11e8-97cc-4d6de04086d2.png)](https://user-images.githubusercontent.com/10877162/42484500-d4f4839c-8425-11e8-97cc-4d6de04086d2.png)

**Comment by cugxuan** [comment]
@xCss oh，我居然之前没找到。。感谢！我晚上回去试试。
